export const PRODUCT_NAME: 'Aeldrune';
export const PACKAGE_NAME: 'aeldrune-desktop';
export const APP_ID: 'com.aeldrune.desktop';
export const APP_ORIGIN: 'app://worldofclaudecraft';
export const DEEP_LINK_PROTOCOL: 'aeldrune';
export const LEGACY_DEEP_LINK_PROTOCOL: 'worldofclaudecraft';
export const PRODUCTION_API_ORIGIN: 'https://aeldrune.tibiadepot.com';
export const DESKTOP_UPDATE_URL: 'https://aeldrune.tibiadepot.com/desktop-updates';
export const GAME_PROFILE: 'mir4-gameplay-port';
