// GENERATED by scripts/build_dawnhold_map.mjs; do not edit by hand.
// Re-bake with `npm run assets:dawnholdmap` after any Dawnhold layout or
// plan-palette change (tests/dawnhold_map_baked.test.ts guards freshness).
// Plates live in public/map_bg/dawnhold_<story>.webp.

export const BAKED_DAWNHOLD_MAP = {
  fingerprint: '5f3412d5',
  plateWidth: 640,
  plateHeight: 640,
  stories: ["ground","solar"],
} as const;
