// GENERATED by scripts/build_lastkeep_map.mjs; do not edit by hand.
// Re-bake with `npm run assets:lastkeepmap` after any Last Keep layout or
// plan-palette change (tests/lastkeep_map_baked.test.ts guards freshness).
// Plates live in public/map_bg/lastkeep_<story>.webp.

export const BAKED_LASTKEEP_MAP = {
  fingerprint: '9090ab31',
  plateWidth: 736,
  plateHeight: 992,
  stories: ["undercroft","state","residence","tower"],
} as const;
