// Exact runtime identities from the audited live mob aura census. Keep this
// closed: mob producers often share prefixes with player abilities, so family
// or prefix inference can silently assign the wrong painting.
const MOB_AURA_ICON_IDENTITIES: ReadonlyMap<string, string> = new Map([
  ['arcaneRot_deacon_voss', 'mob_arcane_rot'],
  ['arcaneRot_rift_void_acolyte', 'mob_arcane_rot'],
  ['aoe_slow', 'mob_aoe_slow'],
  ['bleed_ridge_stalker', 'mob_bleed'],
  ['bleed_rift_thornback', 'mob_bleed'],
  ['bleed_wildheart_ravager', 'mob_bleed'],
  ['blind_vale_bandit', 'mob_blind'],
  ['blood_frenzy', 'mob_frenzy_on_hit'],
  ['cinder_ironvein_sapper', 'mob_cinder'],
  ['cinder_rift_boss_ember', 'mob_cinder'],
  ['cinder_rift_ember_fiend', 'mob_cinder'],
  ['concuss_brakka_wallbreaker', 'mob_concuss'],
  ['concuss_rift_boss_storm', 'mob_concuss'],
  ['concuss_rift_storm_caller', 'mob_concuss'],
  ['concuss_thornpeak_ogre', 'mob_concuss'],
  ['corrode_deepfen_murloc', 'mob_corrode'],
  ['corrode_reliquary_ledger_wraith', 'mob_corrode'],
  ['corrode_rift_deep_lurker', 'mob_corrode'],
  ['cost_tax_gravecaller_mender', 'mob_cost_tax'],
  ['critvuln_mire_widow', 'mob_crit_vuln'],
  ['disarm_ogre_crusher', 'mob_disarm'],
  ['enervate_boneclad_revenant', 'mob_enervate'],
  ['enfeeble_threnos_first_voice', 'mob_enfeeble'],
  ['enfeeble_wyrmcult_zealot', 'mob_enfeeble'],
  ['ensnare_rift_boss_venom', 'mob_ensnare'],
  ['ensnare_rift_venom_weaver', 'mob_ensnare'],
  ['ensnare_webwood_spider', 'mob_ensnare'],
  ['expose_varkas_boneguard', 'mob_expose'],
  ['frostbite_rift_rime_elemental', 'mob_frostbite'],
  ['frostbite_shardlord_kazzix', 'mob_frostbite'],
  ['heal_absorb_gravecaller_summoner', 'mob_heal_absorb'],
  ['heal_absorb_rift_boss_necro', 'mob_heal_absorb'],
  ['hex_gravecaller_cultist', 'mob_hex'],
  ['hex_mudfin_murloc', 'mob_polymorph_hex'],
  ['lockout_threnos_first_voice', 'mob_lockout'],
  ['lockout_wyrmcult_zealot', 'mob_lockout'],
  ['mirefen_widowling_chill', 'mob_chill_on_hit'],
  ['mob_charge_stun', 'mob_charge_stun'],
  ['mob_demoralize', 'mob_demoralize'],
  ['mortal_wound_bastion_revenant', 'mob_mortal_strike'],
  ['mortal_wound_deathstalker_voss', 'mob_mortal_strike'],
  ['mortal_wound_reliquary_gravecall_acolyte', 'mob_mortal_strike'],
  ['mortal_wound_voskar_emberwing', 'mob_mortal_strike'],
  ['pack_frenzy', 'mob_pack_frenzy'],
  ['plague_drowned_dead', 'mob_plague'],
  ['plague_drowned_warlord', 'mob_plague'],
  ['raise_bone_mage', 'mob_spell_vuln'],
  ['rally_ironvein_foreman', 'mob_rally'],
  ['rampage_rift_boss_brute', 'mob_rampage'],
  ['rampage_warlord_drogmar', 'mob_rampage'],
  ['rift_frost_revenant_chill', 'mob_chill_on_hit'],
  ['silence_gravecaller_summoner', 'mob_silence'],
  ['siphon_spirit_sister_nhalia', 'mob_siphon_spirit'],
  ['slowstrike_mire_prowler', 'mob_slow_strike'],
  ['smolder_ironvein_sapper', 'mob_smolder'],
  ['smolder_rift_hellguard', 'mob_smolder'],
  ['smolder_rift_magma_brute', 'mob_smolder'],
  ['soulrot_restless_bones', 'mob_soulrot'],
  ['soulrot_rift_boss_necro', 'mob_soulrot'],
  ['soulrot_rift_boss_ritualist', 'mob_soulrot'],
  ['soulrot_rift_pact_acolyte', 'mob_soulrot'],
  ['spellvuln_rift_boss_arcane', 'mob_spell_vuln'],
  ['spellvuln_stormcrag_elemental', 'mob_spell_vuln'],
  ['stackpoison_mirefen_broodmother', 'mob_stack_poison'],
  ['stackpoison_rift_boss_venom', 'mob_stack_poison'],
  ['stagger_deeprock_kobold', 'mob_stagger_hit'],
  ['stoneskin_ancient_guardian', 'mob_stoneskin'],
  ['stoneskin_marrowlord_varkas', 'mob_stoneskin'],
  ['stoneskin_old_marrowshell', 'mob_stoneskin'],
  ['stoneskin_rift_boss_arcane', 'mob_stoneskin'],
  ['stoneskin_rift_boss_frost', 'mob_stoneskin'],
  ['stoneskin_sump_troll_devourer', 'mob_stoneskin'],
  ['stoneskin_thunzharr_waking_peak', 'mob_stoneskin'],
  ['stormcrag_elemental_chill', 'mob_chill_on_hit'],
  ['stun_mogger_lackey', 'mob_stun_on_hit'],
  ['stun_rift_stone_ogre', 'mob_stun_on_hit'],
  ['tongues_nhalia_mourner', 'mob_tongues'],
  ['venom_duskwisp', 'mob_venom'],
  ['venom_old_marrowshell', 'mob_venom'],
  ['venom_rift_venom_weaver', 'mob_venom'],
  ['venom_webwood_spider', 'mob_venom'],
  ['vulnerability_gravecaller_cultist', 'mob_vulnerability'],
  ['warcry_deepfen_murloc', 'mob_warcry'],
  ['warcry_wildheart_beastmaster', 'mob_warcry'],
  ['ward_grave_silt_bulwark', 'mob_ward_allies'],
  ['ward_mogger', 'mob_ward_allies'],
  ['ward_treant_elder', 'mob_ward_allies'],
  ['ward_wildheart_beastmaster', 'mob_ward_allies'],
  ['wither_fen_troll', 'mob_wither'],
]);

/** Painted family identities owned by the audited mob-aura catalog. */
export const MOB_AURA_IMAGE_IDS: ReadonlySet<string> = new Set(MOB_AURA_ICON_IDENTITIES.values());

/** Return painted art for one exact live mob aura runtime ID. */
export function resolveMobAuraIconIdentity(runtimeId: string): string | null {
  return MOB_AURA_ICON_IDENTITIES.get(runtimeId) ?? null;
}
