import type { AbilityVfxFullSpec, AbilityVfxSpec } from './ability_vfx_core';

// Aeldrune's Warrior uses the MIR4-authored action identities, timings, and
// roles, but composes them from the pooled Three.js primitives already shipped
// by this runtime. These specs deliberately do not alias classic WoC abilities.
const COMPACT: Readonly<Record<string, AbilityVfxSpec>> = {
  mir4_skill_1102: {
    c: '#d7e7ff',
    p: 'physical',
    pw: 1.2,
    sp: 30,
    li: 0.75,
    lg: 0.8,
    a: 'strike',
  },
  mir4_skill_1302: {
    c: '#ffc34d',
    p: 'blood',
    pw: 1.25,
    sp: 34,
    rg: 1.45,
    vr: 1,
    li: 1.15,
    lg: 1.2,
    a: 'shout',
  },
  mir4_skill_1301: {
    c: '#f4f8ff',
    p: 'physical',
    pw: 1.3,
    sp: 24,
    vr: 1,
    li: 0.9,
    lg: 0.9,
    a: 'strike',
  },
  mir4_skill_1101: {
    c: '#ff5b32',
    p: 'blood',
    pw: 1.4,
    sp: 42,
    rg: 1.5,
    vr: 1,
    db: 1,
    li: 1.2,
    lg: 2.2,
    a: 'nova',
  },
  mir4_skill_1103: {
    c: '#ff8a3d',
    p: 'blood',
    pw: 1.35,
    sp: 38,
    rg: 1.25,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.1,
    lg: 1.4,
    a: 'dash',
  },
  mir4_skill_1104: {
    c: '#ff334f',
    p: 'blood',
    pw: 1.32,
    sp: 32,
    vr: 1,
    db: 1,
    li: 0.95,
    lg: 1,
    a: 'strike',
  },
  mir4_skill_1501: {
    c: '#79dcff',
    p: 'physical',
    pw: 1.48,
    sp: 48,
    rg: 1.7,
    vr: 1,
    li: 1.3,
    lg: 2,
    spin: 1,
    a: 'nova',
  },
  mir4_skill_1201: {
    c: '#8ba7c7',
    p: 'physical',
    pw: 1.25,
    sp: 28,
    rg: 1.35,
    vr: 1,
    db: 1,
    sm: 1,
    li: 0.85,
    lg: 1.8,
    a: 'cc',
  },
  mir4_skill_1601: {
    c: '#ffe08a',
    p: 'physical',
    pw: 1.38,
    sp: 36,
    vr: 1,
    li: 1,
    lg: 1.1,
    a: 'strike',
  },
  mir4_skill_1304: {
    c: '#d8894b',
    p: 'physical',
    pw: 1.18,
    sp: 28,
    rg: 0.8,
    vr: 1,
    db: 1,
    li: 0.75,
    lg: 0.8,
    a: 'dash',
  },
  mir4_skill_1401: {
    c: '#d69a55',
    p: 'physical',
    pw: 1.45,
    sp: 46,
    rg: 1.65,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.2,
    lg: 2.4,
    a: 'strike',
  },
  mir4_skill_1502: {
    c: '#ffd36a',
    p: 'physical',
    pw: 1.15,
    sp: 20,
    rg: 1.2,
    vr: 1,
    db: 1,
    li: 1.1,
    lg: 3,
    a: 'buff',
  },
  mir4_ultimate_1: {
    c: '#ff6a21',
    p: 'blood',
    pw: 1.85,
    sp: 60,
    rg: 2,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.9,
    lg: 3.8,
    spin: 1,
    fin: 1,
    a: 'nova',
  },
};

const FULL: Readonly<Record<string, AbilityVfxFullSpec>> = {
  mir4_skill_1102: {
    archetype: 'strike',
    palette: 'physical',
    tint: '#d7e7ff',
    accent: '#6e4aff',
    rim: '#f7fbff',
    power: 1.2,
    strike: { swings: 3, arc: 'horizontal' },
    motifs: ['crescents'],
    motifAt: 'target',
    linger: 0.8,
    impact: { trail: 'x', sparks: 30, flipbook: false, ring: false, light: 0.75 },
  },
  mir4_skill_1302: {
    archetype: 'shout',
    palette: 'blood',
    tint: '#ffc34d',
    accent: '#ff5a2b',
    rim: '#fff0a8',
    power: 1.25,
    shout: { radius: 7 },
    motifs: ['implosion'],
    motifAt: 'caster',
    nova: { radius: 7 },
    linger: 1.2,
    impact: { ring: 1.45, vRing: 0.75, sparks: 34, smoke: true, light: 1.15 },
  },
  mir4_skill_1301: {
    archetype: 'strike',
    palette: 'physical',
    tint: '#f4f8ff',
    accent: '#76b7ff',
    rim: '#ffffff',
    power: 1.3,
    strike: { swings: 1, arc: 'uppercut' },
    windupStyle: 'stance',
    linger: 0.9,
    impact: {
      trail: 'riposte',
      sparks: 24,
      flipbook: false,
      ring: false,
      vRing: true,
      light: 0.9,
    },
  },
  mir4_skill_1101: {
    archetype: 'nova',
    palette: 'blood',
    tint: '#ff5b32',
    accent: '#ffb22e',
    rim: '#ffd0a0',
    power: 1.4,
    motifs: ['bladestorm', 'implosion'],
    motifAt: 'caster',
    nova: { radius: 7 },
    linger: 2.2,
    impact: {
      flipbook: true,
      ring: 1.5,
      vRing: 1,
      sparks: 42,
      debris: true,
      light: 1.2,
    },
  },
  mir4_skill_1103: {
    archetype: 'dash',
    palette: 'blood',
    tint: '#ff8a3d',
    accent: '#ffd057',
    rim: '#fff0bf',
    power: 1.35,
    windupStyle: 'stance',
    motifs: ['fissure', 'implosion'],
    motifAt: 'target',
    decal: 'crack',
    linger: 1.4,
    impact: {
      trail: 'overhead',
      flipbook: true,
      ring: 1.25,
      vRing: 1,
      sparks: 38,
      debris: true,
      smoke: true,
      light: 1.1,
    },
  },
  mir4_skill_1104: {
    archetype: 'strike',
    palette: 'blood',
    tint: '#ff334f',
    accent: '#e9eef7',
    rim: '#ffb5c0',
    power: 1.32,
    strike: { swings: 1, arc: 'vertical', bleed: true, groundSlam: true },
    motifs: ['fissure'],
    motifAt: 'target',
    decal: 'crack',
    linger: 1,
    impact: {
      trail: 'overhead',
      sparks: 32,
      flipbook: true,
      ring: false,
      vRing: true,
      debris: true,
      blood: true,
      light: 0.95,
    },
  },
  mir4_skill_1501: {
    archetype: 'nova',
    palette: 'physical',
    tint: '#79dcff',
    accent: '#f3fbff',
    rim: '#c9f3ff',
    power: 1.48,
    motifs: ['bladestorm', 'crescents'],
    motifAt: 'caster',
    motifEvery: 0.2,
    nova: { radius: 7 },
    spin: { rate: 2.8, timeScale: 1.45 },
    linger: 2,
    impact: {
      trail: 'sweep',
      sparks: 48,
      flipbook: false,
      ring: 1.7,
      vRing: 0.8,
      light: 1.3,
    },
  },
  mir4_skill_1201: {
    archetype: 'cc',
    palette: 'physical',
    tint: '#8ba7c7',
    accent: '#dce8f5',
    rim: '#f0f6ff',
    power: 1.25,
    cc: { style: 'tendrils' },
    motifs: ['chains', 'implosion'],
    motifAt: 'target',
    motifR: 5,
    decal: 'rune',
    linger: 1.8,
    impact: {
      flipbook: false,
      ring: 1.35,
      vRing: 0.85,
      sparks: 28,
      debris: true,
      smoke: true,
      light: 0.85,
    },
  },
  mir4_skill_1601: {
    archetype: 'strike',
    palette: 'physical',
    tint: '#ffe08a',
    accent: '#f8fbff',
    rim: '#fff5cc',
    power: 1.38,
    strike: { swings: 1, arc: 'sweep' },
    motifs: ['crescents'],
    motifAt: 'target',
    motifR: 5,
    linger: 1.1,
    impact: {
      trail: 'sweep',
      sparks: 36,
      flipbook: false,
      ring: false,
      vRing: 1,
      light: 1,
    },
  },
  mir4_skill_1304: {
    archetype: 'dash',
    palette: 'physical',
    tint: '#d8894b',
    accent: '#f5d59a',
    rim: '#fff0c2',
    power: 1.18,
    motifs: ['implosion'],
    motifAt: 'target',
    linger: 0.8,
    impact: {
      trail: 'low',
      sparks: 28,
      flipbook: false,
      ring: 0.8,
      vRing: true,
      debris: true,
      light: 0.75,
    },
  },
  mir4_skill_1401: {
    archetype: 'strike',
    palette: 'physical',
    tint: '#d69a55',
    accent: '#ffcf7b',
    rim: '#ffe7bc',
    power: 1.45,
    strike: { swings: 1, arc: 'vertical', groundSlam: true },
    motifs: ['fissure', 'pillars'],
    motifAt: 'target',
    motifR: 6,
    nova: { radius: 6 },
    decal: 'crack',
    linger: 2.4,
    impact: {
      trail: 'overhead',
      sparks: 46,
      flipbook: true,
      ring: 1.65,
      vRing: 1.1,
      debris: true,
      smoke: true,
      light: 1.2,
    },
  },
  mir4_skill_1502: {
    archetype: 'buff',
    palette: 'physical',
    tint: '#ffd36a',
    accent: '#f5f8ff',
    rim: '#fff2b0',
    power: 1.15,
    windupStyle: 'stance',
    motifs: ['barrier', 'chains'],
    motifAt: 'caster',
    barrier: true,
    buff: { style: 'raise', orbit: 'plates', shellDur: 3, o: { n: 5, rate: 0.7 } },
    linger: 3,
    impact: {
      flipbook: false,
      ring: 1.2,
      vRing: 1,
      sparks: 20,
      debris: true,
      light: 1.1,
    },
  },
  mir4_ultimate_1: {
    archetype: 'nova',
    palette: 'blood',
    tint: '#ff6a21',
    accent: '#ffd42e',
    rim: '#fff0aa',
    hot: 0.1,
    power: 1.85,
    finisher: true,
    motifs: ['bladestorm', 'crescents', 'pillars', 'fissure'],
    motifAt: 'target',
    motifEvery: 0.35,
    motifR: 8,
    nova: { radius: 8 },
    spin: { rate: 3.1, timeScale: 1.35 },
    decal: 'scorch',
    screenFx: true,
    linger: 3.8,
    impact: {
      trail: 'sweep',
      sparks: 60,
      flipbook: true,
      ring: 2,
      vRing: 1.5,
      debris: true,
      smoke: true,
      light: 1.9,
      sample: 'imp_fire',
    },
  },
};

export const MIR4_WARRIOR_VFX_IDS = Object.freeze(Object.keys(FULL));

export function mir4WarriorVfxSpec(abilityId: string): AbilityVfxSpec | undefined {
  return COMPACT[abilityId];
}

export function mir4WarriorVfxFullSpec(abilityId: string): AbilityVfxFullSpec | undefined {
  return FULL[abilityId];
}
