// Generated from the source project server/data/
// authorial-equipment-catalog-v1.json (240 items = 8 slots x 5 classes x 6
// ranks). DO NOT HAND-EDIT VALUES. baseAttributes are [statusId, value]
// pairs exactly as shipped; the applied ids live in MIR4_APPLIED_STATUS_IDS
// (items.ts) and unapplied ids stay data-only until their consumer lands.
// Names are PT-BR source copy; the English i18n source lands with the HUD.

import type { Mir4ClassId } from './classes';

export interface Mir4EquipmentItemDef {
  itemId: number;
  key: string;
  name: string;
  classId: Mir4ClassId;
  /** Source equip slot 1..8 (1 weapon, 2-4 accessories, 5 armor, 6-8 protection). */
  equipSlot: number;
  catalogRank: number;
  requiredLevel: number;
  maxEnhancementLevel: number;
  enhanceable: boolean;
  enchantable: boolean;
  blessable: boolean;
  baseAttributes: readonly (readonly [number, number])[];
  balanceBudget: number;
}

export const MIR4_EQUIPMENT_CATALOG: readonly Mir4EquipmentItemDef[] = [
  {
    itemId: 991010101,
    key: 'aeq-s1-c1-r1',
    name: 'Espada Gasta',
    classId: 1,
    equipSlot: 1,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 18],
      [28, 2],
    ],
    balanceBudget: 186,
  },
  {
    itemId: 991010102,
    key: 'aeq-s1-c1-r2',
    name: 'Machado do Bastião',
    classId: 1,
    equipSlot: 1,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 30],
      [28, 3],
    ],
    balanceBudget: 309,
  },
  {
    itemId: 991010103,
    key: 'aeq-s1-c1-r3',
    name: 'Maça do Juramento',
    classId: 1,
    equipSlot: 1,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 50],
      [28, 5],
      [44, 3],
    ],
    balanceBudget: 533,
  },
  {
    itemId: 991010104,
    key: 'aeq-s1-c1-r4',
    name: 'Espadão Rubro',
    classId: 1,
    equipSlot: 1,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 78],
      [28, 8],
      [44, 5],
    ],
    balanceBudget: 834,
  },
  {
    itemId: 991010105,
    key: 'aeq-s1-c1-r5',
    name: 'Martelo do Colosso',
    classId: 1,
    equipSlot: 1,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 116],
      [28, 11],
      [44, 7],
    ],
    balanceBudget: 1235,
  },
  {
    itemId: 991010106,
    key: 'aeq-s1-c1-r6',
    name: 'Lâmina do Rei',
    classId: 1,
    equipSlot: 1,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 164],
      [28, 15],
      [44, 10],
    ],
    balanceBudget: 1745,
  },
  {
    itemId: 991010201,
    key: 'aeq-s1-c2-r1',
    name: 'Cajado de Cinza',
    classId: 2,
    equipSlot: 1,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 18],
      [28, 2],
    ],
    balanceBudget: 186,
  },
  {
    itemId: 991010202,
    key: 'aeq-s1-c2-r2',
    name: 'Vara Prismática',
    classId: 2,
    equipSlot: 1,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 30],
      [28, 3],
    ],
    balanceBudget: 309,
  },
  {
    itemId: 991010203,
    key: 'aeq-s1-c2-r3',
    name: 'Orbe das Brasas',
    classId: 2,
    equipSlot: 1,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 50],
      [28, 5],
      [44, 3],
    ],
    balanceBudget: 533,
  },
  {
    itemId: 991010204,
    key: 'aeq-s1-c2-r4',
    name: 'Grimório da Tormenta',
    classId: 2,
    equipSlot: 1,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 78],
      [28, 8],
      [44, 5],
    ],
    balanceBudget: 834,
  },
  {
    itemId: 991010205,
    key: 'aeq-s1-c2-r5',
    name: 'Pluma do Éter',
    classId: 2,
    equipSlot: 1,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 116],
      [28, 11],
      [44, 7],
    ],
    balanceBudget: 1235,
  },
  {
    itemId: 991010206,
    key: 'aeq-s1-c2-r6',
    name: 'Núcleo Astral',
    classId: 2,
    equipSlot: 1,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 164],
      [28, 15],
      [44, 10],
    ],
    balanceBudget: 1745,
  },
  {
    itemId: 991010301,
    key: 'aeq-s1-c3-r1',
    name: 'Adaga de Junco',
    classId: 3,
    equipSlot: 1,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 8],
      [22, 10],
      [28, 2],
    ],
    balanceBudget: 186,
  },
  {
    itemId: 991010302,
    key: 'aeq-s1-c3-r2',
    name: 'Chicote do Selo',
    classId: 3,
    equipSlot: 1,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 14],
      [22, 16],
      [28, 3],
    ],
    balanceBudget: 309,
  },
  {
    itemId: 991010303,
    key: 'aeq-s1-c3-r3',
    name: 'Bumerangue do Equilíbrio',
    classId: 3,
    equipSlot: 1,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 22],
      [22, 28],
      [28, 5],
      [44, 3],
    ],
    balanceBudget: 533,
  },
  {
    itemId: 991010304,
    key: 'aeq-s1-c3-r4',
    name: 'Lâmina dos Cinco Fluxos',
    classId: 3,
    equipSlot: 1,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 35],
      [22, 43],
      [28, 8],
      [44, 5],
    ],
    balanceBudget: 834,
  },
  {
    itemId: 991010305,
    key: 'aeq-s1-c3-r5',
    name: 'Espadas do Lótus',
    classId: 3,
    equipSlot: 1,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 52],
      [22, 64],
      [28, 11],
      [44, 7],
    ],
    balanceBudget: 1235,
  },
  {
    itemId: 991010306,
    key: 'aeq-s1-c3-r6',
    name: 'Pedra Celestial',
    classId: 3,
    equipSlot: 1,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 74],
      [22, 90],
      [28, 15],
      [44, 10],
    ],
    balanceBudget: 1745,
  },
  {
    itemId: 991010401,
    key: 'aeq-s1-c4-r1',
    name: 'Arco de Caça',
    classId: 4,
    equipSlot: 1,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 18],
      [28, 2],
    ],
    balanceBudget: 186,
  },
  {
    itemId: 991010402,
    key: 'aeq-s1-c4-r2',
    name: 'Besta da Vigília',
    classId: 4,
    equipSlot: 1,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 30],
      [28, 3],
    ],
    balanceBudget: 309,
  },
  {
    itemId: 991010403,
    key: 'aeq-s1-c4-r3',
    name: 'Flecha do Falcão',
    classId: 4,
    equipSlot: 1,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 50],
      [28, 5],
      [44, 3],
    ],
    balanceBudget: 533,
  },
  {
    itemId: 991010404,
    key: 'aeq-s1-c4-r4',
    name: 'Arco do Horizonte',
    classId: 4,
    equipSlot: 1,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 78],
      [28, 8],
      [44, 5],
    ],
    balanceBudget: 834,
  },
  {
    itemId: 991010405,
    key: 'aeq-s1-c4-r5',
    name: 'Arco da Estrela',
    classId: 4,
    equipSlot: 1,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 116],
      [28, 11],
      [44, 7],
    ],
    balanceBudget: 1235,
  },
  {
    itemId: 991010406,
    key: 'aeq-s1-c4-r6',
    name: 'Flecha da Lua',
    classId: 4,
    equipSlot: 1,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 164],
      [28, 15],
      [44, 10],
    ],
    balanceBudget: 1745,
  },
  {
    itemId: 991010501,
    key: 'aeq-s1-c5-r1',
    name: 'Lança de Ferro',
    classId: 5,
    equipSlot: 1,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 11],
      [22, 7],
      [28, 2],
    ],
    balanceBudget: 186,
  },
  {
    itemId: 991010502,
    key: 'aeq-s1-c5-r2',
    name: 'Alabarda da Guarda',
    classId: 5,
    equipSlot: 1,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 18],
      [22, 12],
      [28, 3],
    ],
    balanceBudget: 309,
  },
  {
    itemId: 991010503,
    key: 'aeq-s1-c5-r3',
    name: 'Lança da Vanguarda',
    classId: 5,
    equipSlot: 1,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 30],
      [22, 20],
      [28, 5],
      [44, 3],
    ],
    balanceBudget: 533,
  },
  {
    itemId: 991010504,
    key: 'aeq-s1-c5-r4',
    name: 'Pique do Dragão',
    classId: 5,
    equipSlot: 1,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 47],
      [22, 31],
      [28, 8],
      [44, 5],
    ],
    balanceBudget: 834,
  },
  {
    itemId: 991010505,
    key: 'aeq-s1-c5-r5',
    name: 'Machado do Firmamento',
    classId: 5,
    equipSlot: 1,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 70],
      [22, 46],
      [28, 11],
      [44, 7],
    ],
    balanceBudget: 1235,
  },
  {
    itemId: 991010506,
    key: 'aeq-s1-c5-r6',
    name: 'Alabarda Imperial',
    classId: 5,
    equipSlot: 1,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 98],
      [22, 66],
      [28, 15],
      [44, 10],
    ],
    balanceBudget: 1745,
  },
  {
    itemId: 991020101,
    key: 'aeq-s2-c1-r1',
    name: 'Pingente de Ferro',
    classId: 1,
    equipSlot: 2,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 5],
      [28, 1],
      [44, 1],
    ],
    balanceBudget: 60,
  },
  {
    itemId: 991020102,
    key: 'aeq-s2-c1-r2',
    name: 'Colar Rubro',
    classId: 1,
    equipSlot: 2,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 8],
      [28, 2],
      [44, 2],
    ],
    balanceBudget: 102,
  },
  {
    itemId: 991020103,
    key: 'aeq-s2-c1-r3',
    name: 'Medalhão do Baluarte',
    classId: 1,
    equipSlot: 2,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 14],
      [28, 3],
      [44, 3],
    ],
    balanceBudget: 168,
  },
  {
    itemId: 991020104,
    key: 'aeq-s2-c1-r4',
    name: 'Relicário Leonino',
    classId: 1,
    equipSlot: 2,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 22],
      [28, 4],
      [44, 5],
    ],
    balanceBudget: 264,
  },
  {
    itemId: 991020105,
    key: 'aeq-s2-c1-r5',
    name: 'Amuleto do Colosso',
    classId: 1,
    equipSlot: 2,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 32],
      [28, 6],
      [44, 7],
    ],
    balanceBudget: 389,
  },
  {
    itemId: 991020106,
    key: 'aeq-s2-c1-r6',
    name: 'Insígnia do Rei',
    classId: 1,
    equipSlot: 2,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 46],
      [28, 8],
      [44, 10],
    ],
    balanceBudget: 549,
  },
  {
    itemId: 991020201,
    key: 'aeq-s2-c2-r1',
    name: 'Pingente de Cinza',
    classId: 2,
    equipSlot: 2,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 5],
      [28, 1],
      [44, 1],
    ],
    balanceBudget: 60,
  },
  {
    itemId: 991020202,
    key: 'aeq-s2-c2-r2',
    name: 'Colar das Brasas',
    classId: 2,
    equipSlot: 2,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 8],
      [28, 2],
      [44, 2],
    ],
    balanceBudget: 102,
  },
  {
    itemId: 991020203,
    key: 'aeq-s2-c2-r3',
    name: 'Medalhão do Prisma',
    classId: 2,
    equipSlot: 2,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 14],
      [28, 3],
      [44, 3],
    ],
    balanceBudget: 168,
  },
  {
    itemId: 991020204,
    key: 'aeq-s2-c2-r4',
    name: 'Relicário da Tormenta',
    classId: 2,
    equipSlot: 2,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 22],
      [28, 4],
      [44, 5],
    ],
    balanceBudget: 264,
  },
  {
    itemId: 991020205,
    key: 'aeq-s2-c2-r5',
    name: 'Amuleto do Éter',
    classId: 2,
    equipSlot: 2,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 32],
      [28, 6],
      [44, 7],
    ],
    balanceBudget: 389,
  },
  {
    itemId: 991020206,
    key: 'aeq-s2-c2-r6',
    name: 'Insígnia Astral',
    classId: 2,
    equipSlot: 2,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 46],
      [28, 8],
      [44, 10],
    ],
    balanceBudget: 549,
  },
  {
    itemId: 991020301,
    key: 'aeq-s2-c3-r1',
    name: 'Pingente de Junco',
    classId: 3,
    equipSlot: 2,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 2],
      [22, 3],
      [28, 1],
      [44, 1],
    ],
    balanceBudget: 60,
  },
  {
    itemId: 991020302,
    key: 'aeq-s2-c3-r2',
    name: 'Colar do Selo',
    classId: 3,
    equipSlot: 2,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 4],
      [22, 5],
      [28, 2],
      [44, 2],
    ],
    balanceBudget: 102,
  },
  {
    itemId: 991020303,
    key: 'aeq-s2-c3-r3',
    name: 'Medalhão do Equilíbrio',
    classId: 3,
    equipSlot: 2,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 6],
      [22, 8],
      [28, 3],
      [44, 3],
    ],
    balanceBudget: 168,
  },
  {
    itemId: 991020304,
    key: 'aeq-s2-c3-r4',
    name: 'Relicário dos Cinco Fluxos',
    classId: 3,
    equipSlot: 2,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 10],
      [22, 12],
      [28, 4],
      [44, 5],
    ],
    balanceBudget: 264,
  },
  {
    itemId: 991020305,
    key: 'aeq-s2-c3-r5',
    name: 'Amuleto do Lótus',
    classId: 3,
    equipSlot: 2,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 15],
      [22, 18],
      [28, 6],
      [44, 7],
    ],
    balanceBudget: 389,
  },
  {
    itemId: 991020306,
    key: 'aeq-s2-c3-r6',
    name: 'Insígnia Celestial',
    classId: 3,
    equipSlot: 2,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 21],
      [22, 25],
      [28, 8],
      [44, 10],
    ],
    balanceBudget: 549,
  },
  {
    itemId: 991020401,
    key: 'aeq-s2-c4-r1',
    name: 'Pingente de Caça',
    classId: 4,
    equipSlot: 2,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 5],
      [28, 1],
      [44, 1],
    ],
    balanceBudget: 60,
  },
  {
    itemId: 991020402,
    key: 'aeq-s2-c4-r2',
    name: 'Colar da Vigília',
    classId: 4,
    equipSlot: 2,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 8],
      [28, 2],
      [44, 2],
    ],
    balanceBudget: 102,
  },
  {
    itemId: 991020403,
    key: 'aeq-s2-c4-r3',
    name: 'Medalhão do Falcão',
    classId: 4,
    equipSlot: 2,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 14],
      [28, 3],
      [44, 3],
    ],
    balanceBudget: 168,
  },
  {
    itemId: 991020404,
    key: 'aeq-s2-c4-r4',
    name: 'Relicário do Horizonte',
    classId: 4,
    equipSlot: 2,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 22],
      [28, 4],
      [44, 5],
    ],
    balanceBudget: 264,
  },
  {
    itemId: 991020405,
    key: 'aeq-s2-c4-r5',
    name: 'Amuleto da Estrela',
    classId: 4,
    equipSlot: 2,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 32],
      [28, 6],
      [44, 7],
    ],
    balanceBudget: 389,
  },
  {
    itemId: 991020406,
    key: 'aeq-s2-c4-r6',
    name: 'Insígnia da Lua',
    classId: 4,
    equipSlot: 2,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 46],
      [28, 8],
      [44, 10],
    ],
    balanceBudget: 549,
  },
  {
    itemId: 991020501,
    key: 'aeq-s2-c5-r1',
    name: 'Pingente de Ferro',
    classId: 5,
    equipSlot: 2,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 3],
      [22, 2],
      [28, 1],
      [44, 1],
    ],
    balanceBudget: 60,
  },
  {
    itemId: 991020502,
    key: 'aeq-s2-c5-r2',
    name: 'Colar da Guarda',
    classId: 5,
    equipSlot: 2,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 5],
      [22, 3],
      [28, 2],
      [44, 2],
    ],
    balanceBudget: 102,
  },
  {
    itemId: 991020503,
    key: 'aeq-s2-c5-r3',
    name: 'Medalhão da Vanguarda',
    classId: 5,
    equipSlot: 2,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 8],
      [22, 6],
      [28, 3],
      [44, 3],
    ],
    balanceBudget: 168,
  },
  {
    itemId: 991020504,
    key: 'aeq-s2-c5-r4',
    name: 'Relicário do Dragão',
    classId: 5,
    equipSlot: 2,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 13],
      [22, 9],
      [28, 4],
      [44, 5],
    ],
    balanceBudget: 264,
  },
  {
    itemId: 991020505,
    key: 'aeq-s2-c5-r5',
    name: 'Amuleto do Firmamento',
    classId: 5,
    equipSlot: 2,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 19],
      [22, 13],
      [28, 6],
      [44, 7],
    ],
    balanceBudget: 389,
  },
  {
    itemId: 991020506,
    key: 'aeq-s2-c5-r6',
    name: 'Insígnia Imperial',
    classId: 5,
    equipSlot: 2,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 28],
      [22, 18],
      [28, 8],
      [44, 10],
    ],
    balanceBudget: 549,
  },
  {
    itemId: 991030101,
    key: 'aeq-s3-c1-r1',
    name: 'Anel de Ferro',
    classId: 1,
    equipSlot: 3,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 4],
      [30, 1],
      [28, 1],
    ],
    balanceBudget: 47,
  },
  {
    itemId: 991030102,
    key: 'aeq-s3-c1-r2',
    name: 'Sinete Rubro',
    classId: 1,
    equipSlot: 3,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 6],
      [30, 2],
      [28, 1],
    ],
    balanceBudget: 81,
  },
  {
    itemId: 991030103,
    key: 'aeq-s3-c1-r3',
    name: 'Aliança do Baluarte',
    classId: 1,
    equipSlot: 3,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 10],
      [30, 3],
      [28, 2],
    ],
    balanceBudget: 132,
  },
  {
    itemId: 991030104,
    key: 'aeq-s3-c1-r4',
    name: 'Aro Leonino',
    classId: 1,
    equipSlot: 3,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 16],
      [30, 4],
      [28, 3],
    ],
    balanceBudget: 200,
  },
  {
    itemId: 991030105,
    key: 'aeq-s3-c1-r5',
    name: 'Selo do Colosso',
    classId: 1,
    equipSlot: 3,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 23],
      [30, 6],
      [28, 4],
    ],
    balanceBudget: 297,
  },
  {
    itemId: 991030106,
    key: 'aeq-s3-c1-r6',
    name: 'Círculo do Rei',
    classId: 1,
    equipSlot: 3,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 33],
      [30, 8],
      [28, 5],
    ],
    balanceBudget: 415,
  },
  {
    itemId: 991030201,
    key: 'aeq-s3-c2-r1',
    name: 'Anel de Cinza',
    classId: 2,
    equipSlot: 3,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 4],
      [30, 1],
      [28, 1],
    ],
    balanceBudget: 47,
  },
  {
    itemId: 991030202,
    key: 'aeq-s3-c2-r2',
    name: 'Sinete das Brasas',
    classId: 2,
    equipSlot: 3,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 6],
      [30, 2],
      [28, 1],
    ],
    balanceBudget: 81,
  },
  {
    itemId: 991030203,
    key: 'aeq-s3-c2-r3',
    name: 'Aliança do Prisma',
    classId: 2,
    equipSlot: 3,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 10],
      [30, 3],
      [28, 2],
    ],
    balanceBudget: 132,
  },
  {
    itemId: 991030204,
    key: 'aeq-s3-c2-r4',
    name: 'Aro da Tormenta',
    classId: 2,
    equipSlot: 3,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 16],
      [30, 4],
      [28, 3],
    ],
    balanceBudget: 200,
  },
  {
    itemId: 991030205,
    key: 'aeq-s3-c2-r5',
    name: 'Selo do Éter',
    classId: 2,
    equipSlot: 3,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 23],
      [30, 6],
      [28, 4],
    ],
    balanceBudget: 297,
  },
  {
    itemId: 991030206,
    key: 'aeq-s3-c2-r6',
    name: 'Círculo Astral',
    classId: 2,
    equipSlot: 3,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [22, 33],
      [30, 8],
      [28, 5],
    ],
    balanceBudget: 415,
  },
  {
    itemId: 991030301,
    key: 'aeq-s3-c3-r1',
    name: 'Anel de Junco',
    classId: 3,
    equipSlot: 3,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 2],
      [22, 2],
      [30, 1],
      [28, 1],
    ],
    balanceBudget: 47,
  },
  {
    itemId: 991030302,
    key: 'aeq-s3-c3-r2',
    name: 'Sinete do Selo',
    classId: 3,
    equipSlot: 3,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 3],
      [22, 3],
      [30, 2],
      [28, 1],
    ],
    balanceBudget: 81,
  },
  {
    itemId: 991030303,
    key: 'aeq-s3-c3-r3',
    name: 'Aliança do Equilíbrio',
    classId: 3,
    equipSlot: 3,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 4],
      [22, 6],
      [30, 3],
      [28, 2],
    ],
    balanceBudget: 132,
  },
  {
    itemId: 991030304,
    key: 'aeq-s3-c3-r4',
    name: 'Aro dos Cinco Fluxos',
    classId: 3,
    equipSlot: 3,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 7],
      [22, 9],
      [30, 4],
      [28, 3],
    ],
    balanceBudget: 200,
  },
  {
    itemId: 991030305,
    key: 'aeq-s3-c3-r5',
    name: 'Selo do Lótus',
    classId: 3,
    equipSlot: 3,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 10],
      [22, 13],
      [30, 6],
      [28, 4],
    ],
    balanceBudget: 297,
  },
  {
    itemId: 991030306,
    key: 'aeq-s3-c3-r6',
    name: 'Círculo Celestial',
    classId: 3,
    equipSlot: 3,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 15],
      [22, 18],
      [30, 8],
      [28, 5],
    ],
    balanceBudget: 415,
  },
  {
    itemId: 991030401,
    key: 'aeq-s3-c4-r1',
    name: 'Anel de Caça',
    classId: 4,
    equipSlot: 3,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 4],
      [30, 1],
      [28, 1],
    ],
    balanceBudget: 47,
  },
  {
    itemId: 991030402,
    key: 'aeq-s3-c4-r2',
    name: 'Sinete da Vigília',
    classId: 4,
    equipSlot: 3,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 6],
      [30, 2],
      [28, 1],
    ],
    balanceBudget: 81,
  },
  {
    itemId: 991030403,
    key: 'aeq-s3-c4-r3',
    name: 'Aliança do Falcão',
    classId: 4,
    equipSlot: 3,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 10],
      [30, 3],
      [28, 2],
    ],
    balanceBudget: 132,
  },
  {
    itemId: 991030404,
    key: 'aeq-s3-c4-r4',
    name: 'Aro do Horizonte',
    classId: 4,
    equipSlot: 3,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 16],
      [30, 4],
      [28, 3],
    ],
    balanceBudget: 200,
  },
  {
    itemId: 991030405,
    key: 'aeq-s3-c4-r5',
    name: 'Selo da Estrela',
    classId: 4,
    equipSlot: 3,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 23],
      [30, 6],
      [28, 4],
    ],
    balanceBudget: 297,
  },
  {
    itemId: 991030406,
    key: 'aeq-s3-c4-r6',
    name: 'Círculo da Lua',
    classId: 4,
    equipSlot: 3,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 33],
      [30, 8],
      [28, 5],
    ],
    balanceBudget: 415,
  },
  {
    itemId: 991030501,
    key: 'aeq-s3-c5-r1',
    name: 'Anel de Ferro',
    classId: 5,
    equipSlot: 3,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 2],
      [22, 1],
      [30, 1],
      [28, 1],
    ],
    balanceBudget: 47,
  },
  {
    itemId: 991030502,
    key: 'aeq-s3-c5-r2',
    name: 'Sinete da Guarda',
    classId: 5,
    equipSlot: 3,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 4],
      [22, 2],
      [30, 2],
      [28, 1],
    ],
    balanceBudget: 81,
  },
  {
    itemId: 991030503,
    key: 'aeq-s3-c5-r3',
    name: 'Aliança da Vanguarda',
    classId: 5,
    equipSlot: 3,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 6],
      [22, 4],
      [30, 3],
      [28, 2],
    ],
    balanceBudget: 132,
  },
  {
    itemId: 991030504,
    key: 'aeq-s3-c5-r4',
    name: 'Aro do Dragão',
    classId: 5,
    equipSlot: 3,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 9],
      [22, 6],
      [30, 4],
      [28, 3],
    ],
    balanceBudget: 200,
  },
  {
    itemId: 991030505,
    key: 'aeq-s3-c5-r5',
    name: 'Selo do Firmamento',
    classId: 5,
    equipSlot: 3,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 14],
      [22, 9],
      [30, 6],
      [28, 4],
    ],
    balanceBudget: 297,
  },
  {
    itemId: 991030506,
    key: 'aeq-s3-c5-r6',
    name: 'Círculo Imperial',
    classId: 5,
    equipSlot: 3,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [20, 20],
      [22, 13],
      [30, 8],
      [28, 5],
    ],
    balanceBudget: 415,
  },
  {
    itemId: 991040101,
    key: 'aeq-s4-c1-r1',
    name: 'Talismã de Ferro',
    classId: 1,
    equipSlot: 4,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 5],
      [26, 4],
      [31, 1],
      [29, 1],
    ],
    balanceBudget: 44,
  },
  {
    itemId: 991040102,
    key: 'aeq-s4-c1-r2',
    name: 'Ídolo Rubro',
    classId: 1,
    equipSlot: 4,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 8],
      [26, 6],
      [31, 2],
      [29, 1],
    ],
    balanceBudget: 71,
  },
  {
    itemId: 991040103,
    key: 'aeq-s4-c1-r3',
    name: 'Emblema do Baluarte',
    classId: 1,
    equipSlot: 4,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 14],
      [26, 10],
      [31, 2],
      [29, 2],
    ],
    balanceBudget: 119,
  },
  {
    itemId: 991040104,
    key: 'aeq-s4-c1-r4',
    name: 'Runa Leonino',
    classId: 1,
    equipSlot: 4,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 21],
      [26, 16],
      [31, 3],
      [29, 3],
    ],
    balanceBudget: 180,
  },
  {
    itemId: 991040105,
    key: 'aeq-s4-c1-r5',
    name: 'Totem do Colosso',
    classId: 1,
    equipSlot: 4,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 31],
      [26, 24],
      [31, 4],
      [29, 4],
    ],
    balanceBudget: 267,
  },
  {
    itemId: 991040106,
    key: 'aeq-s4-c1-r6',
    name: 'Símbolo do Rei',
    classId: 1,
    equipSlot: 4,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 45],
      [26, 34],
      [31, 6],
      [29, 5],
    ],
    balanceBudget: 379,
  },
  {
    itemId: 991040201,
    key: 'aeq-s4-c2-r1',
    name: 'Talismã de Cinza',
    classId: 2,
    equipSlot: 4,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 4],
      [26, 5],
      [31, 1],
      [29, 1],
    ],
    balanceBudget: 44,
  },
  {
    itemId: 991040202,
    key: 'aeq-s4-c2-r2',
    name: 'Ídolo das Brasas',
    classId: 2,
    equipSlot: 4,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 6],
      [26, 8],
      [31, 2],
      [29, 1],
    ],
    balanceBudget: 71,
  },
  {
    itemId: 991040203,
    key: 'aeq-s4-c2-r3',
    name: 'Emblema do Prisma',
    classId: 2,
    equipSlot: 4,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 10],
      [26, 14],
      [31, 2],
      [29, 2],
    ],
    balanceBudget: 119,
  },
  {
    itemId: 991040204,
    key: 'aeq-s4-c2-r4',
    name: 'Runa da Tormenta',
    classId: 2,
    equipSlot: 4,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 16],
      [26, 21],
      [31, 3],
      [29, 3],
    ],
    balanceBudget: 180,
  },
  {
    itemId: 991040205,
    key: 'aeq-s4-c2-r5',
    name: 'Totem do Éter',
    classId: 2,
    equipSlot: 4,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 24],
      [26, 31],
      [31, 4],
      [29, 4],
    ],
    balanceBudget: 267,
  },
  {
    itemId: 991040206,
    key: 'aeq-s4-c2-r6',
    name: 'Símbolo Astral',
    classId: 2,
    equipSlot: 4,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 34],
      [26, 45],
      [31, 6],
      [29, 5],
    ],
    balanceBudget: 379,
  },
  {
    itemId: 991040301,
    key: 'aeq-s4-c3-r1',
    name: 'Talismã de Junco',
    classId: 3,
    equipSlot: 4,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 4],
      [26, 4],
      [31, 1],
      [29, 1],
    ],
    balanceBudget: 40,
  },
  {
    itemId: 991040302,
    key: 'aeq-s4-c3-r2',
    name: 'Ídolo do Selo',
    classId: 3,
    equipSlot: 4,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 7],
      [26, 7],
      [31, 2],
      [29, 1],
    ],
    balanceBudget: 71,
  },
  {
    itemId: 991040303,
    key: 'aeq-s4-c3-r3',
    name: 'Emblema do Equilíbrio',
    classId: 3,
    equipSlot: 4,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 12],
      [26, 12],
      [31, 2],
      [29, 2],
    ],
    balanceBudget: 119,
  },
  {
    itemId: 991040304,
    key: 'aeq-s4-c3-r4',
    name: 'Runa dos Cinco Fluxos',
    classId: 3,
    equipSlot: 4,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 19],
      [26, 19],
      [31, 3],
      [29, 3],
    ],
    balanceBudget: 184,
  },
  {
    itemId: 991040305,
    key: 'aeq-s4-c3-r5',
    name: 'Totem do Lótus',
    classId: 3,
    equipSlot: 4,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 28],
      [26, 28],
      [31, 4],
      [29, 4],
    ],
    balanceBudget: 271,
  },
  {
    itemId: 991040306,
    key: 'aeq-s4-c3-r6',
    name: 'Símbolo Celestial',
    classId: 3,
    equipSlot: 4,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 40],
      [26, 40],
      [31, 6],
      [29, 5],
    ],
    balanceBudget: 383,
  },
  {
    itemId: 991040401,
    key: 'aeq-s4-c4-r1',
    name: 'Talismã de Caça',
    classId: 4,
    equipSlot: 4,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 5],
      [26, 4],
      [31, 1],
      [29, 1],
    ],
    balanceBudget: 44,
  },
  {
    itemId: 991040402,
    key: 'aeq-s4-c4-r2',
    name: 'Ídolo da Vigília',
    classId: 4,
    equipSlot: 4,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 8],
      [26, 6],
      [31, 2],
      [29, 1],
    ],
    balanceBudget: 71,
  },
  {
    itemId: 991040403,
    key: 'aeq-s4-c4-r3',
    name: 'Emblema do Falcão',
    classId: 4,
    equipSlot: 4,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 14],
      [26, 10],
      [31, 2],
      [29, 2],
    ],
    balanceBudget: 119,
  },
  {
    itemId: 991040404,
    key: 'aeq-s4-c4-r4',
    name: 'Runa do Horizonte',
    classId: 4,
    equipSlot: 4,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 21],
      [26, 16],
      [31, 3],
      [29, 3],
    ],
    balanceBudget: 180,
  },
  {
    itemId: 991040405,
    key: 'aeq-s4-c4-r5',
    name: 'Totem da Estrela',
    classId: 4,
    equipSlot: 4,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 31],
      [26, 24],
      [31, 4],
      [29, 4],
    ],
    balanceBudget: 267,
  },
  {
    itemId: 991040406,
    key: 'aeq-s4-c4-r6',
    name: 'Símbolo da Lua',
    classId: 4,
    equipSlot: 4,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 45],
      [26, 34],
      [31, 6],
      [29, 5],
    ],
    balanceBudget: 379,
  },
  {
    itemId: 991040501,
    key: 'aeq-s4-c5-r1',
    name: 'Talismã de Ferro',
    classId: 5,
    equipSlot: 4,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 4],
      [26, 4],
      [31, 1],
      [29, 1],
    ],
    balanceBudget: 40,
  },
  {
    itemId: 991040502,
    key: 'aeq-s4-c5-r2',
    name: 'Ídolo da Guarda',
    classId: 5,
    equipSlot: 4,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 7],
      [26, 7],
      [31, 2],
      [29, 1],
    ],
    balanceBudget: 71,
  },
  {
    itemId: 991040503,
    key: 'aeq-s4-c5-r3',
    name: 'Emblema da Vanguarda',
    classId: 5,
    equipSlot: 4,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 12],
      [26, 12],
      [31, 2],
      [29, 2],
    ],
    balanceBudget: 119,
  },
  {
    itemId: 991040504,
    key: 'aeq-s4-c5-r4',
    name: 'Runa do Dragão',
    classId: 5,
    equipSlot: 4,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 19],
      [26, 19],
      [31, 3],
      [29, 3],
    ],
    balanceBudget: 184,
  },
  {
    itemId: 991040505,
    key: 'aeq-s4-c5-r5',
    name: 'Totem do Firmamento',
    classId: 5,
    equipSlot: 4,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 28],
      [26, 28],
      [31, 4],
      [29, 4],
    ],
    balanceBudget: 271,
  },
  {
    itemId: 991040506,
    key: 'aeq-s4-c5-r6',
    name: 'Símbolo Imperial',
    classId: 5,
    equipSlot: 4,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 40],
      [26, 40],
      [31, 6],
      [29, 5],
    ],
    balanceBudget: 383,
  },
  {
    itemId: 991050101,
    key: 'aeq-s5-c1-r1',
    name: 'Armadura de Ferro',
    classId: 1,
    equipSlot: 5,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 14],
      [26, 11],
      [31, 1],
    ],
    balanceBudget: 105,
  },
  {
    itemId: 991050102,
    key: 'aeq-s5-c1-r2',
    name: 'Couraça Rubro',
    classId: 1,
    equipSlot: 5,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 24],
      [26, 18],
      [31, 1],
    ],
    balanceBudget: 178,
  },
  {
    itemId: 991050103,
    key: 'aeq-s5-c1-r3',
    name: 'Veste do Baluarte',
    classId: 1,
    equipSlot: 5,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 40],
      [26, 30],
      [31, 2],
    ],
    balanceBudget: 295,
  },
  {
    itemId: 991050104,
    key: 'aeq-s5-c1-r4',
    name: 'Cota Leonino',
    classId: 1,
    equipSlot: 5,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 62],
      [26, 47],
      [31, 2],
    ],
    balanceBudget: 456,
  },
  {
    itemId: 991050105,
    key: 'aeq-s5-c1-r5',
    name: 'Manto do Colosso',
    classId: 1,
    equipSlot: 5,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 92],
      [26, 70],
      [31, 4],
    ],
    balanceBudget: 678,
  },
  {
    itemId: 991050106,
    key: 'aeq-s5-c1-r6',
    name: 'Égide do Rei',
    classId: 1,
    equipSlot: 5,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 132],
      [26, 100],
      [31, 5],
    ],
    balanceBudget: 968,
  },
  {
    itemId: 991050201,
    key: 'aeq-s5-c2-r1',
    name: 'Armadura de Cinza',
    classId: 2,
    equipSlot: 5,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 11],
      [26, 14],
      [31, 1],
    ],
    balanceBudget: 105,
  },
  {
    itemId: 991050202,
    key: 'aeq-s5-c2-r2',
    name: 'Couraça das Brasas',
    classId: 2,
    equipSlot: 5,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 18],
      [26, 24],
      [31, 1],
    ],
    balanceBudget: 178,
  },
  {
    itemId: 991050203,
    key: 'aeq-s5-c2-r3',
    name: 'Veste do Prisma',
    classId: 2,
    equipSlot: 5,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 30],
      [26, 40],
      [31, 2],
    ],
    balanceBudget: 295,
  },
  {
    itemId: 991050204,
    key: 'aeq-s5-c2-r4',
    name: 'Cota da Tormenta',
    classId: 2,
    equipSlot: 5,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 47],
      [26, 62],
      [31, 2],
    ],
    balanceBudget: 456,
  },
  {
    itemId: 991050205,
    key: 'aeq-s5-c2-r5',
    name: 'Manto do Éter',
    classId: 2,
    equipSlot: 5,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 70],
      [26, 92],
      [31, 4],
    ],
    balanceBudget: 678,
  },
  {
    itemId: 991050206,
    key: 'aeq-s5-c2-r6',
    name: 'Égide Astral',
    classId: 2,
    equipSlot: 5,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 100],
      [26, 132],
      [31, 5],
    ],
    balanceBudget: 968,
  },
  {
    itemId: 991050301,
    key: 'aeq-s5-c3-r1',
    name: 'Armadura de Junco',
    classId: 3,
    equipSlot: 5,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 13],
      [26, 13],
      [31, 1],
    ],
    balanceBudget: 109,
  },
  {
    itemId: 991050302,
    key: 'aeq-s5-c3-r2',
    name: 'Couraça do Selo',
    classId: 3,
    equipSlot: 5,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 22],
      [26, 22],
      [31, 1],
    ],
    balanceBudget: 186,
  },
  {
    itemId: 991050303,
    key: 'aeq-s5-c3-r3',
    name: 'Veste do Equilíbrio',
    classId: 3,
    equipSlot: 5,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 36],
      [26, 36],
      [31, 2],
    ],
    balanceBudget: 303,
  },
  {
    itemId: 991050304,
    key: 'aeq-s5-c3-r4',
    name: 'Cota dos Cinco Fluxos',
    classId: 3,
    equipSlot: 5,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 56],
      [26, 56],
      [31, 2],
    ],
    balanceBudget: 468,
  },
  {
    itemId: 991050305,
    key: 'aeq-s5-c3-r5',
    name: 'Manto do Lótus',
    classId: 3,
    equipSlot: 5,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 83],
      [26, 83],
      [31, 4],
    ],
    balanceBudget: 694,
  },
  {
    itemId: 991050306,
    key: 'aeq-s5-c3-r6',
    name: 'Égide Celestial',
    classId: 3,
    equipSlot: 5,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 119],
      [26, 119],
      [31, 5],
    ],
    balanceBudget: 992,
  },
  {
    itemId: 991050401,
    key: 'aeq-s5-c4-r1',
    name: 'Armadura de Caça',
    classId: 4,
    equipSlot: 5,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 14],
      [26, 11],
      [31, 1],
    ],
    balanceBudget: 105,
  },
  {
    itemId: 991050402,
    key: 'aeq-s5-c4-r2',
    name: 'Couraça da Vigília',
    classId: 4,
    equipSlot: 5,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 24],
      [26, 18],
      [31, 1],
    ],
    balanceBudget: 178,
  },
  {
    itemId: 991050403,
    key: 'aeq-s5-c4-r3',
    name: 'Veste do Falcão',
    classId: 4,
    equipSlot: 5,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 40],
      [26, 30],
      [31, 2],
    ],
    balanceBudget: 295,
  },
  {
    itemId: 991050404,
    key: 'aeq-s5-c4-r4',
    name: 'Cota do Horizonte',
    classId: 4,
    equipSlot: 5,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 62],
      [26, 47],
      [31, 2],
    ],
    balanceBudget: 456,
  },
  {
    itemId: 991050405,
    key: 'aeq-s5-c4-r5',
    name: 'Manto da Estrela',
    classId: 4,
    equipSlot: 5,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 92],
      [26, 70],
      [31, 4],
    ],
    balanceBudget: 678,
  },
  {
    itemId: 991050406,
    key: 'aeq-s5-c4-r6',
    name: 'Égide da Lua',
    classId: 4,
    equipSlot: 5,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 132],
      [26, 100],
      [31, 5],
    ],
    balanceBudget: 968,
  },
  {
    itemId: 991050501,
    key: 'aeq-s5-c5-r1',
    name: 'Armadura de Ferro',
    classId: 5,
    equipSlot: 5,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 13],
      [26, 13],
      [31, 1],
    ],
    balanceBudget: 109,
  },
  {
    itemId: 991050502,
    key: 'aeq-s5-c5-r2',
    name: 'Couraça da Guarda',
    classId: 5,
    equipSlot: 5,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 22],
      [26, 22],
      [31, 1],
    ],
    balanceBudget: 186,
  },
  {
    itemId: 991050503,
    key: 'aeq-s5-c5-r3',
    name: 'Veste da Vanguarda',
    classId: 5,
    equipSlot: 5,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 36],
      [26, 36],
      [31, 2],
    ],
    balanceBudget: 303,
  },
  {
    itemId: 991050504,
    key: 'aeq-s5-c5-r4',
    name: 'Cota do Dragão',
    classId: 5,
    equipSlot: 5,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 56],
      [26, 56],
      [31, 2],
    ],
    balanceBudget: 468,
  },
  {
    itemId: 991050505,
    key: 'aeq-s5-c5-r5',
    name: 'Manto do Firmamento',
    classId: 5,
    equipSlot: 5,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 83],
      [26, 83],
      [31, 4],
    ],
    balanceBudget: 694,
  },
  {
    itemId: 991050506,
    key: 'aeq-s5-c5-r6',
    name: 'Égide Imperial',
    classId: 5,
    equipSlot: 5,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 119],
      [26, 119],
      [31, 5],
    ],
    balanceBudget: 992,
  },
  {
    itemId: 991060101,
    key: 'aeq-s6-c1-r1',
    name: 'Elmo de Ferro',
    classId: 1,
    equipSlot: 6,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 9],
      [26, 7],
      [31, 1],
      [28, 1],
    ],
    balanceBudget: 72,
  },
  {
    itemId: 991060102,
    key: 'aeq-s6-c1-r2',
    name: 'Capuz Rubro',
    classId: 1,
    equipSlot: 6,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 15],
      [26, 11],
      [31, 2],
      [28, 1],
    ],
    balanceBudget: 119,
  },
  {
    itemId: 991060103,
    key: 'aeq-s6-c1-r3',
    name: 'Diadema do Baluarte',
    classId: 1,
    equipSlot: 6,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 25],
      [26, 19],
      [31, 2],
      [28, 2],
    ],
    balanceBudget: 199,
  },
  {
    itemId: 991060104,
    key: 'aeq-s6-c1-r4',
    name: 'Coroa Leonino',
    classId: 1,
    equipSlot: 6,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 38],
      [26, 29],
      [31, 3],
      [28, 2],
    ],
    balanceBudget: 300,
  },
  {
    itemId: 991060105,
    key: 'aeq-s6-c1-r5',
    name: 'Máscara do Colosso',
    classId: 1,
    equipSlot: 6,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 57],
      [26, 43],
      [31, 5],
      [28, 3],
    ],
    balanceBudget: 447,
  },
  {
    itemId: 991060106,
    key: 'aeq-s6-c1-r6',
    name: 'Auréola do Rei',
    classId: 1,
    equipSlot: 6,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 82],
      [26, 62],
      [31, 6],
      [28, 4],
    ],
    balanceBudget: 639,
  },
  {
    itemId: 991060201,
    key: 'aeq-s6-c2-r1',
    name: 'Elmo de Cinza',
    classId: 2,
    equipSlot: 6,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 7],
      [26, 9],
      [31, 1],
      [28, 1],
    ],
    balanceBudget: 72,
  },
  {
    itemId: 991060202,
    key: 'aeq-s6-c2-r2',
    name: 'Capuz das Brasas',
    classId: 2,
    equipSlot: 6,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 11],
      [26, 15],
      [31, 2],
      [28, 1],
    ],
    balanceBudget: 119,
  },
  {
    itemId: 991060203,
    key: 'aeq-s6-c2-r3',
    name: 'Diadema do Prisma',
    classId: 2,
    equipSlot: 6,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 19],
      [26, 25],
      [31, 2],
      [28, 2],
    ],
    balanceBudget: 199,
  },
  {
    itemId: 991060204,
    key: 'aeq-s6-c2-r4',
    name: 'Coroa da Tormenta',
    classId: 2,
    equipSlot: 6,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 29],
      [26, 38],
      [31, 3],
      [28, 2],
    ],
    balanceBudget: 300,
  },
  {
    itemId: 991060205,
    key: 'aeq-s6-c2-r5',
    name: 'Máscara do Éter',
    classId: 2,
    equipSlot: 6,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 43],
      [26, 57],
      [31, 5],
      [28, 3],
    ],
    balanceBudget: 447,
  },
  {
    itemId: 991060206,
    key: 'aeq-s6-c2-r6',
    name: 'Auréola Astral',
    classId: 2,
    equipSlot: 6,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 62],
      [26, 82],
      [31, 6],
      [28, 4],
    ],
    balanceBudget: 639,
  },
  {
    itemId: 991060301,
    key: 'aeq-s6-c3-r1',
    name: 'Elmo de Junco',
    classId: 3,
    equipSlot: 6,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 8],
      [26, 8],
      [31, 1],
      [28, 1],
    ],
    balanceBudget: 72,
  },
  {
    itemId: 991060302,
    key: 'aeq-s6-c3-r2',
    name: 'Capuz do Selo',
    classId: 3,
    equipSlot: 6,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 13],
      [26, 13],
      [31, 2],
      [28, 1],
    ],
    balanceBudget: 119,
  },
  {
    itemId: 991060303,
    key: 'aeq-s6-c3-r3',
    name: 'Diadema do Equilíbrio',
    classId: 3,
    equipSlot: 6,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 22],
      [26, 22],
      [31, 2],
      [28, 2],
    ],
    balanceBudget: 199,
  },
  {
    itemId: 991060304,
    key: 'aeq-s6-c3-r4',
    name: 'Coroa dos Cinco Fluxos',
    classId: 3,
    equipSlot: 6,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 35],
      [26, 35],
      [31, 3],
      [28, 2],
    ],
    balanceBudget: 312,
  },
  {
    itemId: 991060305,
    key: 'aeq-s6-c3-r5',
    name: 'Máscara do Lótus',
    classId: 3,
    equipSlot: 6,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 51],
      [26, 51],
      [31, 5],
      [28, 3],
    ],
    balanceBudget: 455,
  },
  {
    itemId: 991060306,
    key: 'aeq-s6-c3-r6',
    name: 'Auréola Celestial',
    classId: 3,
    equipSlot: 6,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 74],
      [26, 74],
      [31, 6],
      [28, 4],
    ],
    balanceBudget: 655,
  },
  {
    itemId: 991060401,
    key: 'aeq-s6-c4-r1',
    name: 'Elmo de Caça',
    classId: 4,
    equipSlot: 6,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 9],
      [26, 7],
      [31, 1],
      [28, 1],
    ],
    balanceBudget: 72,
  },
  {
    itemId: 991060402,
    key: 'aeq-s6-c4-r2',
    name: 'Capuz da Vigília',
    classId: 4,
    equipSlot: 6,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 15],
      [26, 11],
      [31, 2],
      [28, 1],
    ],
    balanceBudget: 119,
  },
  {
    itemId: 991060403,
    key: 'aeq-s6-c4-r3',
    name: 'Diadema do Falcão',
    classId: 4,
    equipSlot: 6,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 25],
      [26, 19],
      [31, 2],
      [28, 2],
    ],
    balanceBudget: 199,
  },
  {
    itemId: 991060404,
    key: 'aeq-s6-c4-r4',
    name: 'Coroa do Horizonte',
    classId: 4,
    equipSlot: 6,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 38],
      [26, 29],
      [31, 3],
      [28, 2],
    ],
    balanceBudget: 300,
  },
  {
    itemId: 991060405,
    key: 'aeq-s6-c4-r5',
    name: 'Máscara da Estrela',
    classId: 4,
    equipSlot: 6,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 57],
      [26, 43],
      [31, 5],
      [28, 3],
    ],
    balanceBudget: 447,
  },
  {
    itemId: 991060406,
    key: 'aeq-s6-c4-r6',
    name: 'Auréola da Lua',
    classId: 4,
    equipSlot: 6,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 82],
      [26, 62],
      [31, 6],
      [28, 4],
    ],
    balanceBudget: 639,
  },
  {
    itemId: 991060501,
    key: 'aeq-s6-c5-r1',
    name: 'Elmo de Ferro',
    classId: 5,
    equipSlot: 6,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 8],
      [26, 8],
      [31, 1],
      [28, 1],
    ],
    balanceBudget: 72,
  },
  {
    itemId: 991060502,
    key: 'aeq-s6-c5-r2',
    name: 'Capuz da Guarda',
    classId: 5,
    equipSlot: 6,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 13],
      [26, 13],
      [31, 2],
      [28, 1],
    ],
    balanceBudget: 119,
  },
  {
    itemId: 991060503,
    key: 'aeq-s6-c5-r3',
    name: 'Diadema da Vanguarda',
    classId: 5,
    equipSlot: 6,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 22],
      [26, 22],
      [31, 2],
      [28, 2],
    ],
    balanceBudget: 199,
  },
  {
    itemId: 991060504,
    key: 'aeq-s6-c5-r4',
    name: 'Coroa do Dragão',
    classId: 5,
    equipSlot: 6,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 35],
      [26, 35],
      [31, 3],
      [28, 2],
    ],
    balanceBudget: 312,
  },
  {
    itemId: 991060505,
    key: 'aeq-s6-c5-r5',
    name: 'Máscara do Firmamento',
    classId: 5,
    equipSlot: 6,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 51],
      [26, 51],
      [31, 5],
      [28, 3],
    ],
    balanceBudget: 455,
  },
  {
    itemId: 991060506,
    key: 'aeq-s6-c5-r6',
    name: 'Auréola Imperial',
    classId: 5,
    equipSlot: 6,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 74],
      [26, 74],
      [31, 6],
      [28, 4],
    ],
    balanceBudget: 655,
  },
  {
    itemId: 991070101,
    key: 'aeq-s7-c1-r1',
    name: 'Luvas de Ferro',
    classId: 1,
    equipSlot: 7,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 6],
      [26, 5],
      [28, 2],
      [30, 1],
    ],
    balanceBudget: 55,
  },
  {
    itemId: 991070102,
    key: 'aeq-s7-c1-r2',
    name: 'Manoplas Rubro',
    classId: 1,
    equipSlot: 7,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 11],
      [26, 8],
      [28, 2],
      [30, 1],
    ],
    balanceBudget: 95,
  },
  {
    itemId: 991070103,
    key: 'aeq-s7-c1-r3',
    name: 'Braçadeiras do Baluarte',
    classId: 1,
    equipSlot: 7,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 18],
      [26, 14],
      [28, 4],
      [30, 2],
    ],
    balanceBudget: 158,
  },
  {
    itemId: 991070104,
    key: 'aeq-s7-c1-r4',
    name: 'Punhos Leonino',
    classId: 1,
    equipSlot: 7,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 29],
      [26, 22],
      [28, 6],
      [30, 2],
    ],
    balanceBudget: 248,
  },
  {
    itemId: 991070105,
    key: 'aeq-s7-c1-r5',
    name: 'Garras do Colosso',
    classId: 1,
    equipSlot: 7,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 42],
      [26, 32],
      [28, 8],
      [30, 4],
    ],
    balanceBudget: 359,
  },
  {
    itemId: 991070106,
    key: 'aeq-s7-c1-r6',
    name: 'Guanteletes do Rei',
    classId: 1,
    equipSlot: 7,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 61],
      [26, 46],
      [28, 11],
      [30, 5],
    ],
    balanceBudget: 513,
  },
  {
    itemId: 991070201,
    key: 'aeq-s7-c2-r1',
    name: 'Luvas de Cinza',
    classId: 2,
    equipSlot: 7,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 5],
      [26, 6],
      [28, 2],
      [30, 1],
    ],
    balanceBudget: 55,
  },
  {
    itemId: 991070202,
    key: 'aeq-s7-c2-r2',
    name: 'Manoplas das Brasas',
    classId: 2,
    equipSlot: 7,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 8],
      [26, 11],
      [28, 2],
      [30, 1],
    ],
    balanceBudget: 95,
  },
  {
    itemId: 991070203,
    key: 'aeq-s7-c2-r3',
    name: 'Braçadeiras do Prisma',
    classId: 2,
    equipSlot: 7,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 14],
      [26, 18],
      [28, 4],
      [30, 2],
    ],
    balanceBudget: 158,
  },
  {
    itemId: 991070204,
    key: 'aeq-s7-c2-r4',
    name: 'Punhos da Tormenta',
    classId: 2,
    equipSlot: 7,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 22],
      [26, 29],
      [28, 6],
      [30, 2],
    ],
    balanceBudget: 248,
  },
  {
    itemId: 991070205,
    key: 'aeq-s7-c2-r5',
    name: 'Garras do Éter',
    classId: 2,
    equipSlot: 7,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 32],
      [26, 42],
      [28, 8],
      [30, 4],
    ],
    balanceBudget: 359,
  },
  {
    itemId: 991070206,
    key: 'aeq-s7-c2-r6',
    name: 'Guanteletes Astral',
    classId: 2,
    equipSlot: 7,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 46],
      [26, 61],
      [28, 11],
      [30, 5],
    ],
    balanceBudget: 513,
  },
  {
    itemId: 991070301,
    key: 'aeq-s7-c3-r1',
    name: 'Luvas de Junco',
    classId: 3,
    equipSlot: 7,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 6],
      [26, 6],
      [28, 2],
      [30, 1],
    ],
    balanceBudget: 59,
  },
  {
    itemId: 991070302,
    key: 'aeq-s7-c3-r2',
    name: 'Manoplas do Selo',
    classId: 3,
    equipSlot: 7,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 10],
      [26, 10],
      [28, 2],
      [30, 1],
    ],
    balanceBudget: 99,
  },
  {
    itemId: 991070303,
    key: 'aeq-s7-c3-r3',
    name: 'Braçadeiras do Equilíbrio',
    classId: 3,
    equipSlot: 7,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 17],
      [26, 17],
      [28, 4],
      [30, 2],
    ],
    balanceBudget: 166,
  },
  {
    itemId: 991070304,
    key: 'aeq-s7-c3-r4',
    name: 'Punhos dos Cinco Fluxos',
    classId: 3,
    equipSlot: 7,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 26],
      [26, 26],
      [28, 6],
      [30, 2],
    ],
    balanceBudget: 252,
  },
  {
    itemId: 991070305,
    key: 'aeq-s7-c3-r5',
    name: 'Garras do Lótus',
    classId: 3,
    equipSlot: 7,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 38],
      [26, 38],
      [28, 8],
      [30, 4],
    ],
    balanceBudget: 367,
  },
  {
    itemId: 991070306,
    key: 'aeq-s7-c3-r6',
    name: 'Guanteletes Celestial',
    classId: 3,
    equipSlot: 7,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 55],
      [26, 55],
      [28, 11],
      [30, 5],
    ],
    balanceBudget: 525,
  },
  {
    itemId: 991070401,
    key: 'aeq-s7-c4-r1',
    name: 'Luvas de Caça',
    classId: 4,
    equipSlot: 7,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 6],
      [26, 5],
      [28, 2],
      [30, 1],
    ],
    balanceBudget: 55,
  },
  {
    itemId: 991070402,
    key: 'aeq-s7-c4-r2',
    name: 'Manoplas da Vigília',
    classId: 4,
    equipSlot: 7,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 11],
      [26, 8],
      [28, 2],
      [30, 1],
    ],
    balanceBudget: 95,
  },
  {
    itemId: 991070403,
    key: 'aeq-s7-c4-r3',
    name: 'Braçadeiras do Falcão',
    classId: 4,
    equipSlot: 7,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 18],
      [26, 14],
      [28, 4],
      [30, 2],
    ],
    balanceBudget: 158,
  },
  {
    itemId: 991070404,
    key: 'aeq-s7-c4-r4',
    name: 'Punhos do Horizonte',
    classId: 4,
    equipSlot: 7,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 29],
      [26, 22],
      [28, 6],
      [30, 2],
    ],
    balanceBudget: 248,
  },
  {
    itemId: 991070405,
    key: 'aeq-s7-c4-r5',
    name: 'Garras da Estrela',
    classId: 4,
    equipSlot: 7,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 42],
      [26, 32],
      [28, 8],
      [30, 4],
    ],
    balanceBudget: 359,
  },
  {
    itemId: 991070406,
    key: 'aeq-s7-c4-r6',
    name: 'Guanteletes da Lua',
    classId: 4,
    equipSlot: 7,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 61],
      [26, 46],
      [28, 11],
      [30, 5],
    ],
    balanceBudget: 513,
  },
  {
    itemId: 991070501,
    key: 'aeq-s7-c5-r1',
    name: 'Luvas de Ferro',
    classId: 5,
    equipSlot: 7,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 6],
      [26, 6],
      [28, 2],
      [30, 1],
    ],
    balanceBudget: 59,
  },
  {
    itemId: 991070502,
    key: 'aeq-s7-c5-r2',
    name: 'Manoplas da Guarda',
    classId: 5,
    equipSlot: 7,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 10],
      [26, 10],
      [28, 2],
      [30, 1],
    ],
    balanceBudget: 99,
  },
  {
    itemId: 991070503,
    key: 'aeq-s7-c5-r3',
    name: 'Braçadeiras da Vanguarda',
    classId: 5,
    equipSlot: 7,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 17],
      [26, 17],
      [28, 4],
      [30, 2],
    ],
    balanceBudget: 166,
  },
  {
    itemId: 991070504,
    key: 'aeq-s7-c5-r4',
    name: 'Punhos do Dragão',
    classId: 5,
    equipSlot: 7,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 26],
      [26, 26],
      [28, 6],
      [30, 2],
    ],
    balanceBudget: 252,
  },
  {
    itemId: 991070505,
    key: 'aeq-s7-c5-r5',
    name: 'Garras do Firmamento',
    classId: 5,
    equipSlot: 7,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 38],
      [26, 38],
      [28, 8],
      [30, 4],
    ],
    balanceBudget: 367,
  },
  {
    itemId: 991070506,
    key: 'aeq-s7-c5-r6',
    name: 'Guanteletes Imperial',
    classId: 5,
    equipSlot: 7,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 55],
      [26, 55],
      [28, 11],
      [30, 5],
    ],
    balanceBudget: 525,
  },
  {
    itemId: 991080101,
    key: 'aeq-s8-c1-r1',
    name: 'Botas de Ferro',
    classId: 1,
    equipSlot: 8,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 6],
      [26, 5],
      [29, 2],
      [31, 1],
    ],
    balanceBudget: 56,
  },
  {
    itemId: 991080102,
    key: 'aeq-s8-c1-r2',
    name: 'Grevas Rubro',
    classId: 1,
    equipSlot: 8,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 10],
      [26, 8],
      [29, 3],
      [31, 1],
    ],
    balanceBudget: 92,
  },
  {
    itemId: 991080103,
    key: 'aeq-s8-c1-r3',
    name: 'Passos do Baluarte',
    classId: 1,
    equipSlot: 8,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 17],
      [26, 13],
      [29, 5],
      [31, 2],
    ],
    balanceBudget: 152,
  },
  {
    itemId: 991080104,
    key: 'aeq-s8-c1-r4',
    name: 'Sandálias Leonino',
    classId: 1,
    equipSlot: 8,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 27],
      [26, 20],
      [29, 8],
      [31, 2],
    ],
    balanceBudget: 236,
  },
  {
    itemId: 991080105,
    key: 'aeq-s8-c1-r5',
    name: 'Coturnos do Colosso',
    classId: 1,
    equipSlot: 8,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 40],
      [26, 30],
      [29, 11],
      [31, 3],
    ],
    balanceBudget: 348,
  },
  {
    itemId: 991080106,
    key: 'aeq-s8-c1-r6',
    name: 'Caminhantes do Rei',
    classId: 1,
    equipSlot: 8,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 57],
      [26, 43],
      [29, 15],
      [31, 4],
    ],
    balanceBudget: 492,
  },
  {
    itemId: 991080201,
    key: 'aeq-s8-c2-r1',
    name: 'Botas de Cinza',
    classId: 2,
    equipSlot: 8,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 5],
      [26, 6],
      [29, 2],
      [31, 1],
    ],
    balanceBudget: 56,
  },
  {
    itemId: 991080202,
    key: 'aeq-s8-c2-r2',
    name: 'Grevas das Brasas',
    classId: 2,
    equipSlot: 8,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 8],
      [26, 10],
      [29, 3],
      [31, 1],
    ],
    balanceBudget: 92,
  },
  {
    itemId: 991080203,
    key: 'aeq-s8-c2-r3',
    name: 'Passos do Prisma',
    classId: 2,
    equipSlot: 8,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 13],
      [26, 17],
      [29, 5],
      [31, 2],
    ],
    balanceBudget: 152,
  },
  {
    itemId: 991080204,
    key: 'aeq-s8-c2-r4',
    name: 'Sandálias da Tormenta',
    classId: 2,
    equipSlot: 8,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 20],
      [26, 27],
      [29, 8],
      [31, 2],
    ],
    balanceBudget: 236,
  },
  {
    itemId: 991080205,
    key: 'aeq-s8-c2-r5',
    name: 'Coturnos do Éter',
    classId: 2,
    equipSlot: 8,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 30],
      [26, 40],
      [29, 11],
      [31, 3],
    ],
    balanceBudget: 348,
  },
  {
    itemId: 991080206,
    key: 'aeq-s8-c2-r6',
    name: 'Caminhantes Astral',
    classId: 2,
    equipSlot: 8,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 43],
      [26, 57],
      [29, 15],
      [31, 4],
    ],
    balanceBudget: 492,
  },
  {
    itemId: 991080301,
    key: 'aeq-s8-c3-r1',
    name: 'Botas de Junco',
    classId: 3,
    equipSlot: 8,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 5],
      [26, 5],
      [29, 2],
      [31, 1],
    ],
    balanceBudget: 52,
  },
  {
    itemId: 991080302,
    key: 'aeq-s8-c3-r2',
    name: 'Grevas do Selo',
    classId: 3,
    equipSlot: 8,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 9],
      [26, 9],
      [29, 3],
      [31, 1],
    ],
    balanceBudget: 92,
  },
  {
    itemId: 991080303,
    key: 'aeq-s8-c3-r3',
    name: 'Passos do Equilíbrio',
    classId: 3,
    equipSlot: 8,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 15],
      [26, 15],
      [29, 5],
      [31, 2],
    ],
    balanceBudget: 152,
  },
  {
    itemId: 991080304,
    key: 'aeq-s8-c3-r4',
    name: 'Sandálias dos Cinco Fluxos',
    classId: 3,
    equipSlot: 8,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 24],
      [26, 24],
      [29, 8],
      [31, 2],
    ],
    balanceBudget: 240,
  },
  {
    itemId: 991080305,
    key: 'aeq-s8-c3-r5',
    name: 'Coturnos do Lótus',
    classId: 3,
    equipSlot: 8,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 36],
      [26, 36],
      [29, 11],
      [31, 3],
    ],
    balanceBudget: 356,
  },
  {
    itemId: 991080306,
    key: 'aeq-s8-c3-r6',
    name: 'Caminhantes Celestial',
    classId: 3,
    equipSlot: 8,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 51],
      [26, 51],
      [29, 15],
      [31, 4],
    ],
    balanceBudget: 500,
  },
  {
    itemId: 991080401,
    key: 'aeq-s8-c4-r1',
    name: 'Botas de Caça',
    classId: 4,
    equipSlot: 8,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 6],
      [26, 5],
      [29, 2],
      [31, 1],
    ],
    balanceBudget: 56,
  },
  {
    itemId: 991080402,
    key: 'aeq-s8-c4-r2',
    name: 'Grevas da Vigília',
    classId: 4,
    equipSlot: 8,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 10],
      [26, 8],
      [29, 3],
      [31, 1],
    ],
    balanceBudget: 92,
  },
  {
    itemId: 991080403,
    key: 'aeq-s8-c4-r3',
    name: 'Passos do Falcão',
    classId: 4,
    equipSlot: 8,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 17],
      [26, 13],
      [29, 5],
      [31, 2],
    ],
    balanceBudget: 152,
  },
  {
    itemId: 991080404,
    key: 'aeq-s8-c4-r4',
    name: 'Sandálias do Horizonte',
    classId: 4,
    equipSlot: 8,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 27],
      [26, 20],
      [29, 8],
      [31, 2],
    ],
    balanceBudget: 236,
  },
  {
    itemId: 991080405,
    key: 'aeq-s8-c4-r5',
    name: 'Coturnos da Estrela',
    classId: 4,
    equipSlot: 8,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 40],
      [26, 30],
      [29, 11],
      [31, 3],
    ],
    balanceBudget: 348,
  },
  {
    itemId: 991080406,
    key: 'aeq-s8-c4-r6',
    name: 'Caminhantes da Lua',
    classId: 4,
    equipSlot: 8,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 57],
      [26, 43],
      [29, 15],
      [31, 4],
    ],
    balanceBudget: 492,
  },
  {
    itemId: 991080501,
    key: 'aeq-s8-c5-r1',
    name: 'Botas de Ferro',
    classId: 5,
    equipSlot: 8,
    catalogRank: 1,
    requiredLevel: 1,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 5],
      [26, 5],
      [29, 2],
      [31, 1],
    ],
    balanceBudget: 52,
  },
  {
    itemId: 991080502,
    key: 'aeq-s8-c5-r2',
    name: 'Grevas da Guarda',
    classId: 5,
    equipSlot: 8,
    catalogRank: 2,
    requiredLevel: 10,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 9],
      [26, 9],
      [29, 3],
      [31, 1],
    ],
    balanceBudget: 92,
  },
  {
    itemId: 991080503,
    key: 'aeq-s8-c5-r3',
    name: 'Passos da Vanguarda',
    classId: 5,
    equipSlot: 8,
    catalogRank: 3,
    requiredLevel: 25,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 15],
      [26, 15],
      [29, 5],
      [31, 2],
    ],
    balanceBudget: 152,
  },
  {
    itemId: 991080504,
    key: 'aeq-s8-c5-r4',
    name: 'Sandálias do Dragão',
    classId: 5,
    equipSlot: 8,
    catalogRank: 4,
    requiredLevel: 40,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 24],
      [26, 24],
      [29, 8],
      [31, 2],
    ],
    balanceBudget: 240,
  },
  {
    itemId: 991080505,
    key: 'aeq-s8-c5-r5',
    name: 'Coturnos do Firmamento',
    classId: 5,
    equipSlot: 8,
    catalogRank: 5,
    requiredLevel: 60,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 36],
      [26, 36],
      [29, 11],
      [31, 3],
    ],
    balanceBudget: 356,
  },
  {
    itemId: 991080506,
    key: 'aeq-s8-c5-r6',
    name: 'Caminhantes Imperial',
    classId: 5,
    equipSlot: 8,
    catalogRank: 6,
    requiredLevel: 80,
    maxEnhancementLevel: 15,
    enhanceable: true,
    enchantable: true,
    blessable: true,
    baseAttributes: [
      [24, 51],
      [26, 51],
      [29, 15],
      [31, 4],
    ],
    balanceBudget: 500,
  },
];

const BY_ID = new Map<number, Mir4EquipmentItemDef>(
  MIR4_EQUIPMENT_CATALOG.map((i) => [i.itemId, i]),
);

export function mir4EquipmentItem(itemId: number): Mir4EquipmentItemDef | null {
  return BY_ID.get(itemId) ?? null;
}
