// Ruinas da Encosta is a production-authored highland city map. Vau Dourado,
// its abandoned outer walls, petrified-root quarry, windward ramparts, root
// crypt and inverted beacon form one physical story instead of six unrelated
// quest clearings.

import type { BiomePaint, HeightStamp, ZonePropsDef } from '../../types';

type Point = { x: number; z: number };
type MissionSiteId =
  | 'ownerless-walls'
  | 'breathing-quarry'
  | 'night-rampart'
  | 'golden-ascent'
  | 'root-crypt'
  | 'root-beacon';
type PoiPurpose = 'service' | 'quest' | 'exploration';
type PoiOccupants = 'citizens' | 'soldiers' | 'bandits' | 'undead' | 'wildlife' | 'guardians';
type PoiArchitecture =
  | 'mountain-pass'
  | 'abandoned-rampart'
  | 'highland-city'
  | 'petrified-root-quarry'
  | 'windward-rampart'
  | 'switchback-road'
  | 'regent-citadel'
  | 'root-maintenance-crypt'
  | 'ancient-aqueduct'
  | 'inverted-root-amphitheater'
  | 'beacon-skybridge';
type DecorOrigin = 'settlement' | 'military' | 'natural' | 'ancient' | 'conclave' | 'guardian';
type DecorProp = NonNullable<ZonePropsDef['decorProps']>[number];
type ArtDistrictId =
  | 'golden-terraces'
  | 'root-undercroft'
  | 'windward-ramparts'
  | 'inverted-beacon';
type M04QuestId =
  | `M04-Q0${1 | 2 | 3 | 4 | 5 | 6}`
  | `M04-S0${1 | 2 | 3}`
  | `M04-R0${1 | 2}`
  | `M04-P0${1 | 2}`;

export interface Mir4M04MissionSite {
  id: MissionSiteId;
  questId: `M04-Q0${1 | 2 | 3 | 4 | 5 | 6}`;
  label: string;
  pos: Point;
  dangerTier: 0 | 1 | 2 | 3;
  levelRange: readonly [number, number];
  gameplay: string;
}

export interface Mir4M04PointOfInterest {
  id: string;
  label: string;
  pos: Point;
  diagnosticSpawn?: Point;
  radius: number;
  purpose: PoiPurpose;
  occupants: PoiOccupants;
  architecture: PoiArchitecture;
  biomeFeature: string;
  narrativeRole: string;
  gameplayRole: string;
}

export interface Mir4M04CampPlan {
  questId: `M04-Q0${1 | 2 | 3 | 4 | 5 | 6}`;
  mobId: string;
  center: Point;
  radius: number;
  count: number;
  levelRange: readonly [number, number];
}

export interface Mir4M04ObjectiveAnchorPlan {
  questId: M04QuestId;
  stageIndex: number;
  points: readonly Point[];
}

export interface Mir4M04DecorPlacement extends DecorProp {
  poiId: string;
  origin: DecorOrigin;
}

export interface Mir4M04ArtDistrict {
  id: ArtDistrictId;
  label: string;
  presentationBiome: 'amber' | 'cave' | 'gale' | 'ember';
  poiIds: readonly string[];
  visualLanguage: string;
  ecologyRule: string;
}

interface Mir4M04NpcPlacement {
  id: string;
  name: string;
  title: string;
  pos: Point;
  facing: number;
  greeting: string;
  campaign: boolean;
}

export interface Mir4M04WorldBlueprint {
  mapId: 'm04-ruinas-da-encosta';
  authoringStatus: 'production-authored';
  fantasy: string;
  progressionPromise: string;
  bounds: { xMin: number; xMax: number; zMin: number; zMax: number };
  hub: Point;
  hubRadius: number;
  graveyard: Point;
  portalIn: Point;
  portalOut: Point;
  missionSites: readonly Mir4M04MissionSite[];
  pointsOfInterest: readonly Mir4M04PointOfInterest[];
  artDistricts: readonly Mir4M04ArtDistrict[];
  biomePaint: BiomePaint;
  roads: readonly (readonly Point[])[];
  litRoads: readonly (readonly Point[])[];
  dryCrossings: readonly { x: number; z: number; radius: number }[];
  camps: readonly Mir4M04CampPlan[];
  objectiveAnchors: readonly Mir4M04ObjectiveAnchorPlan[];
  lakes: readonly { x: number; z: number; radius: number }[];
  terrainEdits: readonly HeightStamp[];
  ruinRings: readonly { x: number; z: number; ringR: number; columns: number }[];
  decorPlacements: readonly Mir4M04DecorPlacement[];
  npcPlacements: readonly Mir4M04NpcPlacement[];
  noticeboard: Point;
}

const MISSION_SITES: readonly Mir4M04MissionSite[] = [
  {
    id: 'ownerless-walls',
    questId: 'M04-Q01',
    label: 'Muros sem Dono',
    pos: { x: 5285, z: 105 },
    dangerTier: 0,
    levelRange: [31, 32],
    gameplay:
      'Three patrol signs lead through separate breaches before the Carrasco emerges at the old gate.',
  },
  {
    id: 'breathing-quarry',
    questId: 'M04-Q02',
    label: 'Pedreira da Pedra que Respira',
    pos: { x: 5415, z: -55 },
    dangerTier: 1,
    levelRange: [33, 34],
    gameplay:
      'Petrified roots, ore seams and a reconstruction table create a real investigation circuit.',
  },
  {
    id: 'night-rampart',
    questId: 'M04-Q03',
    label: 'Muralha da Longa Noite',
    pos: { x: 5510, z: 475 },
    dangerTier: 1,
    levelRange: [35, 35],
    gameplay:
      'Three shelters occupy separate wall sectors and force movement during the ninety-second siege.',
  },
  {
    id: 'golden-ascent',
    questId: 'M04-Q04',
    label: 'Subida das Três Voltas',
    pos: { x: 5625, z: 260 },
    dangerTier: 2,
    levelRange: [36, 37],
    gameplay:
      'A visible switchback road provides three escort checkpoints, repair obstacles and an ambush court.',
  },
  {
    id: 'root-crypt',
    questId: 'M04-Q05',
    label: 'Cripta da Raiz',
    pos: { x: 5710, z: 35 },
    dangerTier: 2,
    levelRange: [38, 39],
    gameplay:
      'Environmental clues disclose the order of three seals before the short dungeon entrance.',
  },
  {
    id: 'root-beacon',
    questId: 'M04-Q06',
    label: 'Farol da Raiz Invertida',
    pos: { x: 5860, z: 385 },
    dangerTier: 3,
    levelRange: [40, 40],
    gameplay:
      'Three exposed wards ring a high amphitheater where the Briar Colossus controls the beacon.',
  },
];

const POINTS_OF_INTEREST: readonly Mir4M04PointOfInterest[] = [
  {
    id: 'm04-poi-passo-lente',
    label: 'Passo da Lente Quebrada',
    pos: { x: 5180, z: 95 },
    radius: 36,
    purpose: 'exploration',
    occupants: 'soldiers',
    architecture: 'mountain-pass',
    biomeFeature: 'A narrow wind-cut shelf receives the road from Bosque do Vale.',
    narrativeRole: 'A shattered beacon lens ties the M03 guardian to the occupied city above.',
    gameplayRole: 'Arrival vista, recovery pocket and readable western entrance.',
  },
  {
    id: 'm04-poi-muros-sem-dono',
    label: 'Muros sem Dono',
    pos: { x: 5285, z: 105 },
    diagnosticSpawn: { x: 5285, z: 40 },
    radius: 58,
    purpose: 'quest',
    occupants: 'bandits',
    architecture: 'abandoned-rampart',
    biomeFeature: 'Collapsed curtain walls span a dry saddle below the inhabited terraces.',
    narrativeRole: 'The Conclave searches each breach for keys to the Farol da Raiz.',
    gameplayRole: 'Tracking circuit, selective hunt and Carrasco gate confrontation.',
  },
  {
    id: 'm04-poi-vau-dourado',
    label: 'Vau Dourado',
    pos: { x: 5390, z: 250 },
    radius: 82,
    purpose: 'service',
    occupants: 'citizens',
    architecture: 'highland-city',
    biomeFeature: 'Warm stone terraces occupy the only broad shelf protected from the east wind.',
    narrativeRole: 'The city unknowingly sits above the original Farol maintenance chamber.',
    gameplayRole: 'Dialogue, contracts, crafting, refinement, blessing and safe recovery.',
  },
  {
    id: 'm04-poi-pedreira-raiz',
    label: 'Pedreira da Raiz Petrificada',
    pos: { x: 5415, z: -55 },
    diagnosticSpawn: { x: 5415, z: -125 },
    radius: 62,
    purpose: 'quest',
    occupants: 'undead',
    architecture: 'petrified-root-quarry',
    biomeFeature: 'A mineral cleft exposes luminous roots inside dark highland stone.',
    narrativeRole: 'The roots prove that the beacon network still conducts light below the city.',
    gameplayRole: 'Three clue inspections, evidence reconstruction and material pressure.',
  },
  {
    id: 'm04-poi-muralha-noite',
    label: 'Muralha da Longa Noite',
    pos: { x: 5510, z: 475 },
    diagnosticSpawn: { x: 5510, z: 405 },
    radius: 66,
    purpose: 'quest',
    occupants: 'soldiers',
    architecture: 'windward-rampart',
    biomeFeature: 'The northern curtain catches uninterrupted gale above a steep visible drop.',
    narrativeRole: 'The night attacks are measurements for Veyr, not attempts to take the wall.',
    gameplayRole: 'Shelter activation, refinement lesson and mobile survival defense.',
  },
  {
    id: 'm04-poi-tres-voltas',
    label: 'Subida das Três Voltas',
    pos: { x: 5625, z: 260 },
    diagnosticSpawn: { x: 5625, z: 190 },
    radius: 72,
    purpose: 'quest',
    occupants: 'guardians',
    architecture: 'switchback-road',
    biomeFeature:
      'Three stone ramps climb the eastern face without hiding the route in teleportation.',
    narrativeRole: 'The Mestre das Chaves controls the only freight path to the upper city.',
    gameplayRole: 'Branch choice, three escort checkpoints, repairs and guardian ambush.',
  },
  {
    id: 'm04-poi-cidadela-regente',
    label: 'Cidadela do Regente',
    pos: { x: 5650, z: 345 },
    radius: 58,
    purpose: 'exploration',
    occupants: 'citizens',
    architecture: 'regent-citadel',
    biomeFeature: 'An upper amber terrace overlooks every defended road and wall sector.',
    narrativeRole: 'Its foundation conceals the civic access shaft into the root network.',
    gameplayRole: 'Vista, lore cache, upper shortcut and escort destination.',
  },
  {
    id: 'm04-poi-cripta-raiz',
    label: 'Cripta da Raiz',
    pos: { x: 5710, z: 35 },
    diagnosticSpawn: { x: 5710, z: -64 },
    radius: 68,
    purpose: 'quest',
    occupants: 'undead',
    architecture: 'root-maintenance-crypt',
    biomeFeature: 'A natural cleft surrounds a worked maintenance door and three root seals.',
    narrativeRole: 'The supposed tomb is the Farol network original service room.',
    gameplayRole: 'Clue order, dungeon tutorial, seal sequence and short dungeon entry.',
  },
  {
    id: 'm04-poi-aqueduto-vento',
    label: 'Aqueduto do Vento Oco',
    pos: { x: 5705, z: 485 },
    radius: 42,
    purpose: 'exploration',
    occupants: 'wildlife',
    architecture: 'ancient-aqueduct',
    biomeFeature: 'Broken water arches sing where the northern gale crosses their empty channels.',
    narrativeRole: 'The aqueduct shows how the upper terrace once fed the beacon grove.',
    gameplayRole: 'Northern shortcut, optional elite pocket and overlook.',
  },
  {
    id: 'm04-poi-farol-raiz',
    label: 'Farol da Raiz Invertida',
    pos: { x: 5860, z: 385 },
    diagnosticSpawn: { x: 5860, z: 305 },
    radius: 74,
    purpose: 'quest',
    occupants: 'guardians',
    architecture: 'inverted-root-amphitheater',
    biomeFeature: 'Black roots and ember light spiral around an ancient highland beacon socket.',
    narrativeRole: 'Veyr reversed the luminous sap and woke the Briar Colossus protecting it.',
    gameplayRole: 'Three ward removals, boss confrontation and beacon reactivation.',
  },
  {
    id: 'm04-poi-ponte-fenda',
    label: 'Ponte sobre a Fenda Clara',
    pos: { x: 5925, z: 385 },
    radius: 34,
    purpose: 'exploration',
    occupants: 'guardians',
    architecture: 'beacon-skybridge',
    biomeFeature: 'A narrow ancient bridge leaves the beacon shelf above a visible mountain cleft.',
    narrativeRole: 'The repaired beacon reveals the road toward Posto da Fenda.',
    gameplayRole: 'Final vista and the physical but gated route to M05.',
  },
];

const ART_DISTRICTS: readonly Mir4M04ArtDistrict[] = [
  {
    id: 'golden-terraces',
    label: 'Terraços Dourados',
    presentationBiome: 'amber',
    poiIds: ['m04-poi-vau-dourado', 'm04-poi-cidadela-regente'],
    visualLanguage:
      'Warm amber grass, blue-roofed civic buildings, ordered markets and high stone silhouettes make the city prosperous but besieged.',
    ecologyRule:
      'Recent human buildings remain on the two defended shelves and never spread into quarry, crypt or guardian habitats.',
  },
  {
    id: 'root-undercroft',
    label: 'Subsolo da Raiz',
    presentationBiome: 'cave',
    poiIds: ['m04-poi-pedreira-raiz', 'm04-poi-cripta-raiz'],
    visualLanguage:
      'Cold mineral ground, exposed ore, cave mouths and sparse artificial light distinguish the buried root network.',
    ecologyRule:
      'Worked stone appears only where miners or ancient maintainers touched the clefts; no homes or market dressing enters them.',
  },
  {
    id: 'windward-ramparts',
    label: 'Muralhas do Barlavento',
    presentationBiome: 'gale',
    poiIds: [
      'm04-poi-passo-lente',
      'm04-poi-muros-sem-dono',
      'm04-poi-muralha-noite',
      'm04-poi-tres-voltas',
      'm04-poi-aqueduto-vento',
      'm04-poi-ponte-fenda',
    ],
    visualLanguage:
      'Pale rock, broken battlements, flags, sparse pines and long sight lines expose every ascent to mountain weather.',
    ecologyRule:
      'Military and ancient transit structures follow ridges and roads, leaving wildlife shelves free of civic buildings.',
  },
  {
    id: 'inverted-beacon',
    label: 'Farol Invertido',
    presentationBiome: 'ember',
    poiIds: ['m04-poi-farol-raiz'],
    visualLanguage:
      'Charred roots, red crystal light and a dark stone arena isolate the finale from the golden city behind it.',
    ecologyRule:
      'Only ancient beacon works, guardian growth and Conclave corruption occupy the final amphitheater.',
  },
];

const M04_PRESENTATION_PAINT: BiomePaint = (() => {
  const cell = 12;
  const originX = 5120;
  const originZ = -160;
  const cols = Math.ceil((5960 - originX) / cell);
  const rows = Math.ceil((600 - originZ) / cell);
  const ellipse = (x: number, z: number, cx: number, cz: number, rx: number, rz: number) =>
    ((x - cx) / rx) ** 2 + ((z - cz) / rz) ** 2 <= 1;
  const ids = Array.from({ length: cols * rows }, (_, index) => {
    const col = index % cols;
    const row = Math.floor(index / cols);
    const x = originX + (col + 0.5) * cell;
    const z = originZ + (row + 0.5) * cell;
    if (x < 5900 && ellipse(x, z, 5860, 385, 72, 122)) return 8;
    if (ellipse(x, z, 5415, -55, 105, 100) || ellipse(x, z, 5710, 35, 86, 88)) return 6;
    if (ellipse(x, z, 5390, 250, 128, 132) || ellipse(x, z, 5650, 345, 82, 86)) return 10;
    return 16;
  });
  return { cell, cols, rows, originX, originZ, ids, affectsTerrain: false };
})();

const DECOR_PLACEMENTS: readonly Mir4M04DecorPlacement[] = [
  // Passo da Lente Quebrada: natural mountain arrival, no settlement clutter.
  {
    poiId: 'm04-poi-passo-lente',
    origin: 'natural',
    key: 'rockTallA',
    x: 5145,
    z: 72,
    rot: 0.4,
    scale: 3.4,
    r: 2.2,
    h: 8,
  },
  {
    poiId: 'm04-poi-passo-lente',
    origin: 'natural',
    key: 'rockTallH',
    x: 5142,
    z: 118,
    rot: -0.2,
    scale: 3.1,
    r: 2.1,
    h: 7,
  },
  {
    poiId: 'm04-poi-passo-lente',
    origin: 'ancient',
    key: 'statueBlock',
    x: 5178,
    z: 111,
    rot: 0.8,
    r: 0.6,
    h: 0.85,
  },
  {
    poiId: 'm04-poi-passo-lente',
    origin: 'ancient',
    key: 'kcasTorch',
    x: 5190,
    z: 80,
    rot: -0.5,
    r: 0.45,
    h: 2.4,
  },
  {
    poiId: 'm04-poi-passo-lente',
    origin: 'natural',
    key: 'rockLargeD',
    x: 5194,
    z: 120,
    rot: 1.1,
    scale: 2.6,
    r: 1.7,
    h: 2.2,
  },
  {
    poiId: 'm04-poi-passo-lente',
    origin: 'ancient',
    key: 'columnBroken',
    x: 5190,
    z: 72,
    rot: -1.2,
    r: 0.6,
    h: 2.1,
  },

  // Muros sem Dono: broken defenses and Conclave occupation.
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'ancient',
    key: 'kcasWallBroken',
    x: 5260,
    z: 76,
    rot: 0.7,
    hw: 4,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'ancient',
    key: 'kcasWallCracked',
    x: 5270,
    z: 69,
    rot: 0.7,
    hw: 4,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'ancient',
    key: 'kcasWallGated',
    x: 5285,
    z: 94,
    rot: Math.PI / 2,
    hw: 4,
    hd: 0.8,
    h: 4,
  },
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'ancient',
    key: 'kcasWallHalf',
    x: 5308,
    z: 127,
    rot: -0.65,
    hw: 2.2,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'ancient',
    key: 'kcasRubbleLarge',
    x: 5274,
    z: 128,
    rot: 1.4,
    scale: 1.1,
    r: 2.4,
    h: 1.7,
  },
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'ancient',
    key: 'kcasRubbleHalf',
    x: 5315,
    z: 95,
    rot: -0.4,
    scale: 1.2,
    r: 1.6,
    h: 1.2,
  },
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'conclave',
    key: 'hexrTent',
    x: 5252,
    z: 121,
    rot: 0.6,
    scale: 4.2,
    r: 2.4,
    h: 3,
  },
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'conclave',
    key: 'hexrWatchtower',
    x: 5323,
    z: 79,
    rot: -0.5,
    scale: 4.8,
    r: 2.3,
    h: 8,
  },
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'conclave',
    key: 'hexFlagRed',
    x: 5298,
    z: 127,
    rot: 0.3,
    scale: 3.2,
  },
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'conclave',
    key: 'weaponStand',
    x: 5262,
    z: 116,
    rot: -0.8,
    hw: 1,
    hd: 0.5,
    h: 2,
  },
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'natural',
    key: 'rockLargeF',
    x: 5238,
    z: 92,
    rot: 0.1,
    scale: 2.8,
    r: 1.8,
    h: 2.6,
  },
  {
    poiId: 'm04-poi-muros-sem-dono',
    origin: 'natural',
    key: 'rockTallA',
    x: 5330,
    z: 138,
    rot: 0.9,
    scale: 3,
    r: 2,
    h: 7,
  },

  // Vau Dourado: every recent civilian building stays on the defended terrace.
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'hexbTownhall',
    x: 5390,
    z: 278,
    rot: Math.PI,
    scale: 8,
    hw: 6.5,
    hd: 6,
    h: 15,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'hexbMarket',
    x: 5352,
    z: 246,
    rot: 0.5,
    scale: 6,
    hw: 4.5,
    hd: 4,
    h: 7,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'hexbTavern',
    x: 5432,
    z: 242,
    rot: -0.6,
    scale: 7,
    hw: 5.5,
    hd: 5,
    h: 11,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'hexbWorkshop',
    x: 5350,
    z: 292,
    rot: 2.8,
    scale: 6.5,
    hw: 5.5,
    hd: 5,
    h: 8,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'hexbHomeA',
    x: 5434,
    z: 292,
    rot: -2.6,
    scale: 7,
    hw: 4.5,
    hd: 4.5,
    h: 8,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'hexbHomeB',
    x: 5350,
    z: 208,
    rot: 0.2,
    scale: 7,
    hw: 5,
    hd: 4.5,
    h: 10,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'hexbHomeA',
    x: 5432,
    z: 205,
    rot: -0.2,
    scale: 7,
    hw: 4.5,
    hd: 4.5,
    h: 8,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'hexbStables',
    x: 5460,
    z: 260,
    rot: -Math.PI / 2,
    scale: 6.5,
    hw: 5.5,
    hd: 5,
    h: 9,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'well',
    x: 5385,
    z: 245,
    r: 1.5,
    h: 2.4,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'stand1',
    x: 5371,
    z: 232,
    rot: 0.3,
    hw: 2,
    hd: 1.2,
    h: 3,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'stand2',
    x: 5408,
    z: 230,
    rot: -0.3,
    hw: 2,
    hd: 1.2,
    h: 3,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'bonfire',
    x: 5390,
    z: 218,
    r: 1.5,
    h: 1.5,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'anvil',
    x: 5362,
    z: 283,
    rot: 0.5,
    r: 0.8,
    h: 1.2,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'cityWagon',
    x: 5445,
    z: 320,
    rot: -1.1,
    scale: 4,
    r: 2.2,
    h: 3.2,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'hexCrateBig',
    x: 5338,
    z: 270,
    rot: 0.6,
    scale: 3,
    r: 1.3,
    h: 1.4,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'hexFlag',
    x: 5376,
    z: 310,
    rot: 0.2,
    scale: 4,
  },
  {
    poiId: 'm04-poi-vau-dourado',
    origin: 'settlement',
    key: 'hexFlag',
    x: 5404,
    z: 310,
    rot: -0.2,
    scale: 4,
  },
  // Pedreira: exposed geology and ancient maintenance fragments only.
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'ancient',
    key: 'kcasWallDoorway',
    x: 5415,
    z: -88,
    rot: 0,
    h: 4,
  },
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'ancient',
    key: 'kcasWallHalf',
    x: 5407,
    z: -88,
    rot: 0,
    hw: 4,
    hd: 0.8,
    h: 4,
  },
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'ancient',
    key: 'kcasWallHalf',
    x: 5423,
    z: -88,
    rot: 0,
    hw: 4,
    hd: 0.8,
    h: 4,
  },
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'natural',
    key: 'rockTallA',
    x: 5365,
    z: -65,
    rot: 0.4,
    scale: 4.4,
    r: 2.8,
    h: 10,
  },
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'natural',
    key: 'rockTallH',
    x: 5466,
    z: -70,
    rot: -0.6,
    scale: 4.1,
    r: 2.6,
    h: 9,
  },
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'natural',
    key: 'rockLargeD',
    x: 5380,
    z: -24,
    rot: 1.1,
    scale: 3.6,
    r: 2.3,
    h: 2.5,
  },
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'natural',
    key: 'rockLargeF',
    x: 5450,
    z: -20,
    rot: -1.3,
    scale: 3.5,
    r: 2.2,
    h: 2.6,
  },
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'natural',
    key: 'oreRocks',
    x: 5392,
    z: -62,
    rot: 0.7,
    scale: 1.4,
    r: 1.4,
    h: 1.3,
  },
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'natural',
    key: 'oreRocks',
    x: 5438,
    z: -49,
    rot: -0.4,
    scale: 1.3,
    r: 1.3,
    h: 1.2,
  },
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'ancient',
    key: 'kkPillar',
    x: 5400,
    z: -72,
    rot: 0.2,
    scale: 0.8,
    r: 0.9,
    h: 4,
  },
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'ancient',
    key: 'kkPillar',
    x: 5430,
    z: -72,
    rot: -0.2,
    scale: 0.8,
    r: 0.9,
    h: 4,
  },
  {
    poiId: 'm04-poi-pedreira-raiz',
    origin: 'natural',
    key: 'oreRocks',
    x: 5425,
    z: -32,
    rot: 0.3,
    scale: 1.6,
    r: 1.5,
    h: 1.4,
  },

  // Northern wall: three readable shelters and a broad combat lane.
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'ancient',
    key: 'kcasWall',
    x: 5468,
    z: 492,
    rot: Math.PI / 2,
    hw: 4,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'ancient',
    key: 'kcasWallCracked',
    x: 5482,
    z: 492,
    rot: Math.PI / 2,
    hw: 4,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'ancient',
    key: 'kcasWallGated',
    x: 5510,
    z: 492,
    rot: Math.PI / 2,
    hw: 4,
    hd: 0.8,
    h: 4,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'ancient',
    key: 'kcasWallCracked',
    x: 5538,
    z: 492,
    rot: Math.PI / 2,
    hw: 4,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'ancient',
    key: 'kcasWall',
    x: 5552,
    z: 492,
    rot: Math.PI / 2,
    hw: 4,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'ancient',
    key: 'hexbTowerA',
    x: 5460,
    z: 482,
    rot: 0.2,
    scale: 5,
    r: 2.8,
    h: 10,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'ancient',
    key: 'hexbTowerB',
    x: 5560,
    z: 482,
    rot: -0.2,
    scale: 5,
    r: 2.8,
    h: 10,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'military',
    key: 'tentOpen',
    x: 5478,
    z: 456,
    rot: 0.1,
    hw: 2.2,
    hd: 2,
    h: 2.5,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'military',
    key: 'tentOpen',
    x: 5510,
    z: 448,
    rot: 0,
    hw: 2.2,
    hd: 2,
    h: 2.5,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'military',
    key: 'tentOpen',
    x: 5542,
    z: 456,
    rot: -0.1,
    hw: 2.2,
    hd: 2,
    h: 2.5,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'military',
    key: 'bonfire',
    x: 5510,
    z: 470,
    r: 1.5,
    h: 1.5,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'military',
    key: 'bonfire',
    x: 5480,
    z: 430,
    r: 1.5,
    h: 1.5,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'military',
    key: 'bonfire',
    x: 5540,
    z: 430,
    r: 1.5,
    h: 1.5,
  },
  {
    poiId: 'm04-poi-muralha-noite',
    origin: 'military',
    key: 'hexFlag',
    x: 5500,
    z: 488,
    rot: 0.3,
    scale: 3.5,
  },

  // Switchbacks: worked transit architecture follows the escort road.
  {
    poiId: 'm04-poi-tres-voltas',
    origin: 'ancient',
    key: 'kcasStairsWide',
    x: 5575,
    z: 230,
    rot: -0.65,
    h: 2,
  },
  {
    poiId: 'm04-poi-tres-voltas',
    origin: 'ancient',
    key: 'kcasStairsWalled',
    x: 5625,
    z: 260,
    rot: 0.45,
    h: 3,
  },
  {
    poiId: 'm04-poi-tres-voltas',
    origin: 'ancient',
    key: 'kcasStairsWide',
    x: 5672,
    z: 292,
    rot: -0.55,
    h: 2,
  },
  {
    poiId: 'm04-poi-tres-voltas',
    origin: 'ancient',
    key: 'kcasBarrier',
    x: 5592,
    z: 252,
    rot: -0.65,
    hw: 2.5,
    hd: 0.4,
    h: 1.2,
  },
  {
    poiId: 'm04-poi-tres-voltas',
    origin: 'ancient',
    key: 'kcasBarrierHalf',
    x: 5650,
    z: 276,
    rot: 0.45,
    hw: 1.4,
    hd: 0.4,
    h: 1.2,
  },
  {
    poiId: 'm04-poi-tres-voltas',
    origin: 'conclave',
    key: 'hexrTent',
    x: 5630,
    z: 225,
    rot: -0.4,
    scale: 4.2,
    r: 2.4,
    h: 3,
  },
  {
    poiId: 'm04-poi-tres-voltas',
    origin: 'conclave',
    key: 'hexrWatchtower',
    x: 5680,
    z: 260,
    rot: 0.5,
    scale: 4.8,
    r: 2.3,
    h: 8,
  },
  {
    poiId: 'm04-poi-tres-voltas',
    origin: 'natural',
    key: 'rockTallH',
    x: 5580,
    z: 300,
    rot: 0.9,
    scale: 3.8,
    r: 2.4,
    h: 8,
  },

  // Cidadela: the second and last lived-in shelf.
  {
    poiId: 'm04-poi-cidadela-regente',
    origin: 'settlement',
    key: 'hexCastle',
    x: 5650,
    z: 360,
    rot: Math.PI,
    scale: 7,
    hw: 7,
    hd: 6,
    h: 14,
  },
  {
    poiId: 'm04-poi-cidadela-regente',
    origin: 'settlement',
    key: 'hexTower',
    x: 5615,
    z: 370,
    rot: 0.2,
    scale: 5,
    r: 3,
    h: 11,
  },
  {
    poiId: 'm04-poi-cidadela-regente',
    origin: 'settlement',
    key: 'hexTower',
    x: 5685,
    z: 370,
    rot: -0.2,
    scale: 5,
    r: 3,
    h: 11,
  },
  {
    poiId: 'm04-poi-cidadela-regente',
    origin: 'settlement',
    key: 'hexBridge',
    x: 5650,
    z: 322,
    rot: 0,
    scale: 5,
    h: 3,
  },
  {
    poiId: 'm04-poi-cidadela-regente',
    origin: 'settlement',
    key: 'hexFlag',
    x: 5635,
    z: 346,
    rot: 0.2,
    scale: 4,
  },
  {
    poiId: 'm04-poi-cidadela-regente',
    origin: 'settlement',
    key: 'hexFlag',
    x: 5665,
    z: 346,
    rot: -0.2,
    scale: 4,
  },
  {
    poiId: 'm04-poi-cidadela-regente',
    origin: 'ancient',
    key: 'kcasColumn',
    x: 5628,
    z: 330,
    rot: 0,
    r: 0.8,
    h: 4,
  },
  {
    poiId: 'm04-poi-cidadela-regente',
    origin: 'ancient',
    key: 'kcasColumn',
    x: 5672,
    z: 330,
    rot: 0,
    r: 0.8,
    h: 4,
  },

  // Cripta: worked ancient maintenance door inside a natural cleft.
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'ancient',
    key: 'delveEntrance2',
    x: 5710,
    z: 0,
    rot: 0,
    scale: 3,
    h: 13,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'ancient',
    key: 'kcasWallDoorway',
    x: 5710,
    z: 4,
    rot: 0,
    scale: 1.5,
    h: 6,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'ancient',
    key: 'kcasWallHalf',
    x: 5701,
    z: 4,
    rot: 0,
    hw: 4,
    hd: 1.2,
    h: 5,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'ancient',
    key: 'kcasWallHalf',
    x: 5719,
    z: 4,
    rot: 0,
    hw: 4,
    hd: 1.2,
    h: 5,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'guardian',
    key: 'bonfire',
    x: 5685,
    z: -8,
    r: 1.5,
    h: 1.5,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'guardian',
    key: 'bonfire',
    x: 5735,
    z: -8,
    r: 1.5,
    h: 1.5,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'natural',
    key: 'rockLargeD',
    x: 5688,
    z: -2,
    rot: 0.5,
    scale: 4.2,
    r: 2.7,
    h: 3.2,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'natural',
    key: 'rockLargeF',
    x: 5732,
    z: -2,
    rot: -0.5,
    scale: 4.2,
    r: 2.7,
    h: 3.2,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'natural',
    key: 'rockTallA',
    x: 5660,
    z: 12,
    rot: 0.4,
    scale: 4.2,
    r: 2.7,
    h: 9,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'natural',
    key: 'marshRootWall',
    x: 5688,
    z: 9,
    rot: 0.25,
    scale: 3.2,
    hw: 4,
    hd: 1.2,
    h: 5,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'natural',
    key: 'marshRootWall',
    x: 5732,
    z: 9,
    rot: -0.25,
    scale: 3.2,
    hw: 4,
    hd: 1.2,
    h: 5,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'natural',
    key: 'marshDeadTree',
    x: 5672,
    z: -6,
    rot: 0.35,
    scale: 2.4,
    r: 1.2,
    h: 9.5,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'natural',
    key: 'marshDeadTree',
    x: 5748,
    z: -4,
    rot: -0.45,
    scale: 2.2,
    r: 1.2,
    h: 8.8,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'natural',
    key: 'rockTallH',
    x: 5760,
    z: 14,
    rot: -0.4,
    scale: 4.2,
    r: 2.7,
    h: 9,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'ancient',
    key: 'kkWallCracked',
    x: 5680,
    z: 48,
    rot: 0.4,
    hw: 3,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'ancient',
    key: 'kkWall',
    x: 5740,
    z: 48,
    rot: -0.4,
    hw: 3,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'ancient',
    key: 'kkPillar',
    x: 5685,
    z: 22,
    rot: 0,
    scale: 0.9,
    r: 1,
    h: 4.5,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'ancient',
    key: 'kkPillar',
    x: 5735,
    z: 22,
    rot: 0,
    scale: 0.9,
    r: 1,
    h: 4.5,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'ancient',
    key: 'kcasShrine',
    x: 5710,
    z: 68,
    rot: Math.PI,
    scale: 1.1,
    r: 1.8,
    h: 4,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'guardian',
    key: 'kcasTorch',
    x: 5682,
    z: 58,
    rot: 0.2,
    r: 0.45,
    h: 2.4,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'guardian',
    key: 'kcasTorch',
    x: 5710,
    z: 78,
    rot: -0.3,
    r: 0.45,
    h: 2.4,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'guardian',
    key: 'kcasTorch',
    x: 5738,
    z: 58,
    rot: 0.5,
    r: 0.45,
    h: 2.4,
  },
  {
    poiId: 'm04-poi-cripta-raiz',
    origin: 'ancient',
    key: 'columnBroken',
    x: 5750,
    z: 72,
    rot: 0.8,
    r: 0.6,
    h: 2.1,
  },

  // Aqueduct: ancient infrastructure inside a wildlife shelf.
  {
    poiId: 'm04-poi-aqueduto-vento',
    origin: 'ancient',
    key: 'kcasWallWindow',
    x: 5680,
    z: 485,
    rot: Math.PI / 2,
    hw: 4,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-aqueduto-vento',
    origin: 'ancient',
    key: 'kcasWallBroken',
    x: 5695,
    z: 485,
    rot: Math.PI / 2,
    hw: 4,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-aqueduto-vento',
    origin: 'ancient',
    key: 'kcasWallWindow',
    x: 5710,
    z: 485,
    rot: Math.PI / 2,
    hw: 4,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-aqueduto-vento',
    origin: 'ancient',
    key: 'kcasWallCracked',
    x: 5725,
    z: 485,
    rot: Math.PI / 2,
    hw: 4,
    hd: 0.7,
    h: 4,
  },
  {
    poiId: 'm04-poi-aqueduto-vento',
    origin: 'natural',
    key: 'rockLargeD',
    x: 5700,
    z: 450,
    rot: 0.6,
    scale: 3.1,
    r: 2,
    h: 2.4,
  },
  {
    poiId: 'm04-poi-aqueduto-vento',
    origin: 'natural',
    key: 'rockTallA',
    x: 5740,
    z: 505,
    rot: -0.8,
    scale: 3.5,
    r: 2.2,
    h: 8,
  },

  // Farol: ancient root machinery and corruption, never civilian construction.
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'ancient',
    key: 'kcasFoundation',
    x: 5860,
    z: 385,
    rot: 0,
    h: 1,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'ancient',
    key: 'kcasColumn',
    x: 5830,
    z: 355,
    rot: 0,
    scale: 3.2,
    r: 2.4,
    h: 13,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'ancient',
    key: 'kcasColumn',
    x: 5890,
    z: 355,
    rot: 0,
    scale: 3.2,
    r: 2.4,
    h: 13,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'ancient',
    key: 'kcasColumn',
    x: 5860,
    z: 425,
    rot: 0,
    scale: 3.2,
    r: 2.4,
    h: 13,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'kcasTorchMounted',
    x: 5830,
    z: 351,
    rot: 0.3,
    r: 0.5,
    h: 3,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'kcasTorchMounted',
    x: 5890,
    z: 351,
    rot: -0.3,
    r: 0.5,
    h: 3,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'kcasTorchMounted',
    x: 5864,
    z: 425,
    rot: 0.8,
    r: 0.5,
    h: 3,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'marshRootWall',
    x: 5815,
    z: 385,
    rot: Math.PI / 2,
    scale: 3.2,
    hw: 3.2,
    hd: 0.8,
    h: 4.8,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'marshRootWall',
    x: 5905,
    z: 385,
    rot: Math.PI / 2,
    scale: 3.2,
    hw: 3.2,
    hd: 0.8,
    h: 4.8,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'conclave',
    key: 'marshBellGallows',
    x: 5860,
    z: 410,
    rot: Math.PI,
    scale: 6,
    r: 2.5,
    h: 15,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'conclave',
    key: 'kcasBannerRedTriple',
    x: 5860,
    z: 345,
    rot: 0,
    hw: 1,
    hd: 0.3,
    h: 4,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'bonfire',
    x: 5830,
    z: 335,
    r: 1.5,
    h: 1.5,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'bonfire',
    x: 5890,
    z: 335,
    r: 1.5,
    h: 1.5,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'bonfire',
    x: 5860,
    z: 445,
    r: 1.5,
    h: 1.5,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'natural',
    key: 'rockLargeD',
    x: 5805,
    z: 360,
    rot: 0.4,
    scale: 4,
    r: 2.6,
    h: 3.2,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'natural',
    key: 'rockLargeF',
    x: 5915,
    z: 360,
    rot: -0.4,
    scale: 4,
    r: 2.6,
    h: 3.2,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'marshDeadTree',
    x: 5825,
    z: 350,
    rot: 0.4,
    scale: 2.5,
    r: 1.4,
    h: 10,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'marshDeadTree',
    x: 5895,
    z: 350,
    rot: -0.4,
    scale: 2.5,
    r: 1.4,
    h: 10,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'marshDeadTree',
    x: 5815,
    z: 415,
    rot: 0.8,
    scale: 2.8,
    r: 1.5,
    h: 11,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'guardian',
    key: 'marshDeadTree',
    x: 5905,
    z: 415,
    rot: -0.8,
    scale: 2.8,
    r: 1.5,
    h: 11,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'ancient',
    key: 'kcasRubbleLarge',
    x: 5840,
    z: 360,
    rot: 0.5,
    scale: 1.8,
    r: 2.2,
    h: 2,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'ancient',
    key: 'kcasRubbleLarge',
    x: 5880,
    z: 360,
    rot: -0.5,
    scale: 1.8,
    r: 2.2,
    h: 2,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'natural',
    key: 'rockTallH',
    x: 5798,
    z: 430,
    rot: 0.6,
    scale: 4,
    r: 2.6,
    h: 9,
  },
  {
    poiId: 'm04-poi-farol-raiz',
    origin: 'natural',
    key: 'rockTallA',
    x: 5920,
    z: 438,
    rot: -0.6,
    scale: 4,
    r: 2.6,
    h: 9,
  },

  // Final skybridge: ancient transit only.
  {
    poiId: 'm04-poi-ponte-fenda',
    origin: 'ancient',
    key: 'hexBridge',
    x: 5925,
    z: 385,
    rot: Math.PI / 2,
    scale: 5,
    h: 3,
  },
  {
    poiId: 'm04-poi-ponte-fenda',
    origin: 'ancient',
    key: 'columnBroken',
    x: 5935,
    z: 370,
    rot: 0.5,
    r: 0.6,
    h: 2.1,
  },
  {
    poiId: 'm04-poi-ponte-fenda',
    origin: 'natural',
    key: 'rockLargeF',
    x: 5944,
    z: 410,
    rot: -0.8,
    scale: 3.2,
    r: 2.1,
    h: 2.6,
  },
];

export const M04_RUINAS_DA_ENCOSTA_BLUEPRINT: Mir4M04WorldBlueprint = {
  mapId: 'm04-ruinas-da-encosta',
  authoringStatus: 'production-authored',
  fantasy:
    'A golden highland city built unknowingly over a buried beacon network while wind, stone and inverted roots expose the price of its occupation.',
  progressionPromise:
    'The player investigates occupied walls, reads petrified roots, survives a moving siege, escorts a switchback ascent, enters a short crypt and breaks three wards before the level-40 boss.',
  bounds: { xMin: 5140, xMax: 6000, zMin: -160, zMax: 600 },
  hub: { x: 5390, z: 250 },
  hubRadius: 82,
  graveyard: { x: 5325, z: 282 },
  portalIn: { x: 5180, z: 95 },
  portalOut: { x: 5925, z: 385 },
  missionSites: MISSION_SITES,
  pointsOfInterest: POINTS_OF_INTEREST,
  artDistricts: ART_DISTRICTS,
  biomePaint: M04_PRESENTATION_PAINT,
  roads: [
    [
      { x: 5180, z: 95 },
      { x: 5220, z: 90 },
      { x: 5285, z: 105 },
    ],
    [
      { x: 5285, z: 105 },
      { x: 5335, z: 165 },
      { x: 5360, z: 205 },
      { x: 5390, z: 250 },
    ],
    [
      { x: 5390, z: 250 },
      { x: 5380, z: 198 },
      { x: 5370, z: 145 },
      { x: 5380, z: 80 },
      { x: 5400, z: 10 },
      { x: 5415, z: -55 },
    ],
    [
      { x: 5390, z: 250 },
      { x: 5410, z: 300 },
      { x: 5430, z: 350 },
      { x: 5470, z: 405 },
      { x: 5510, z: 475 },
    ],
    [
      { x: 5390, z: 250 },
      { x: 5450, z: 230 },
      { x: 5510, z: 215 },
      { x: 5565, z: 235 },
      { x: 5625, z: 260 },
    ],
    [
      { x: 5625, z: 260 },
      { x: 5650, z: 345 },
    ],
    [
      { x: 5415, z: -55 },
      { x: 5490, z: -52 },
      { x: 5570, z: -45 },
      { x: 5640, z: -20 },
      { x: 5710, z: 35 },
    ],
    [
      { x: 5625, z: 260 },
      { x: 5645, z: 200 },
      { x: 5665, z: 145 },
      { x: 5685, z: 90 },
      { x: 5710, z: 35 },
    ],
    [
      { x: 5510, z: 475 },
      { x: 5600, z: 480 },
      { x: 5650, z: 483 },
      { x: 5705, z: 485 },
      { x: 5680, z: 420 },
      { x: 5650, z: 345 },
    ],
    [
      { x: 5650, z: 345 },
      { x: 5740, z: 330 },
      { x: 5805, z: 355 },
      { x: 5860, z: 385 },
    ],
    [
      { x: 5710, z: 35 },
      { x: 5750, z: 100 },
      { x: 5775, z: 145 },
      { x: 5795, z: 190 },
      { x: 5820, z: 270 },
      { x: 5840, z: 330 },
      { x: 5860, z: 385 },
    ],
    [
      { x: 5860, z: 385 },
      { x: 5925, z: 385 },
    ],
  ],
  litRoads: [
    [
      { x: 5335, z: 165 },
      { x: 5390, z: 250 },
      { x: 5430, z: 350 },
    ],
    [
      { x: 5350, z: 292 },
      { x: 5390, z: 250 },
      { x: 5432, z: 242 },
    ],
    [
      { x: 5390, z: 250 },
      { x: 5510, z: 215 },
      { x: 5625, z: 260 },
      { x: 5650, z: 345 },
    ],
  ],
  dryCrossings: [
    { x: 5570, z: -45, radius: 30 },
    { x: 5705, z: 485, radius: 32 },
  ],
  camps: [
    {
      questId: 'M04-Q01',
      mobId: 'bandit_cutthroat',
      center: { x: 5285, z: 105 },
      radius: 42,
      count: 12,
      levelRange: [31, 32],
    },
    {
      questId: 'M04-Q02',
      mobId: 'moss_skeleton',
      center: { x: 5415, z: -55 },
      radius: 44,
      count: 12,
      levelRange: [33, 34],
    },
    {
      questId: 'M04-Q03',
      mobId: 'dire_wolf',
      center: { x: 5510, z: 475 },
      radius: 46,
      count: 13,
      levelRange: [35, 35],
    },
    {
      questId: 'M04-Q04',
      mobId: 'briar_guard',
      center: { x: 5625, z: 260 },
      radius: 48,
      count: 13,
      levelRange: [36, 37],
    },
    {
      questId: 'M04-Q05',
      mobId: 'crypt_rat',
      center: { x: 5710, z: 35 },
      radius: 48,
      count: 14,
      levelRange: [38, 39],
    },
    {
      questId: 'M04-Q06',
      mobId: 'skeleton_spearman',
      center: { x: 5860, z: 385 },
      radius: 52,
      count: 14,
      levelRange: [40, 40],
    },
  ],
  objectiveAnchors: [
    {
      questId: 'M04-Q01',
      stageIndex: 2,
      points: [
        { x: 5258, z: 118 },
        { x: 5298, z: 128 },
        { x: 5315, z: 90 },
      ],
    },
    {
      questId: 'M04-Q01',
      stageIndex: 3,
      points: [
        { x: 5268, z: 95 },
        { x: 5280, z: 115 },
        { x: 5300, z: 120 },
        { x: 5295, z: 90 },
        { x: 5310, z: 105 },
        { x: 5260, z: 125 },
      ],
    },
    { questId: 'M04-Q01', stageIndex: 4, points: [{ x: 5288, z: 108 }] },
    { questId: 'M04-Q01', stageIndex: 5, points: [{ x: 5300, z: 110 }] },
    {
      questId: 'M04-Q02',
      stageIndex: 2,
      points: [
        { x: 5396, z: -58 },
        { x: 5434, z: -45 },
        { x: 5419, z: -38 },
      ],
    },
    { questId: 'M04-Q02', stageIndex: 3, points: [{ x: 5415, z: -30 }] },
    { questId: 'M04-Q02', stageIndex: 4, points: [{ x: 5415, z: -42 }] },
    {
      questId: 'M04-Q03',
      stageIndex: 2,
      points: [
        { x: 5478, z: 450 },
        { x: 5510, z: 442 },
        { x: 5542, z: 450 },
      ],
    },
    { questId: 'M04-Q03', stageIndex: 4, points: [{ x: 5510, z: 478 }] },
    { questId: 'M04-Q03', stageIndex: 5, points: [{ x: 5510, z: 482 }] },
    {
      questId: 'M04-Q04',
      stageIndex: 2,
      points: [
        { x: 5570, z: 240 },
        { x: 5610, z: 245 },
        { x: 5648, z: 280 },
      ],
    },
    { questId: 'M04-Q04', stageIndex: 4, points: [{ x: 5670, z: 260 }] },
    { questId: 'M04-Q04', stageIndex: 5, points: [{ x: 5650, z: 305 }] },
    {
      questId: 'M04-Q05',
      stageIndex: 2,
      points: [
        { x: 5686, z: 58 },
        { x: 5714, z: 78 },
        { x: 5734, z: 58 },
      ],
    },
    {
      questId: 'M04-Q05',
      stageIndex: 4,
      points: [
        { x: 5686, z: 58 },
        { x: 5714, z: 78 },
        { x: 5734, z: 58 },
      ],
    },
    { questId: 'M04-Q05', stageIndex: 5, points: [{ x: 5710, z: 8 }] },
    { questId: 'M04-Q05', stageIndex: 6, points: [{ x: 5710, z: 35 }] },
    {
      questId: 'M04-Q06',
      stageIndex: 2,
      points: [
        { x: 5834, z: 355 },
        { x: 5886, z: 355 },
        { x: 5860, z: 421 },
      ],
    },
    { questId: 'M04-Q06', stageIndex: 3, points: [{ x: 5860, z: 385 }] },
    { questId: 'M04-Q06', stageIndex: 4, points: [{ x: 5840, z: 400 }] },

    // Regional side contracts use the authored quarry, roads, city services
    // and defensive shelves instead of hashed campaign-site fallbacks.
    {
      questId: 'M04-S01',
      stageIndex: 1,
      points: [
        { x: 5258, z: 118 },
        { x: 5298, z: 128 },
        { x: 5315, z: 90 },
        { x: 5396, z: -58 },
        { x: 5434, z: -45 },
        { x: 5419, z: -38 },
        { x: 5686, z: 58 },
        { x: 5734, z: 58 },
      ],
    },
    { questId: 'M04-S01', stageIndex: 2, points: [{ x: 5360, z: 275 }] },
    {
      questId: 'M04-S02',
      stageIndex: 1,
      points: [
        { x: 5186, z: 80 },
        { x: 5705, z: 450 },
        { x: 5805, z: 355 },
      ],
    },
    { questId: 'M04-S02', stageIndex: 2, points: [{ x: 5570, z: -45 }] },
    { questId: 'M04-S02', stageIndex: 3, points: [{ x: 5650, z: 322 }] },
    {
      questId: 'M04-S03',
      stageIndex: 1,
      points: [
        { x: 5355, z: 260 },
        { x: 5390, z: 260 },
        { x: 5425, z: 260 },
      ],
    },
    { questId: 'M04-S03', stageIndex: 2, points: [{ x: 5335, z: 180 }] },
    { questId: 'M04-S03', stageIndex: 3, points: [{ x: 5500, z: 450 }] },

    // Daily contracts reuse public infrastructure and travel along the real
    // switchbacks, so their checkpoints stay useful even outside the story.
    {
      questId: 'M04-R01',
      stageIndex: 1,
      points: [
        { x: 5285, z: 84 },
        { x: 5510, z: 482 },
        { x: 5705, z: 468 },
      ],
    },
    {
      questId: 'M04-R01',
      stageIndex: 2,
      points: [
        { x: 5450, z: 230 },
        { x: 5565, z: 235 },
        { x: 5650, z: 305 },
      ],
    },
    { questId: 'M04-R02', stageIndex: 0, points: [{ x: 5415, z: -30 }] },
    { questId: 'M04-R02', stageIndex: 1, points: [{ x: 5705, z: 450 }] },
    { questId: 'M04-R02', stageIndex: 2, points: [{ x: 5710, z: 8 }] },

    // Profession work points at the visible Vau Dourado workshop, service
    // stations and beacon network. Receipt stages intentionally return to one
    // workstation while field stages spread across the whole map.
    { questId: 'M04-P01', stageIndex: 0, points: [{ x: 5406, z: 260 }] },
    {
      questId: 'M04-P01',
      stageIndex: 1,
      points: [
        { x: 5258, z: 118 },
        { x: 5298, z: 128 },
        { x: 5315, z: 90 },
        { x: 5396, z: -58 },
        { x: 5434, z: -45 },
        { x: 5419, z: -38 },
        { x: 5478, z: 450 },
        { x: 5510, z: 442 },
        { x: 5542, z: 450 },
        { x: 5686, z: 58 },
        { x: 5714, z: 78 },
        { x: 5734, z: 58 },
      ],
    },
    { questId: 'M04-P01', stageIndex: 2, points: [{ x: 5368, z: 290 }] },
    { questId: 'M04-P01', stageIndex: 3, points: [{ x: 5360, z: 275 }] },
    {
      questId: 'M04-P02',
      stageIndex: 1,
      points: [
        { x: 5360, z: 275 },
        { x: 5390, z: 245 },
        { x: 5442, z: 260 },
        { x: 5406, z: 260 },
      ],
    },
    {
      questId: 'M04-P02',
      stageIndex: 2,
      points: [
        { x: 5285, z: 84 },
        { x: 5510, z: 482 },
        { x: 5705, z: 468 },
      ],
    },
    { questId: 'M04-P02', stageIndex: 3, points: [{ x: 5360, z: 275 }] },
    { questId: 'M04-P02', stageIndex: 4, points: [{ x: 5840, z: 400 }] },
  ],
  lakes: [],
  terrainEdits: [
    { x: 5390, z: 250, radius: 104, delta: 7, falloff: 'smooth' },
    { x: 5650, z: 345, radius: 72, delta: 13, falloff: 'smooth' },
    { x: 5415, z: -55, radius: 76, delta: -5, falloff: 'smooth' },
    { x: 5510, z: 510, radius: 150, delta: 8, falloff: 'smooth' },
    { x: 5510, z: 510, radius: 60, delta: 5, falloff: 'smooth' },
    { x: 5625, z: 260, radius: 92, delta: 10, falloff: 'smooth' },
    { x: 5710, z: 35, radius: 84, delta: -3, falloff: 'smooth' },
    { x: 5860, z: 385, radius: 120, delta: 8, falloff: 'smooth' },
    { x: 5860, z: 385, radius: 54, delta: 6, falloff: 'smooth' },
    { x: 5925, z: 360, radius: 20, delta: -12, falloff: 'smooth' },
    { x: 5925, z: 410, radius: 20, delta: -12, falloff: 'smooth' },
    { x: 5790, z: 285, radius: 60, delta: 10, falloff: 'smooth' },
    { x: 5520, z: 565, radius: 150, delta: 21, falloff: 'smooth' },
    { x: 5790, z: -115, radius: 130, delta: 18, falloff: 'smooth' },
  ],
  ruinRings: [
    { x: 5285, z: 105, ringR: 18, columns: 8 },
    { x: 5860, z: 385, ringR: 30, columns: 9 },
  ],
  decorPlacements: DECOR_PLACEMENTS,
  npcPlacements: [
    {
      id: 'm04-ruinas-da-encosta-capita-maela',
      name: 'Capitã Maela',
      title: 'Comandante da Muralha',
      pos: { x: 5374, z: 258 },
      facing: 1.1,
      greeting:
        'Uma muralha sem dono sempre acaba servindo ao primeiro exército que aprende seus buracos.',
      campaign: true,
    },
    {
      id: 'm04-ruinas-da-encosta-regente-auren',
      name: 'Regente Auren',
      title: 'Regente de Vau Dourado',
      pos: { x: 5404, z: 265 },
      facing: -1.1,
      greeting: 'Nossa cidade brilha porque a raiz abaixo dela ainda se lembra do amanhecer.',
      campaign: true,
    },
    {
      id: 'm04-ruinas-da-encosta-aurenna-da-centelha',
      name: 'Aurenna da Centelha',
      title: 'Vigia do Farol',
      pos: { x: 5376, z: 238 },
      facing: 0.6,
      greeting: 'O vento muda de nota quando a Rede está sendo tocada do lado errado.',
      campaign: true,
    },
    {
      id: 'm04-ruinas-da-encosta-doran-sete-marcas',
      name: 'Doran Sete Marcas',
      title: 'Engenheiro da Raiz',
      pos: { x: 5405, z: 238 },
      facing: -0.6,
      greeting: 'Três selos, três raízes e uma ordem que a pedra ainda consegue recordar.',
      campaign: true,
    },
    {
      id: 'm04-ruinas-da-encosta-ferreira-nima',
      name: 'Nima Ferroluz',
      title: 'Ferreira da Encosta',
      pos: { x: 5365, z: 280 },
      facing: 0.2,
      greeting: 'Aço de altitude trinca se você o esfria antes de ouvir o vento.',
      campaign: false,
    },
    {
      id: 'm04-ruinas-da-encosta-alquimista-varo',
      name: 'Varo Raizclara',
      title: 'Alquimista',
      pos: { x: 5418, z: 278 },
      facing: -0.3,
      greeting: 'A seiva petrificada não morreu. Ela apenas aprendeu a conduzir luz devagar.',
      campaign: false,
    },
    {
      id: 'm04-ruinas-da-encosta-guarda-selma',
      name: 'Selma Ventoalto',
      title: 'Guarda do Portão',
      pos: { x: 5335, z: 225 },
      facing: 1.3,
      greeting: 'Do portão para baixo, toda pedra pode esconder uma patrulha.',
      campaign: false,
    },
    {
      id: 'm04-ruinas-da-encosta-mercador-breno',
      name: 'Breno Cobrelimpo',
      title: 'Mercador',
      pos: { x: 5368, z: 228 },
      facing: 0.1,
      greeting: 'Tenho provisões para uma subida e preços para quem pretende voltar.',
      campaign: false,
    },
    {
      id: 'm04-ruinas-da-encosta-curadora-issa',
      name: 'Issa do Sol Frio',
      title: 'Curadora',
      pos: { x: 5420, z: 226 },
      facing: -0.1,
      greeting: 'Feridas do vento fecham. Feridas da raiz precisam primeiro dizer seu nome.',
      campaign: false,
    },
    {
      id: 'm04-ruinas-da-encosta-estabulo-taren',
      name: 'Taren Três-Rédeas',
      title: 'Mestre do Estábulo',
      pos: { x: 5442, z: 258 },
      facing: -1.4,
      greeting: 'Na terceira volta, deixe a montaria escolher a pedra firme.',
      campaign: false,
    },
    {
      id: 'm04-ruinas-da-encosta-pedreira-elva',
      name: 'Elva PedraViva',
      title: 'Mestre da Pedreira',
      pos: { x: 5348, z: 260 },
      facing: 1.5,
      greeting: 'Não chamamos de minério aquilo que pulsa quando a luz se aproxima.',
      campaign: false,
    },
    {
      id: 'm04-ruinas-da-encosta-cartografo-omer',
      name: 'Omer LinhaVento',
      title: 'Cartógrafo',
      pos: { x: 5415, z: 296 },
      facing: -2.2,
      greeting: 'Uma estrada de montanha é um argumento entre a encosta e quem insiste em subir.',
      campaign: false,
    },
    {
      id: 'm04-ruinas-da-encosta-refinadora-cira',
      name: 'Cira SolForte',
      title: 'Refinadora',
      pos: { x: 5368, z: 296 },
      facing: 2.2,
      greeting: 'Chance, garantia e custo. Leia os três antes de encostar no martelo.',
      campaign: false,
    },
    {
      id: 'm04-ruinas-da-encosta-arquivista-pavel',
      name: 'Pavel ChaveAntiga',
      title: 'Arquivista',
      pos: { x: 5402, z: 312 },
      facing: Math.PI,
      greeting:
        'A cripta aparece nos registros como oficina. Alguém decidiu que túmulo soava mais seguro.',
      campaign: false,
    },
    {
      id: 'm04-ruinas-da-encosta-cozinheira-luma',
      name: 'Luma PanDourado',
      title: 'Estalajadeira',
      pos: { x: 5430, z: 250 },
      facing: -Math.PI / 2,
      greeting: 'Coma antes da muralha. O vento cobra energia mesmo quando os monstros não cobram.',
      campaign: false,
    },
    {
      id: 'm04-ruinas-da-encosta-sinaleiro-ged',
      name: 'Ged TrêsSinos',
      title: 'Sinaleiro',
      pos: { x: 5362, z: 236 },
      facing: Math.PI / 2,
      greeting: 'Um sino para a parede, dois para a pedreira, três quando a raiz responde.',
      campaign: false,
    },
  ],
  noticeboard: { x: 5410, z: 260 },
};
