import {
  freezeMir4NativeBuffOverlapCallEvidence,
  freezeMir4NativeBuffValue,
  freezeMir4NativeSkillBuffEvidence,
  type Mir4NativeBuffConsumerEvidenceCatalog,
  type Mir4NativeBuffOverlapCallEvidence,
  type Mir4NativeBuffOverlapCallRawRecord,
  type Mir4NativeBuffRawRecord,
  type Mir4NativeBuffSourceHash,
  type Mir4NativeSkillBuffEvidence,
} from './native_skill_buff_types';

/**
 * Hashes of the sealed MIR4 source files used for this bounded catalog. BUFF_ATTACK
 * is pinned even though every selected BUFF row has BuffAttackID=0.
 */
export const MIR4_NATIVE_SKILL_BUFF_PROVENANCE = freezeMir4NativeBuffValue({
  sources: [
    {
      fileName: 'BUFF.json',
      sha256: '797b38418ce5fd955cceb2d43012f82e4c864e1c0acea0ab5027f67b8142543b',
    },
    {
      fileName: 'BUFF_OVERLAPCALL.json',
      sha256: 'a6d04273c9aadfe8cb0a9b8f6ccdef20e42aaabcaca1a4cde708b11a522cd624',
    },
    {
      fileName: 'BUFF_ATTACK.json',
      sha256: '1be86bf8af4ec777e1543aac1e4091602a8499a9f4cd121acbfe78e8633ab94e',
    },
  ] satisfies readonly Mir4NativeBuffSourceHash[],
  selection: {
    directActionReferenceCount: 36,
    passiveSkillReferenceCount: 1,
    graphTargetCount: 21,
    overlapCallRowCount: 3,
  },
});

/**
 * Located consumer boundaries. A proved row describes only the named bounded
 * consumer; it does not generalize enum names or authorize target-runtime execution.
 */
export const MIR4_NATIVE_SKILL_BUFF_CONSUMER_EVIDENCE = freezeMir4NativeBuffValue({
  nativeIndexType1Writer: {
    status: 'proved',
    ruling: 'numeric calculated-holder writer only',
    sourcePath:
      'F:/Dev/Mir4-Like/docs/topaz-parity/evidence/GameServer.calculated-high-slot-buff-writer-audit.md',
    symbols: [
      'FUN_14006F0D0',
      'FUN_14006F9D0',
      'FUN_14006FE60',
      'FUN_14006D740',
      'FUN_14006CFB0',
      'FUN_140073550',
    ],
  },
  nativeIndexType2: {
    status: 'consumer-not-located',
    ruling: 'unresolved',
    sourcePath: null,
    symbols: [],
  },
  shippingIndexType3WireProjection: {
    status: 'proved',
    ruling: 'wire special-effect projection only; gameplay meaning unresolved',
    sourcePath: 'F:/Dev/Mir4-Like/src/Services/Mir4ServerHost/ShippingWorldSessionAdapter.cs',
    symbols: ['ShippingWorldSessionAdapter.AppendPlayerBuffPublications'],
  },
  nativeIndexType3Gameplay: {
    status: 'consumer-not-located',
    ruling: 'unresolved',
    sourcePath: null,
    symbols: [],
  },
  boundedShippingApplicationGate: {
    status: 'proved',
    ruling:
      'literal numeric admission, duration, and stack gate in the recovered Shipping host only',
    sourcePath: 'F:/Dev/Mir4-Like/src/Services/Mir4ServerHost/ShippingTopazDamageCalculator.cs',
    symbols: [
      'ShippingTopazDamageCalculator.TryBuildBuffApplications',
      'ShippingTopazDamageCalculator.HasOnlyPlayerVectorIndependentEffects',
    ],
  },
  targetRuntime: {
    status: 'consumer-not-located',
    ruling: 'execution blocked',
    sourcePath: null,
    symbols: [],
  },
  periodicity: {
    status: 'consumer-not-located',
    ruling: 'zero UpdateRule and BuffAttackID do not prove periodic semantics',
    sourcePath: null,
    symbols: [],
  },
  detach: {
    status: 'consumer-not-located',
    ruling: 'raw references only',
    sourcePath: null,
    symbols: [],
  },
  overlapCall: {
    status: 'consumer-not-located',
    ruling: 'raw rows and references only',
    sourcePath: null,
    symbols: [],
  },
} satisfies Mir4NativeBuffConsumerEvidenceCatalog);

export const MIR4_NATIVE_DIRECT_SKILL_BUFF_IDS = freezeMir4NativeBuffValue([
  11011, 11012, 11031, 11032, 13011, 13012, 13021, 14011, 14040, 15011, 15012, 20012, 22021, 22042,
  24012, 24031, 31051, 33011, 35010, 35011, 35012, 35014, 35015, 35019, 36010, 40114, 40115, 41001,
  41010, 41071, 43041, 50109, 51011, 53011, 53012, 54011,
] as readonly number[]);

/** BUFF rows referenced by reviewed passive-skill ranks rather than ATTACK rows. */
export const MIR4_NATIVE_PASSIVE_SKILL_BUFF_IDS = freezeMir4NativeBuffValue([
  40102,
] as readonly number[]);

export const MIR4_NATIVE_SKILL_BUFF_GRAPH_TARGET_IDS = freezeMir4NativeBuffValue([
  50010, 50103, 50105, 50106, 50108, 50402, 30205, 30208, 20010, 704001, 705001, 41011, 41012,
  41013, 50101, 50102, 50107, 50505, 50519, 10101, 50514,
] as readonly number[]);

const RAW_BUFF_RECORDS = [
  {
    BuffId: 11011,
    BuffName: 362108,
    BuffExplain: 372108,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 1.5,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4003,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 11012,
    BuffName: 363003,
    BuffExplain: 376101,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341013,
    Icon_Big: 0,
    BuffTime: 15,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 44,
    BuffValue_1: 120,
    LevelUpBuffValue_1: 20,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [24, 0.25, 0],
    Fresnel_Exponenth: 2.9,
    Fresnel_BaseReflect: 0.05,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 11031,
    BuffName: 361102,
    BuffExplain: 371102,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 2050118,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 2,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4004,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 11032,
    BuffName: 361102,
    BuffExplain: 371102,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 2050118,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 3,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4004,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 13011,
    BuffName: 361103,
    BuffExplain: 373104,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050104,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341015,
    Icon_Big: 0,
    BuffTime: 3,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 47,
    BuffValue_1: 240,
    LevelUpBuffValue_1: 40,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 13012,
    BuffName: 2600128,
    BuffExplain: 2600128,
    ShowDamageFont: 1,
    ShowDamageLog: 1,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050001,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341005,
    Icon_Big: 0,
    BuffTime: 5,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4021,
    BuffValue_1: 0,
    LevelUpBuffValue_1: -100,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Top',
    EffectSocket_Type: 'EBuffSocketType::Buff_Top',
    EffectHeight: 60,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 13021,
    BuffName: 361304,
    BuffExplain: 372515,
    ShowDamageFont: 1,
    ShowDamageLog: 1,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 1,
    BuffTarget: 0,
    ActEffect: 2050101,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341014,
    Icon_Big: 0,
    BuffTime: 10,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 20,
    BuffValue_1: -80,
    LevelUpBuffValue_1: -30,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Top',
    EffectSocket_Type: 'EBuffSocketType::Buff_Top',
    EffectHeight: 60,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 14011,
    BuffName: 361105,
    BuffExplain: 371105,
    ShowDamageFont: 1,
    ShowDamageLog: 1,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 1,
    BuffTarget: 0,
    ActEffect: 0,
    BuffEffect: 2050113,
    BuffEffectScale: 1,
    Icon: 341014,
    Icon_Big: 0,
    BuffTime: 5,
    LevelUpBuffTime: 0,
    BuffType: 2,
    BuffIndexType_1: 2,
    BuffIndex_1: 2002,
    BuffValue_1: 1000,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 1,
    BuffIndexType_2: 2,
    BuffIndex_2: 2001,
    BuffValue_2: 10,
    LevelUpBuffValue_2: 25,
    BuffValueEx_2: 1,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 5,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 14040,
    BuffName: 362108,
    BuffExplain: 372108,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 2050118,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 3,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4003,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 15011,
    BuffName: 363004,
    BuffExplain: 372517,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341024,
    Icon_Big: 0,
    BuffTime: 20,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 29,
    BuffValue_1: 60,
    LevelUpBuffValue_1: 10,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 15012,
    BuffName: 363004,
    BuffExplain: 375101,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341015,
    Icon_Big: 0,
    BuffTime: 10,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 42,
    BuffValue_1: 200,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 20012,
    BuffName: 362515,
    BuffExplain: 372207,
    ShowDamageFont: 1,
    ShowDamageLog: 1,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 1,
    BuffTarget: 0,
    ActEffect: 0,
    BuffEffect: 2050113,
    BuffEffectScale: 1,
    Icon: 341044,
    Icon_Big: 0,
    BuffTime: 5,
    LevelUpBuffTime: 0,
    BuffType: 2,
    BuffIndexType_1: 2,
    BuffIndex_1: 2004,
    BuffValue_1: 6000,
    LevelUpBuffValue_1: 1200,
    BuffValueEx_1: 0,
    BuffIndexType_2: 3,
    BuffIndex_2: 4032,
    BuffValue_2: 20010,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [20010],
  },
  {
    BuffId: 22021,
    BuffName: 363112,
    BuffExplain: 370090,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 2,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 3,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4005,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 3,
    BuffIndex_2: 4004,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 3,
    BuffIndex_3: 4002,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: '0',
    EffectSocket_Type: 'EBuffSocketType::NONE',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 22042,
    BuffName: 362514,
    BuffExplain: 372510,
    ShowDamageFont: 1,
    ShowDamageLog: 1,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050103,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341013,
    Icon_Big: 0,
    BuffTime: 60,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 22,
    BuffValue_1: 25,
    LevelUpBuffValue_1: 5,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Top',
    EffectSocket_Type: 'EBuffSocketType::Buff_Top',
    EffectHeight: 60,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 24012,
    BuffName: 361204,
    BuffExplain: 371204,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 2,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 2050133,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 25,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4011,
    BuffValue_1: 2400,
    LevelUpBuffValue_1: 400,
    BuffValueEx_1: 20,
    BuffIndexType_2: 3,
    BuffIndex_2: 4023,
    BuffValue_2: 2000,
    LevelUpBuffValue_2: 7000,
    BuffValueEx_2: 0,
    BuffIndexType_3: 1,
    BuffIndex_3: 35,
    BuffValue_3: 150,
    LevelUpBuffValue_3: 30,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: -90,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [704001, 705001],
  },
  {
    BuffId: 24031,
    BuffName: 361202,
    BuffExplain: 371202,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 3,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4003,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: '0',
    EffectSocket_Type: 'EBuffSocketType::NONE',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 31051,
    BuffName: 361302,
    BuffExplain: 371302,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 2050118,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 5,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4004,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 33011,
    BuffName: 361302,
    BuffExplain: 371302,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 2050118,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 2,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4004,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 35010,
    BuffName: 363205,
    BuffExplain: 375203,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341015,
    Icon_Big: 0,
    BuffTime: 60,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 35,
    BuffValue_1: 100,
    LevelUpBuffValue_1: 20,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 35011,
    BuffName: 362501,
    BuffExplain: 372501,
    ShowDamageFont: 1,
    ShowDamageLog: 1,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050132,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341015,
    Icon_Big: 0,
    BuffTime: 60,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 24,
    BuffValue_1: 25,
    LevelUpBuffValue_1: 5,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 35012,
    BuffName: 362511,
    BuffExplain: 372511,
    ShowDamageFont: 1,
    ShowDamageLog: 1,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050131,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341022,
    Icon_Big: 0,
    BuffTime: 60,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 26,
    BuffValue_1: 25,
    LevelUpBuffValue_1: 5,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 35014,
    BuffName: 362513,
    BuffExplain: 372514,
    ShowDamageFont: 0,
    ShowDamageLog: 1,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 0,
    BuffEffect: 2050135,
    BuffEffectScale: 1,
    Icon: 341011,
    Icon_Big: 0,
    BuffTime: 5.3,
    LevelUpBuffTime: 0,
    BuffType: 2,
    BuffIndexType_1: 2,
    BuffIndex_1: 2027,
    BuffValue_1: 3600,
    LevelUpBuffValue_1: 200,
    BuffValueEx_1: 0,
    BuffIndexType_2: 2,
    BuffIndex_2: 2021,
    BuffValue_2: 100,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 35015,
    BuffName: 362513,
    BuffExplain: 372513,
    ShowDamageFont: 0,
    ShowDamageLog: 1,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050128,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341011,
    Icon_Big: 0,
    BuffTime: 1,
    LevelUpBuffTime: 0,
    BuffType: 2,
    BuffIndexType_1: 2,
    BuffIndex_1: 2022,
    BuffValue_1: 1000,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 2,
    BuffIndex_2: 2027,
    BuffValue_2: 12000,
    LevelUpBuffValue_2: 500,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 35019,
    BuffName: 0,
    BuffExplain: 0,
    ShowDamageFont: 0,
    ShowDamageLog: 1,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 0,
    BuffEffect: 2050107,
    BuffEffectScale: 1,
    Icon: 0,
    Icon_Big: 0,
    BuffTime: 1,
    LevelUpBuffTime: 0,
    BuffType: 2,
    BuffIndexType_1: 2,
    BuffIndex_1: 2022,
    BuffValue_1: 330,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 2,
    BuffIndex_2: 2027,
    BuffValue_2: 1000,
    LevelUpBuffValue_2: 800,
    BuffValueEx_2: 0,
    BuffIndexType_3: 2,
    BuffIndex_3: 2021,
    BuffValue_3: 150,
    LevelUpBuffValue_3: 150,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 36010,
    BuffName: 361501,
    BuffExplain: 371501,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 3,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4003,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: '0',
    EffectSocket_Type: 'EBuffSocketType::NONE',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 40102,
    BuffName: 304102,
    BuffExplain: 373117,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341024,
    Icon_Big: 0,
    BuffTime: 5,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 29,
    BuffValue_1: 50,
    LevelUpBuffValue_1: 50,
    BuffValueEx_1: 0,
    BuffIndexType_2: 3,
    BuffIndex_2: 4037,
    BuffValue_2: 1,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 40114,
    BuffName: 361302,
    BuffExplain: 371302,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 2050118,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 1.5,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4004,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 40115,
    BuffName: 361501,
    BuffExplain: 371501,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 1,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4003,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: '0',
    EffectSocket_Type: 'EBuffSocketType::NONE',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 41001,
    BuffName: 0,
    BuffExplain: 0,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 2,
    BuffTarget: 0,
    ActEffect: 2050143,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 0,
    Icon_Big: 0,
    BuffTime: 1,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 0,
    BuffIndex_1: 0,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 0,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 41010,
    BuffName: 377101,
    BuffExplain: 377102,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 2,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341021,
    Icon_Big: 0,
    BuffTime: 30,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4046,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 10,
    EffectSocket: '0',
    EffectSocket_Type: 'EBuffSocketType::NONE',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 2,
    KeepType_Die: 0,
    KeepType_StageOut: 0,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 41071,
    BuffName: 304107,
    BuffExplain: 375504,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 1,
    BuffTarget: 0,
    ActEffect: 0,
    BuffEffect: 2050007,
    BuffEffectScale: 1,
    Icon: 341033,
    Icon_Big: 0,
    BuffTime: 1,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 28,
    BuffValue_1: -50,
    LevelUpBuffValue_1: -10,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Top',
    EffectSocket_Type: 'EBuffSocketType::Buff_Top',
    EffectHeight: 60,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 43041,
    BuffName: 361020,
    BuffExplain: 376401,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050103,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341013,
    Icon_Big: 0,
    BuffTime: 30,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 20,
    BuffValue_1: 10,
    LevelUpBuffValue_1: 10,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Top',
    EffectSocket_Type: 'EBuffSocketType::Buff_Top',
    EffectHeight: 60,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 50109,
    BuffName: 363310,
    BuffExplain: 375102,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341025,
    Icon_Big: 0,
    BuffTime: 15,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 35,
    BuffValue_1: 150,
    LevelUpBuffValue_1: 30,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 51011,
    BuffName: 361302,
    BuffExplain: 371302,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 2050118,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 1.5,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4004,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 53011,
    BuffName: 361501,
    BuffExplain: 371501,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 1,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4003,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: '0',
    EffectSocket_Type: 'EBuffSocketType::NONE',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 53012,
    BuffName: 361501,
    BuffExplain: 371501,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 2,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4003,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: '0',
    EffectSocket_Type: 'EBuffSocketType::NONE',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 54011,
    BuffName: 363310,
    BuffExplain: 376104,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050104,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341015,
    Icon_Big: 0,
    BuffTime: 5,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 47,
    BuffValue_1: 200,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 50010,
    BuffName: 360080,
    BuffExplain: 370080,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050138,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 4,
    LevelUpBuffTime: 2,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 47,
    BuffValue_1: 300,
    LevelUpBuffValue_1: 200,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: -90,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 50103,
    BuffName: 363310,
    BuffExplain: 376103,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341015,
    Icon_Big: 0,
    BuffTime: 8,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 42,
    BuffValue_1: 50,
    LevelUpBuffValue_1: 100,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 50105,
    BuffName: 363310,
    BuffExplain: 376103,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341015,
    Icon_Big: 0,
    BuffTime: 12,
    LevelUpBuffTime: 3,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 42,
    BuffValue_1: 200,
    LevelUpBuffValue_1: 100,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 50106,
    BuffName: 363310,
    BuffExplain: 375201,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341025,
    Icon_Big: 0,
    BuffTime: 12,
    LevelUpBuffTime: 3,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 43,
    BuffValue_1: 200,
    LevelUpBuffValue_1: 100,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 50108,
    BuffName: 363310,
    BuffExplain: 375201,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050104,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 6,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 43,
    BuffValue_1: 200,
    LevelUpBuffValue_1: 150,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: -90,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [30205],
  },
  {
    BuffId: 50402,
    BuffName: 363304,
    BuffExplain: 376402,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 0,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341022,
    Icon_Big: 0,
    BuffTime: 0,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 22,
    BuffValue_1: 20,
    LevelUpBuffValue_1: 40,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: '0',
    EffectSocket_Type: 'EBuffSocketType::NONE',
    EffectHeight: -90,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 1,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 30205,
    BuffName: 363206,
    BuffExplain: 375201,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050104,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 30,
    LevelUpBuffTime: 30,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 43,
    BuffValue_1: 100,
    LevelUpBuffValue_1: 100,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: -90,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [30208],
  },
  {
    BuffId: 30208,
    BuffName: 363206,
    BuffExplain: 375201,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050104,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341008,
    Icon_Big: 0,
    BuffTime: 20,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 43,
    BuffValue_1: 100,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: -90,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [30205],
  },
  {
    BuffId: 20010,
    BuffName: 362515,
    BuffExplain: 372207,
    ShowDamageFont: 1,
    ShowDamageLog: 1,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 1,
    BuffTarget: 0,
    ActEffect: 0,
    BuffEffect: 2050113,
    BuffEffectScale: 1,
    Icon: 341044,
    Icon_Big: 0,
    BuffTime: 5,
    LevelUpBuffTime: 0,
    BuffType: 2,
    BuffIndexType_1: 2,
    BuffIndex_1: 2004,
    BuffValue_1: 3600,
    LevelUpBuffValue_1: 900,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 704001,
    BuffName: 2606170,
    BuffExplain: 2616170,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 4900002,
    Icon_Big: 0,
    BuffTime: 5,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 47,
    BuffValue_1: 300,
    LevelUpBuffValue_1: 9,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [24012],
  },
  {
    BuffId: 705001,
    BuffName: 2606170,
    BuffExplain: 2616170,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 4900002,
    Icon_Big: 0,
    BuffTime: 8,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 47,
    BuffValue_1: 500,
    LevelUpBuffValue_1: 15,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [24012],
  },
  {
    BuffId: 41011,
    BuffName: 377103,
    BuffExplain: 377106,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 2,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 2050141,
    BuffEffectScale: 1,
    Icon: 341023,
    Icon_Big: 0,
    BuffTime: 0,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 30,
    BuffValue_1: 50,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 0,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 41012,
    BuffName: 377104,
    BuffExplain: 377106,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 2,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 2050141,
    BuffEffectScale: 1,
    Icon: 341023,
    Icon_Big: 0,
    BuffTime: 0,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 30,
    BuffValue_1: 100,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 0,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [41011],
  },
  {
    BuffId: 41013,
    BuffName: 377105,
    BuffExplain: 377106,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 1,
    ApplyType: 2,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 2050142,
    BuffEffectScale: 1,
    Icon: 341023,
    Icon_Big: 0,
    BuffTime: 0,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 30,
    BuffValue_1: 150,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 0,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [41011, 41012],
  },
  {
    BuffId: 50101,
    BuffName: 363302,
    BuffExplain: 376101,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 2050103,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341025,
    Icon_Big: 0,
    BuffTime: 15,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 44,
    BuffValue_1: 100,
    LevelUpBuffValue_1: 100,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Top',
    EffectSocket_Type: 'EBuffSocketType::Buff_Top',
    EffectHeight: 60,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 50102,
    BuffName: 363302,
    BuffExplain: 376102,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341018,
    Icon_Big: 0,
    BuffTime: 15,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 95,
    BuffValue_1: 2000,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 50107,
    BuffName: 363302,
    BuffExplain: 376102,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 0,
    ActEffect: 2050122,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341018,
    Icon_Big: 0,
    BuffTime: 20,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 95,
    BuffValue_1: 3000,
    LevelUpBuffValue_1: 2000,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Root',
    EffectSocket_Type: 'EBuffSocketType::Root',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 50505,
    BuffName: 362521,
    BuffExplain: 376501,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 1,
    BuffTarget: 0,
    ActEffect: 2050102,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341035,
    Icon_Big: 0,
    BuffTime: 10,
    LevelUpBuffTime: 5,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 120,
    BuffValue_1: -100,
    LevelUpBuffValue_1: -50,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Top',
    EffectSocket_Type: 'EBuffSocketType::Buff_Top',
    EffectHeight: 60,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 50519,
    BuffName: 362522,
    BuffExplain: 2610002,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 1,
    BuffTarget: 0,
    ActEffect: 0,
    BuffEffect: 2050111,
    BuffEffectScale: 1,
    Icon: 341031,
    Icon_Big: 0,
    BuffTime: 2,
    LevelUpBuffTime: 0,
    BuffType: 2,
    BuffIndexType_1: 2,
    BuffIndex_1: 2002,
    BuffValue_1: 2000,
    LevelUpBuffValue_1: 500,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Mid',
    EffectSocket_Type: 'EBuffSocketType::Buff_Mid',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 10101,
    BuffName: 362516,
    BuffExplain: 373101,
    ShowDamageFont: 0,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 0,
    BuffTarget: 1,
    ActEffect: 0,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 0,
    Icon_Big: 0,
    BuffTime: 3,
    LevelUpBuffTime: 0,
    BuffType: 1,
    BuffIndexType_1: 1,
    BuffIndex_1: 127,
    BuffValue_1: 50,
    LevelUpBuffValue_1: 50,
    BuffValueEx_1: 0,
    BuffIndexType_2: 0,
    BuffIndex_2: 0,
    BuffValue_2: 0,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: '0',
    EffectSocket_Type: 'EBuffSocketType::NONE',
    EffectHeight: 0,
    BuffArmorType: 0,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
  {
    BuffId: 50514,
    BuffName: 363311,
    BuffExplain: 376510,
    ShowDamageFont: 1,
    ShowDamageLog: 0,
    PetBuff_IconId: [0, 0],
    PetId: 0,
    BuffUseType: 3,
    ApplyType: 1,
    BuffTarget: 0,
    ActEffect: 2050011,
    BuffEffect: 0,
    BuffEffectScale: 1,
    Icon: 341003,
    Icon_Big: 0,
    BuffTime: 1,
    LevelUpBuffTime: 1,
    BuffType: 1,
    BuffIndexType_1: 3,
    BuffIndex_1: 4031,
    BuffValue_1: 0,
    LevelUpBuffValue_1: 0,
    BuffValueEx_1: 0,
    BuffIndexType_2: 1,
    BuffIndex_2: 60,
    BuffValue_2: -100000,
    LevelUpBuffValue_2: 0,
    BuffValueEx_2: 0,
    BuffIndexType_3: 0,
    BuffIndex_3: 0,
    BuffValue_3: 0,
    LevelUpBuffValue_3: 0,
    BuffValueEx_3: 0,
    BuffOverlap: 0,
    EffectSocket: 'Buff_Top',
    EffectSocket_Type: 'EBuffSocketType::Buff_Top',
    EffectHeight: 60,
    BuffArmorType: 4,
    BuffProbability: 1000,
    UpdateRule: 0,
    Emissive_Dcolor: [0, 0, 0],
    Fresnel_Exponenth: 0,
    Fresnel_BaseReflect: 0,
    BuffAttackID: 0,
    ExtinctionEffect: 0,
    ExtinctionEffectSocket: '0',
    OverLapCallGroupID: 0,
    KeepType_Die: 0,
    KeepType_StageOut: 1,
    KeepType_LogOut: 0,
    IsHideRemainTime: 0,
    detachBuffID: [0],
  },
] satisfies readonly Mir4NativeBuffRawRecord[];

const RAW_OVERLAP_CALL_RECORDS = [
  {
    OverLapCallID: 201,
    OverLapCallGroupID: 2,
    BuffOverlapCntMin: 3,
    BuffOverlapCntMax: 5,
    AttachBuffID: [41011],
    BuffOverlapLevel: 1,
  },
  {
    OverLapCallID: 202,
    OverLapCallGroupID: 2,
    BuffOverlapCntMin: 6,
    BuffOverlapCntMax: 8,
    AttachBuffID: [41012],
    BuffOverlapLevel: 2,
  },
  {
    OverLapCallID: 203,
    OverLapCallGroupID: 2,
    BuffOverlapCntMin: 9,
    BuffOverlapCntMax: 10,
    AttachBuffID: [41013],
    BuffOverlapLevel: 3,
  },
] satisfies readonly Mir4NativeBuffOverlapCallRawRecord[];

function failCatalogValidation(message: string): never {
  throw new Error(`Invalid native skill BUFF evidence: ${message}`);
}

function requireUniqueIds(ids: readonly number[], label: string): void {
  if (new Set(ids).size !== ids.length) {
    failCatalogValidation(`${label} contains duplicate IDs`);
  }
}

function buildBuffCatalog(): readonly Mir4NativeSkillBuffEvidence[] {
  requireUniqueIds(MIR4_NATIVE_DIRECT_SKILL_BUFF_IDS, 'direct reference list');
  requireUniqueIds(MIR4_NATIVE_PASSIVE_SKILL_BUFF_IDS, 'passive reference list');
  requireUniqueIds(MIR4_NATIVE_SKILL_BUFF_GRAPH_TARGET_IDS, 'graph target list');

  const directAndPassiveIds = [
    ...MIR4_NATIVE_DIRECT_SKILL_BUFF_IDS,
    ...MIR4_NATIVE_PASSIVE_SKILL_BUFF_IDS,
  ].sort((left, right) => left - right);
  const expectedIds = [...directAndPassiveIds, ...MIR4_NATIVE_SKILL_BUFF_GRAPH_TARGET_IDS];
  requireUniqueIds(expectedIds, 'selected BUFF list');

  if (RAW_BUFF_RECORDS.length !== expectedIds.length) {
    failCatalogValidation('selected BUFF row count differs from the expected ID count');
  }

  return freezeMir4NativeBuffValue(
    RAW_BUFF_RECORDS.map((rawRecord, index) => {
      if (rawRecord.BuffId !== expectedIds[index]) {
        failCatalogValidation(
          `BUFF row ${index} has ID ${rawRecord.BuffId}; expected ${expectedIds[index]}`,
        );
      }
      return freezeMir4NativeSkillBuffEvidence(
        rawRecord,
        MIR4_NATIVE_DIRECT_SKILL_BUFF_IDS.includes(rawRecord.BuffId)
          ? 'direct-action-reference'
          : MIR4_NATIVE_PASSIVE_SKILL_BUFF_IDS.includes(rawRecord.BuffId)
            ? 'passive-skill-reference'
            : 'graph-target',
      );
    }),
  );
}

function buildOverlapCallCatalog(): readonly Mir4NativeBuffOverlapCallEvidence[] {
  requireUniqueIds(
    RAW_OVERLAP_CALL_RECORDS.map((record) => record.OverLapCallID),
    'selected BUFF_OVERLAPCALL rows',
  );
  return freezeMir4NativeBuffValue(
    RAW_OVERLAP_CALL_RECORDS.map(freezeMir4NativeBuffOverlapCallEvidence),
  );
}

export const MIR4_NATIVE_SKILL_BUFF_EVIDENCE = buildBuffCatalog();

export const MIR4_NATIVE_SKILL_BUFF_OVERLAP_CALL_EVIDENCE = buildOverlapCallCatalog();

const BUFF_EVIDENCE_BY_ID = new Map(
  MIR4_NATIVE_SKILL_BUFF_EVIDENCE.map((entry) => [entry.id, entry] as const),
);
const OVERLAP_CALL_EVIDENCE_BY_ID = new Map(
  MIR4_NATIVE_SKILL_BUFF_OVERLAP_CALL_EVIDENCE.map((entry) => [entry.id, entry] as const),
);

function validateReferences(): void {
  if (BUFF_EVIDENCE_BY_ID.size !== MIR4_NATIVE_SKILL_BUFF_EVIDENCE.length) {
    failCatalogValidation('selected BUFF rows are not unique');
  }
  if (OVERLAP_CALL_EVIDENCE_BY_ID.size !== MIR4_NATIVE_SKILL_BUFF_OVERLAP_CALL_EVIDENCE.length) {
    failCatalogValidation('selected BUFF_OVERLAPCALL rows are not unique');
  }

  for (const entry of MIR4_NATIVE_SKILL_BUFF_EVIDENCE) {
    if (entry.id !== entry.rawRecord.BuffId) {
      failCatalogValidation(`BUFF ${entry.id} raw identity differs`);
    }
    for (const referencedId of entry.rawRecord.detachBuffID) {
      if (referencedId !== 0 && !BUFF_EVIDENCE_BY_ID.has(referencedId)) {
        failCatalogValidation(`BUFF ${entry.id} has unresolved raw detachBuffID ${referencedId}`);
      }
    }
  }

  const selectedOverlapGroupIds = new Set(
    MIR4_NATIVE_SKILL_BUFF_EVIDENCE.map((entry) => entry.rawRecord.OverLapCallGroupID).filter(
      (groupId) => groupId !== 0,
    ),
  );
  const rowOverlapGroupIds = new Set(
    MIR4_NATIVE_SKILL_BUFF_OVERLAP_CALL_EVIDENCE.map((entry) => entry.rawRecord.OverLapCallGroupID),
  );

  for (const groupId of selectedOverlapGroupIds) {
    if (!rowOverlapGroupIds.has(groupId)) {
      failCatalogValidation(`raw overlap-call group ${groupId} has no selected rows`);
    }
  }
  for (const overlapEntry of MIR4_NATIVE_SKILL_BUFF_OVERLAP_CALL_EVIDENCE) {
    if (!selectedOverlapGroupIds.has(overlapEntry.rawRecord.OverLapCallGroupID)) {
      failCatalogValidation(
        `overlap-call row ${overlapEntry.id} has no selected BUFF group source`,
      );
    }
    for (const referencedId of overlapEntry.rawRecord.AttachBuffID) {
      if (referencedId !== 0 && !BUFF_EVIDENCE_BY_ID.has(referencedId)) {
        failCatalogValidation(
          `overlap-call row ${overlapEntry.id} has unresolved raw AttachBuffID ${referencedId}`,
        );
      }
    }
  }
}

validateReferences();

export const MIR4_NATIVE_SKILL_BUFF_VALIDATION = freezeMir4NativeBuffValue({
  directReferenceCount: MIR4_NATIVE_DIRECT_SKILL_BUFF_IDS.length,
  passiveReferenceCount: MIR4_NATIVE_PASSIVE_SKILL_BUFF_IDS.length,
  graphTargetCount: MIR4_NATIVE_SKILL_BUFF_GRAPH_TARGET_IDS.length,
  selectedBuffCount: MIR4_NATIVE_SKILL_BUFF_EVIDENCE.length,
  rawDetachReferenceCount: MIR4_NATIVE_SKILL_BUFF_EVIDENCE.reduce(
    (count, entry) => count + entry.rawRecord.detachBuffID.filter((buffId) => buffId !== 0).length,
    0,
  ),
  rawOverlapAttachReferenceCount: MIR4_NATIVE_SKILL_BUFF_OVERLAP_CALL_EVIDENCE.reduce(
    (count, entry) => count + entry.rawRecord.AttachBuffID.filter((buffId) => buffId !== 0).length,
    0,
  ),
  selectedBuffAttackReferenceCount: MIR4_NATIVE_SKILL_BUFF_EVIDENCE.filter(
    (entry) => entry.rawRecord.BuffAttackID !== 0,
  ).length,
  executionStatus: 'blocked-unresolved' as const,
});

export function mir4NativeSkillBuffEvidenceById(
  buffId: number,
): Mir4NativeSkillBuffEvidence | null {
  return BUFF_EVIDENCE_BY_ID.get(buffId) ?? null;
}

export function mir4NativeSkillBuffOverlapCallEvidenceById(
  overlapCallId: number,
): Mir4NativeBuffOverlapCallEvidence | null {
  return OVERLAP_CALL_EVIDENCE_BY_ID.get(overlapCallId) ?? null;
}
