// Aeldrune's gameplay catalogue. The generated extraction in skills.ts stays
// immutable; this layer composes that evidence with complete class kits from
// the official MIR4 client tables without rewriting the imported snapshot.

import {
  MIR4_SKILLS as EXTRACTED_MIR4_SKILLS,
  type Mir4SkillDef as ExtractedMir4SkillDef,
  type Mir4SkillEffect as ExtractedMir4SkillEffect,
} from './skills';

export interface Mir4SkillEffect extends ExtractedMir4SkillEffect {
  /** Entity that receives this effect. Hostile effects default to target. */
  subject?: 'actor' | 'target' | 'party';
  /** Move the actor to the target before resolving the skill. */
  chargeToTarget?: boolean;
  /** Pull every enemy hit toward the actor after contact. */
  pullToActor?: boolean;
  /** Push every enemy hit away from the actor after contact. */
  pushFromActorYards?: number;
}

export interface Mir4SkillDef extends Omit<ExtractedMir4SkillDef, 'effect'> {
  effect: Mir4SkillEffect | null;
  /** Extra effects let one official skill damage enemies and buff its caster. */
  additionalEffects?: readonly Mir4SkillEffect[];
  /** Skill-specific admission range, used by gap closers. */
  castRangePx?: number;
}

function extractedSkill(skillId: number): Mir4SkillDef {
  const skill = EXTRACTED_MIR4_SKILLS.find((candidate) => candidate.skillId === skillId);
  if (!skill) throw new Error(`Missing extracted MIR4 skill ${skillId}`);
  return skill;
}

function damage(
  components: readonly [number, number, number, number?][],
  damageType = 1,
  damageAttribute = 0,
): Mir4SkillDef['damage'] {
  return {
    components: components.map(([attackId, coefficient, levelUpCoefficient, impactCount]) => ({
      attackId,
      damageType,
      damageAttribute,
      coefficient,
      levelUpCoefficient,
      impactCount: impactCount ?? 1,
    })),
    aggregateCoefficient: components.reduce((total, component) => total + component[1], 0),
    aggregateLevelUpCoefficient: components.reduce((total, component) => total + component[2], 0),
    allocationMode: 'per-impact',
  };
}

const WARRIOR_SKILLS: readonly Mir4SkillDef[] = [
  {
    ...extractedSkill(1102),
    slot: 1,
    displayName: 'Corte do Vazio',
    unlock: { kind: 'initial-deck' },
  },
  {
    skillId: 1302,
    classId: 1,
    slot: 2,
    displayName: 'Rugido de Leão',
    unlock: { kind: 'level', level: 10 },
    cooldownMs: 39_000,
    skillCostType: 2,
    skillCost: 2640,
    attackAnimationMs: 1300,
    hitCount: 2,
    requiresTarget: true,
    browserRangePx: 117,
    attackIds: [130201, 130202, 130203],
    damage: damage([
      [130202, 11_000, 270],
      [130203, 2_000, 30],
    ]),
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 112,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 10_000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 1301,
    classId: 1,
    slot: 3,
    displayName: 'Riposta',
    unlock: { kind: 'level', level: 20 },
    cooldownMs: 25_000,
    skillCostType: 2,
    skillCost: 3840,
    attackAnimationMs: 2150,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 117,
    attackIds: [130101, 130102],
    damage: damage([[130102, 25_200, 500]]),
    roles: ['survival-utility', 'single-target'],
    minTargets: null,
    effect: {
      effect: 'defense-boost',
      subject: 'actor',
      durationMs: 3000,
      magnitude: 0.24,
    },
    additionalEffects: [
      {
        effect: 'self-heal',
        subject: 'actor',
        minimumRank: 8,
        healMaxHpBasisPoints: 1000,
        rank10HealMaxHpBasisPoints: 2000,
      },
    ],
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 1101,
    classId: 1,
    slot: 4,
    displayName: 'Fúria',
    unlock: { kind: 'level', level: 30 },
    cooldownMs: 48_000,
    skillCostType: 2,
    skillCost: 5000,
    attackAnimationMs: 1367,
    hitCount: 2,
    requiresTarget: true,
    browserRangePx: 117,
    attackIds: [110100, 110101],
    damage: damage([
      [110100, 8000, 200],
      [110101, 8000, 200],
    ]),
    roles: ['aoe', 'survival-utility'],
    minTargets: 3,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 112,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 10_000,
    },
    additionalEffects: [
      {
        effect: 'damage-boost',
        subject: 'actor',
        durationMs: 15_000,
        magnitude: 0.12,
      },
    ],
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 1103,
    classId: 1,
    slot: 5,
    displayName: 'Investida Bárbara',
    unlock: { kind: 'level', level: 40 },
    cooldownMs: 33_000,
    skillCostType: 2,
    skillCost: 1700,
    attackAnimationMs: 1667,
    hitCount: 2,
    requiresTarget: true,
    browserRangePx: 117,
    castRangePx: 320,
    attackIds: [110105, 110106, 110107],
    damage: damage([
      [110106, 10_000, 220],
      [110107, 11_000, 230],
    ]),
    roles: ['aoe', 'mobility', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'knockdown',
      durationMs: 1200,
      areaRadiusPx: 112,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 10_000,
      chargeToTarget: true,
      pullToActor: true,
    },
    additionalEffects: [
      {
        effect: 'defense-boost',
        subject: 'actor',
        durationMs: 6000,
        magnitude: 0.12,
      },
    ],
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(1104),
    slot: 6,
    displayName: 'Corte Divisor',
    unlock: { kind: 'level', level: 50 },
  },
  {
    ...extractedSkill(1501),
    slot: 7,
    displayName: 'Corte Vendaval',
    unlock: { kind: 'level', level: 60 },
  },
  {
    skillId: 1201,
    classId: 1,
    slot: 8,
    displayName: 'Grilhão de Ferro',
    unlock: { kind: 'level', level: 70 },
    cooldownMs: 40_000,
    skillCostType: 2,
    skillCost: 1920,
    attackAnimationMs: 2833,
    hitCount: 3,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [120101, 120102, 120103],
    damage: damage([
      [120101, 7000, 130],
      [120102, 7000, 130],
      [120103, 8000, 140],
    ]),
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'pull',
      areaRadiusPx: 160,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 10_000,
      pullToActor: true,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 1601,
    classId: 1,
    slot: 9,
    displayName: 'Golpe Crescente',
    unlock: { kind: 'level', level: 80 },
    cooldownMs: 19_000,
    skillCostType: 2,
    skillCost: 1900,
    attackAnimationMs: 1533,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 160,
    attackIds: [160101, 160102, 160103],
    damage: damage([[160103, 18_000, 400]]),
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 112,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 8500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(1304),
    slot: 10,
    displayName: 'Choque Corporal',
    unlock: { kind: 'level', level: 90 },
  },
  {
    ...extractedSkill(1401),
    slot: 11,
    displayName: 'Esmagamento Terrestre',
    unlock: { kind: 'level', level: 100 },
  },
  {
    skillId: 1502,
    classId: 1,
    slot: 12,
    displayName: 'Postura Inquebrável',
    unlock: { kind: 'level', level: 110 },
    cooldownMs: 52_000,
    skillCostType: 2,
    skillCost: 6400,
    attackAnimationMs: 1167,
    hitCount: 1,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [150201, 150202],
    damage: damage([[150202, 8000, 200]]),
    roles: ['aoe', 'survival-utility'],
    minTargets: 3,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 112,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 10_000,
    },
    additionalEffects: [
      {
        effect: 'dodge-boost',
        subject: 'actor',
        durationMs: 20_000,
        magnitude: 60,
      },
    ],
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
];

const SORCERER_SKILLS: readonly Mir4SkillDef[] = [
  {
    ...extractedSkill(2101),
    slot: 1,
    displayName: 'Esfera Flamejante',
    unlock: { kind: 'initial-deck' },
    roles: ['aoe', 'debuff', 'single-target'],
    minTargets: 3,
    effect: {
      effect: 'burn',
      durationMs: 4500,
      magnitude: 0.08,
      areaRadiusPx: 104,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6500,
    },
  },
  {
    ...extractedSkill(2111),
    slot: 2,
    displayName: 'Esfera Gelada',
    unlock: { kind: 'level', level: 10 },
    roles: ['aoe', 'debuff', 'single-target'],
    minTargets: 3,
    effect: {
      effect: 'slow',
      durationMs: 3200,
      magnitude: 0.35,
      areaRadiusPx: 104,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6500,
    },
  },
  {
    ...extractedSkill(2501),
    slot: 3,
    displayName: 'Vórtice das Trevas',
    unlock: { kind: 'level', level: 20 },
    requiresTarget: true,
    browserRangePx: 128,
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'root',
      durationMs: 2200,
      areaRadiusPx: 128,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 6000,
      pullToActor: true,
    },
  },
  {
    ...extractedSkill(2301),
    slot: 4,
    displayName: 'Tempestade de Relâmpagos',
    unlock: { kind: 'level', level: 30 },
    requiresTarget: true,
    browserRangePx: 128,
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'dazed',
      durationMs: 1200,
      areaRadiusPx: 112,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 6500,
    },
  },
  {
    ...extractedSkill(2503),
    slot: 5,
    displayName: 'Escudo Mágico',
    unlock: { kind: 'level', level: 40 },
  },
  {
    skillId: 2203,
    classId: 2,
    slot: 6,
    displayName: 'Nevão',
    unlock: { kind: 'level', level: 50 },
    cooldownMs: 40_000,
    skillCostType: 2,
    skillCost: 4800,
    attackAnimationMs: 1633,
    hitCount: 7,
    requiresTarget: true,
    browserRangePx: 128,
    attackIds: [220301, 220302],
    damage: {
      components: [
        {
          attackId: 220302,
          damageType: 2,
          damageAttribute: 2,
          coefficient: 3900,
          levelUpCoefficient: 80,
          impactCount: 7,
        },
      ],
      aggregateCoefficient: 27_300,
      aggregateLevelUpCoefficient: 560,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'freeze',
      durationMs: 1800,
      areaRadiusPx: 144,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 10_000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 2303,
    classId: 2,
    slot: 7,
    displayName: 'Cadeia de Relâmpagos',
    unlock: { kind: 'level', level: 60 },
    cooldownMs: 18_000,
    skillCostType: 2,
    skillCost: 2200,
    attackAnimationMs: 2100,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 160,
    attackIds: [230301],
    damage: {
      components: [
        {
          attackId: 230301,
          damageType: 2,
          damageAttribute: 3,
          coefficient: 17_600,
          levelUpCoefficient: 300,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 17_600,
      aggregateLevelUpCoefficient: 300,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'single-target'],
    minTargets: 2,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 192,
      maxSecondaryTargets: 6,
      secondaryDamageBasisPoints: 10_000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 2201,
    classId: 2,
    slot: 8,
    displayName: 'Coluna de Chamas',
    unlock: { kind: 'level', level: 70 },
    cooldownMs: 20_000,
    skillCostType: 2,
    skillCost: 1400,
    attackAnimationMs: 1767,
    hitCount: 3,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [220101, 220102, 220103],
    damage: {
      components: [
        {
          attackId: 220102,
          damageType: 2,
          damageAttribute: 1,
          coefficient: 8000,
          levelUpCoefficient: 180,
          impactCount: 1,
        },
        {
          attackId: 220103,
          damageType: 2,
          damageAttribute: 1,
          coefficient: 15_000,
          levelUpCoefficient: 320,
          impactCount: 2,
        },
      ],
      aggregateCoefficient: 38_000,
      aggregateLevelUpCoefficient: 820,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: 2,
    effect: {
      effect: 'dazed',
      durationMs: 900,
      areaRadiusPx: 112,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 10_000,
      pushFromActorYards: 5.5,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 2502,
    classId: 2,
    slot: 9,
    displayName: 'Devoração da Alma',
    unlock: { kind: 'level', level: 80 },
    cooldownMs: 30_000,
    skillCostType: 2,
    skillCost: 2160,
    attackAnimationMs: 1867,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 128,
    attackIds: [250201, 250202],
    damage: {
      components: [
        {
          attackId: 250202,
          damageType: 2,
          damageAttribute: 3,
          coefficient: 4000,
          levelUpCoefficient: 100,
          impactCount: 5,
        },
      ],
      aggregateCoefficient: 20_000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'per-impact',
    },
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 112,
      maxSecondaryTargets: 5,
      secondaryDamageBasisPoints: 10_000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 2103,
    classId: 2,
    slot: 10,
    displayName: 'Imolar',
    unlock: { kind: 'level', level: 90 },
    cooldownMs: 45_000,
    skillCostType: 2,
    skillCost: 7000,
    attackAnimationMs: 2800,
    hitCount: 10,
    requiresTarget: true,
    browserRangePx: 128,
    attackIds: [210301, 210302, 210303, 210304, 210305],
    damage: {
      components: [
        {
          attackId: 210301,
          damageType: 2,
          damageAttribute: 1,
          coefficient: 7000,
          levelUpCoefficient: 140,
          impactCount: 2,
        },
        {
          attackId: 210302,
          damageType: 2,
          damageAttribute: 1,
          coefficient: 7000,
          levelUpCoefficient: 140,
          impactCount: 2,
        },
        {
          attackId: 210303,
          damageType: 2,
          damageAttribute: 1,
          coefficient: 8000,
          levelUpCoefficient: 160,
          impactCount: 2,
        },
        {
          attackId: 210304,
          damageType: 2,
          damageAttribute: 1,
          coefficient: 8000,
          levelUpCoefficient: 160,
          impactCount: 2,
        },
        {
          attackId: 210305,
          damageType: 2,
          damageAttribute: 1,
          coefficient: 10_000,
          levelUpCoefficient: 200,
          impactCount: 2,
        },
      ],
      aggregateCoefficient: 80_000,
      aggregateLevelUpCoefficient: 1600,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'burn',
      durationMs: 6500,
      magnitude: 0.12,
      areaRadiusPx: 160,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 7500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 2204,
    classId: 2,
    slot: 11,
    displayName: 'Abraço da Fênix',
    unlock: { kind: 'level', level: 100 },
    cooldownMs: 54_000,
    skillCostType: 2,
    skillCost: 3000,
    attackAnimationMs: 1600,
    hitCount: 0,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [220401, 220402],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: {
      effect: 'damage-boost',
      subject: 'actor',
      durationMs: 60_000,
      magnitude: 0.25,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 2202,
    classId: 2,
    slot: 12,
    displayName: 'Bloqueio de Gelo',
    unlock: { kind: 'level', level: 110 },
    cooldownMs: 53_000,
    skillCostType: 2,
    skillCost: 6300,
    attackAnimationMs: 4000,
    hitCount: 3,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [220201, 220202, 220203],
    damage: {
      components: [
        {
          attackId: 220201,
          damageType: 2,
          damageAttribute: 2,
          coefficient: 2200,
          levelUpCoefficient: 0,
          impactCount: 1,
        },
        {
          attackId: 220202,
          damageType: 2,
          damageAttribute: 2,
          coefficient: 9900,
          levelUpCoefficient: 200,
          impactCount: 1,
        },
        {
          attackId: 220203,
          damageType: 2,
          damageAttribute: 2,
          coefficient: 9900,
          levelUpCoefficient: 200,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 22_000,
      aggregateLevelUpCoefficient: 400,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'survival-utility'],
    minTargets: 1,
    effect: {
      effect: 'freeze',
      durationMs: 2000,
      areaRadiusPx: 112,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 10_000,
    },
    additionalEffects: [
      {
        effect: 'magic-shield',
        subject: 'actor',
        durationMs: 4000,
        magnitude: 1,
      },
    ],
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
];

const TAOIST_SKILLS: readonly Mir4SkillDef[] = [
  {
    skillId: 3506,
    classId: 3,
    slot: 1,
    displayName: 'Onda Lunar',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 21_000,
    skillCostType: 2,
    skillCost: 2600,
    attackAnimationMs: 2533,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 128,
    attackIds: [350601, 350602],
    damage: damage([[350602, 6000, 100, 5]], 2, 5),
    roles: ['aoe', 'debuff', 'single-target'],
    minTargets: 3,
    effect: {
      effect: 'slow',
      durationMs: 8000,
      magnitude: 0.25,
      areaRadiusPx: 112,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(3101),
    slot: 2,
    displayName: 'Espada de Raio Solar',
    unlock: { kind: 'level', level: 10 },
  },
  {
    skillId: 3301,
    classId: 3,
    slot: 3,
    displayName: 'Esfera Lunar',
    unlock: { kind: 'level', level: 20 },
    cooldownMs: 24_000,
    skillCostType: 2,
    skillCost: 2400,
    attackAnimationMs: 1533,
    hitCount: 9,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [330101, 330102],
    damage: damage([[330102, 3500, 60, 9]], 2, 5),
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'root',
      durationMs: 1600,
      areaRadiusPx: 116,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3104,
    classId: 3,
    slot: 4,
    displayName: 'Chuva de Lâminas',
    unlock: { kind: 'level', level: 30 },
    cooldownMs: 20_000,
    skillCostType: 2,
    skillCost: 3840,
    attackAnimationMs: 1267,
    hitCount: 4,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [310401, 310402],
    damage: {
      components: [
        {
          attackId: 310402,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 6000,
          levelUpCoefficient: 130,
          impactCount: 2,
        },
        {
          attackId: 310402,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 3000,
          levelUpCoefficient: 60,
          impactCount: 2,
        },
      ],
      aggregateCoefficient: 18_000,
      aggregateLevelUpCoefficient: 380,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 124,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 6000,
    },
    additionalEffects: [
      {
        effect: 'silence',
        subject: 'target',
        minimumRank: 8,
        durationMs: 4000,
        pveChanceBasisPoints: 4000,
        pvpChanceBasisPoints: 4000,
      },
    ],
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(3503),
    slot: 5,
    displayName: 'Cura',
    unlock: { kind: 'level', level: 40 },
    effect: {
      effect: 'heal-pulse',
      subject: 'party',
      utility: 'heal',
      healMaxHpBasisPoints: 1800,
      partyRadiusPx: 320,
      maxPartyTargets: 5,
    },
  },
  {
    skillId: 3103,
    classId: 3,
    slot: 6,
    displayName: 'Lâminas Perfurantes',
    unlock: { kind: 'level', level: 50 },
    cooldownMs: 20_000,
    skillCostType: 2,
    skillCost: 1500,
    attackAnimationMs: 1767,
    hitCount: 6,
    requiresTarget: true,
    browserRangePx: 176,
    attackIds: [310301, 310302, 310303],
    damage: damage([
      [310302, 10_000, 200],
      [310303, 10_000, 200],
    ]),
    roles: ['aoe', 'debuff', 'single-target'],
    minTargets: 3,
    effect: {
      effect: 'stun',
      minimumRank: 5,
      durationMs: 2000,
      areaRadiusPx: 104,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6500,
      pveChanceBasisPoints: 10_000,
      pvpChanceBasisPoints: 2000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3501,
    classId: 3,
    slot: 7,
    displayName: 'Círculo do Guardião',
    unlock: { kind: 'level', level: 60 },
    cooldownMs: 46_000,
    skillCostType: 2,
    skillCost: 2640,
    attackAnimationMs: 1000,
    hitCount: 1,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [350101, 350102, 350103],
    damage: damage([[350102, 6000, 100]], 2),
    roles: ['aoe', 'survival-utility'],
    minTargets: 2,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 112,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 10_000,
    },
    additionalEffects: [
      {
        effect: 'defense-boost',
        subject: 'party',
        durationMs: 60_000,
        magnitude: 0.25,
        partyRadiusPx: 320,
        maxPartyTargets: 5,
      },
    ],
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3201,
    classId: 3,
    slot: 8,
    displayName: 'Tai Chi',
    unlock: { kind: 'level', level: 70 },
    cooldownMs: 35_000,
    skillCostType: 2,
    skillCost: 3000,
    attackAnimationMs: 2067,
    hitCount: 6,
    requiresTarget: true,
    browserRangePx: 112,
    attackIds: [320101, 320102, 320103, 320104, 320105, 320106, 320107],
    damage: {
      components: [
        {
          attackId: 320101,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4000,
          levelUpCoefficient: 80,
          impactCount: 6,
        },
        {
          attackId: 320101,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 1000,
          levelUpCoefficient: 20,
          impactCount: 6,
        },
      ],
      aggregateCoefficient: 30_000,
      aggregateLevelUpCoefficient: 600,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'knockdown',
      durationMs: 1500,
      areaRadiusPx: 112,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 10_000,
      pveChanceBasisPoints: 10_000,
      pvpChanceBasisPoints: 1000,
      pullToActor: true,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3505,
    classId: 3,
    slot: 9,
    displayName: 'Amuleto Explosivo',
    unlock: { kind: 'level', level: 80 },
    cooldownMs: 28_000,
    skillCostType: 2,
    skillCost: 4000,
    attackAnimationMs: 1533,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [350501, 350502],
    damage: damage([[350502, 24_000, 500]], 2, 6),
    roles: ['debuff', 'single-target'],
    minTargets: null,
    effect: {
      effect: 'blind',
      durationMs: 8000,
      magnitude: 0.35,
    },
    additionalEffects: [
      {
        effect: 'defense-break',
        subject: 'target',
        durationMs: 15_000,
        magnitude: 0.12,
      },
    ],
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3203,
    classId: 3,
    slot: 10,
    displayName: 'Golpe Esvoaçante',
    unlock: { kind: 'level', level: 90 },
    cooldownMs: 31_000,
    skillCostType: 2,
    skillCost: 2800,
    attackAnimationMs: 1700,
    hitCount: 9,
    requiresTarget: true,
    browserRangePx: 112,
    attackIds: [320301, 320302, 320303],
    damage: {
      components: [
        {
          attackId: 320302,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 9000,
          levelUpCoefficient: 200,
          impactCount: 3,
        },
        {
          attackId: 320303,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 3000,
          levelUpCoefficient: 60,
          impactCount: 3,
        },
      ],
      aggregateCoefficient: 36_000,
      aggregateLevelUpCoefficient: 780,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'defense-break',
      durationMs: 10_000,
      magnitude: 0.12,
      areaRadiusPx: 112,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 7000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3404,
    classId: 3,
    slot: 11,
    displayName: 'Círculo de Expulsão',
    unlock: { kind: 'level', level: 100 },
    cooldownMs: 46_000,
    skillCostType: 2,
    skillCost: 3000,
    attackAnimationMs: 1000,
    hitCount: 0,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [340401],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: {
      effect: 'defense-boost',
      subject: 'party',
      durationMs: 60_000,
      magnitude: 0.25,
      partyRadiusPx: 320,
      maxPartyTargets: 5,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3504,
    classId: 3,
    slot: 12,
    displayName: 'Cura Maior',
    unlock: { kind: 'level', level: 110 },
    cooldownMs: 46_000,
    skillCostType: 2,
    skillCost: 5880,
    attackAnimationMs: 1640,
    hitCount: 0,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [350401, 350402, 350403, 350404],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: {
      effect: 'heal-pulse',
      subject: 'actor',
      utility: 'heal',
      healMaxHpBasisPoints: 4500,
      partyRadiusPx: 320,
      maxPartyTargets: 5,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
];

const ARBALIST_SKILLS: readonly Mir4SkillDef[] = [
  {
    ...extractedSkill(4101),
    slot: 1,
    displayName: 'Tiro Rápido',
    unlock: { kind: 'initial-deck' },
    roles: ['aoe', 'single-target'],
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 112,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6500,
    },
  },
  {
    ...extractedSkill(4106),
    slot: 2,
    displayName: 'Vendaval de Golpe de Dor',
    unlock: { kind: 'level', level: 10 },
  },
  {
    ...extractedSkill(4102),
    slot: 3,
    displayName: 'Seta da Ilusão',
    unlock: { kind: 'level', level: 20 },
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 106,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6500,
    },
    additionalEffects: [
      { effect: 'dodge-boost', subject: 'actor', durationMs: 4000, magnitude: 60 },
    ],
  },
  {
    skillId: 4103,
    classId: 4,
    slot: 4,
    displayName: 'Escudo Explosivo',
    unlock: { kind: 'level', level: 30 },
    cooldownMs: 26_000,
    skillCostType: 2,
    skillCost: 2100,
    attackAnimationMs: 1100,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [410301, 410302, 410303],
    damage: damage([[410303, 22_000, 500]]),
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'defense-break',
      durationMs: 10_000,
      magnitude: 0.12,
      areaRadiusPx: 120,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 6500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4107,
    classId: 4,
    slot: 5,
    displayName: 'Seta do Clarão',
    unlock: { kind: 'level', level: 40 },
    cooldownMs: 35_000,
    skillCostType: 2,
    skillCost: 4000,
    attackAnimationMs: 1000,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [410701, 410702],
    damage: damage([[410702, 19_000, 400]]),
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'blind',
      durationMs: 5000,
      magnitude: 0.45,
      areaRadiusPx: 108,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4108,
    classId: 4,
    slot: 6,
    displayName: 'Arco Celestial',
    unlock: { kind: 'level', level: 50 },
    cooldownMs: 20_000,
    skillCostType: 2,
    skillCost: 2800,
    attackAnimationMs: 1133,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 256,
    attackIds: [410801, 410802],
    damage: damage([[410802, 30_000, 600]]),
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 144,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 8500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4111,
    classId: 4,
    slot: 7,
    displayName: 'Olho da Mente',
    unlock: { kind: 'level', level: 60 },
    cooldownMs: 30_000,
    skillCostType: 2,
    skillCost: 2000,
    attackAnimationMs: 1000,
    hitCount: 0,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [411101],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: {
      effect: 'damage-boost',
      subject: 'actor',
      durationMs: 30_000,
      magnitude: 0.15,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4105,
    classId: 4,
    slot: 8,
    displayName: 'Prisão de Gelo',
    unlock: { kind: 'level', level: 70 },
    cooldownMs: 33_000,
    skillCostType: 2,
    skillCost: 2500,
    attackAnimationMs: 1000,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 224,
    attackIds: [410501, 410502],
    damage: damage([[410502, 23_000, 500]]),
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'slow',
      durationMs: 10_000,
      magnitude: 0.5,
      areaRadiusPx: 112,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 7000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4109,
    classId: 4,
    slot: 9,
    displayName: 'Escudo de Aniquilação',
    unlock: { kind: 'level', level: 80 },
    cooldownMs: 28_000,
    skillCostType: 2,
    skillCost: 2160,
    attackAnimationMs: 1000,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 224,
    attackIds: [410901, 410902, 410903],
    damage: damage([[410903, 22_000, 500]]),
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'knockdown',
      durationMs: 1400,
      areaRadiusPx: 112,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 7500,
      pveChanceBasisPoints: 10_000,
      pvpChanceBasisPoints: 1000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4104,
    classId: 4,
    slot: 10,
    displayName: 'Escudo da Névoa Venenosa',
    unlock: { kind: 'level', level: 90 },
    cooldownMs: 40_000,
    skillCostType: 2,
    skillCost: 4800,
    attackAnimationMs: 1267,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 224,
    attackIds: [410401, 410402, 410403],
    damage: damage([[410403, 25_000, 500]]),
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'blind',
      durationMs: 5000,
      magnitude: 0.4,
      areaRadiusPx: 128,
      maxSecondaryTargets: 5,
      secondaryDamageBasisPoints: 7500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4110,
    classId: 4,
    slot: 11,
    displayName: 'Seta da Procura',
    unlock: { kind: 'level', level: 100 },
    cooldownMs: 38_000,
    skillCostType: 2,
    skillCost: 4000,
    attackAnimationMs: 1900,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 320,
    attackIds: [411000, 411001, 411002],
    damage: damage([[411002, 40_000, 800]]),
    roles: ['execution', 'single-target'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4112,
    classId: 4,
    slot: 12,
    displayName: 'Ocultação',
    unlock: { kind: 'level', level: 110 },
    cooldownMs: 60_000,
    skillCostType: 2,
    skillCost: 5500,
    attackAnimationMs: 600,
    hitCount: 0,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [411201, 411202],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: { effect: 'dodge-boost', subject: 'actor', durationMs: 2000, magnitude: 150 },
    additionalEffects: [
      { effect: 'damage-boost', subject: 'actor', durationMs: 2000, magnitude: 0.2 },
    ],
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
];

const LANCER_SKILLS: readonly Mir4SkillDef[] = [
  {
    skillId: 5201,
    classId: 5,
    slot: 1,
    displayName: 'Ataque Devastador',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 24_000,
    skillCostType: 2,
    skillCost: 1500,
    attackAnimationMs: 1833,
    hitCount: 6,
    requiresTarget: true,
    browserRangePx: 112,
    attackIds: [520101, 520102, 520103],
    damage: {
      components: [
        {
          attackId: 520102,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 12_000,
          levelUpCoefficient: 200,
          impactCount: 1,
        },
        {
          attackId: 520103,
          damageType: 2,
          damageAttribute: 2,
          coefficient: 16_000,
          levelUpCoefficient: 300,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 28_000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'slow',
      durationMs: 5000,
      magnitude: 0.25,
      areaRadiusPx: 112,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(5101),
    slot: 2,
    displayName: 'Lâmina Crescente',
    unlock: { kind: 'level', level: 10 },
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'knockdown',
      durationMs: 1000,
      areaRadiusPx: 116,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 7000,
      pveChanceBasisPoints: 10_000,
      pvpChanceBasisPoints: 1000,
    },
  },
  {
    ...extractedSkill(5104),
    slot: 3,
    displayName: 'Pontapé Nirvana',
    unlock: { kind: 'level', level: 20 },
    roles: ['debuff', 'single-target'],
    effect: {
      effect: 'knockdown',
      durationMs: 1000,
      pveChanceBasisPoints: 10_000,
      pvpChanceBasisPoints: 1000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(5301),
    slot: 4,
    displayName: 'Golpe Duplo',
    unlock: { kind: 'level', level: 30 },
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 116,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 7000,
    },
  },
  {
    skillId: 5401,
    classId: 5,
    slot: 5,
    displayName: 'Tempestade Arrebatadora',
    unlock: { kind: 'level', level: 40 },
    cooldownMs: 44_000,
    skillCostType: 2,
    skillCost: 3400,
    attackAnimationMs: 1067,
    hitCount: 6,
    requiresTarget: true,
    browserRangePx: 112,
    attackIds: [540101, 540102, 540103, 540104, 540105, 540106],
    damage: {
      components: [
        {
          attackId: 540105,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 9000,
          levelUpCoefficient: 200,
          impactCount: 3,
        },
        {
          attackId: 540106,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 20_000,
          levelUpCoefficient: 400,
          impactCount: 3,
        },
      ],
      aggregateCoefficient: 87_000,
      aggregateLevelUpCoefficient: 1800,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'blind',
      durationMs: 5000,
      magnitude: 0.3,
      areaRadiusPx: 132,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 6500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5102,
    classId: 5,
    slot: 6,
    displayName: 'Cauda do Dragão',
    unlock: { kind: 'level', level: 50 },
    cooldownMs: 29_000,
    skillCostType: 2,
    skillCost: 4000,
    attackAnimationMs: 1667,
    hitCount: 3,
    requiresTarget: true,
    browserRangePx: 128,
    attackIds: [510201, 510202, 510203, 510204],
    damage: damage([[510204, 36_000, 700]]),
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 112,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 8000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5103,
    classId: 5,
    slot: 7,
    displayName: 'Dragão Ascendente',
    unlock: { kind: 'level', level: 60 },
    cooldownMs: 25_000,
    skillCostType: 2,
    skillCost: 2500,
    attackAnimationMs: 2000,
    hitCount: 6,
    requiresTarget: true,
    browserRangePx: 112,
    attackIds: [510301, 510302, 510303, 510304],
    damage: {
      components: [
        {
          attackId: 510303,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 12_000,
          levelUpCoefficient: 200,
          impactCount: 3,
        },
        {
          attackId: 510304,
          damageType: 2,
          damageAttribute: 3,
          coefficient: 16_000,
          levelUpCoefficient: 300,
          impactCount: 3,
        },
      ],
      aggregateCoefficient: 84_000,
      aggregateLevelUpCoefficient: 1500,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'slow',
      durationMs: 5000,
      magnitude: 0.3,
      areaRadiusPx: 112,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 7500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5303,
    classId: 5,
    slot: 8,
    displayName: 'Ataque Esmagador',
    unlock: { kind: 'level', level: 70 },
    cooldownMs: 38_000,
    skillCostType: 2,
    skillCost: 4200,
    attackAnimationMs: 1760,
    hitCount: 4,
    requiresTarget: true,
    browserRangePx: 96,
    attackIds: [530301, 530302, 530303],
    damage: damage([[530303, 24_000, 500, 4]]),
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'knockdown',
      durationMs: 1400,
      areaRadiusPx: 80,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 8000,
      pveChanceBasisPoints: 10_000,
      pvpChanceBasisPoints: 1000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5403,
    classId: 5,
    slot: 9,
    displayName: 'Muralha de Vento',
    unlock: { kind: 'level', level: 80 },
    cooldownMs: 45_000,
    skillCostType: 2,
    skillCost: 3800,
    attackAnimationMs: 800,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 96,
    attackIds: [540301, 540302, 540303, 540304, 540305],
    damage: {
      components: [
        {
          attackId: 540304,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 14_000,
          levelUpCoefficient: 300,
          impactCount: 3,
        },
        {
          attackId: 540305,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 8000,
          levelUpCoefficient: 200,
          impactCount: 2,
        },
      ],
      aggregateCoefficient: 58_000,
      aggregateLevelUpCoefficient: 1300,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'survival-utility'],
    minTargets: 3,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 96,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 7500,
    },
    additionalEffects: [
      { effect: 'defense-boost', subject: 'actor', durationMs: 5000, magnitude: 0.2 },
    ],
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5205,
    classId: 5,
    slot: 10,
    displayName: 'Lança Penetrante',
    unlock: { kind: 'level', level: 90 },
    cooldownMs: 37_000,
    skillCostType: 2,
    skillCost: 4800,
    attackAnimationMs: 1440,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 272,
    attackIds: [520501, 520502, 520503],
    damage: {
      components: [
        {
          attackId: 520502,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 8000,
          levelUpCoefficient: 200,
          impactCount: 1,
        },
        {
          attackId: 520503,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 13_000,
          levelUpCoefficient: 300,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 21_000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'per-impact',
    },
    roles: ['debuff', 'single-target'],
    minTargets: null,
    effect: {
      effect: 'knockdown',
      durationMs: 1600,
      pveChanceBasisPoints: 10_000,
      pvpChanceBasisPoints: 1000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5304,
    classId: 5,
    slot: 11,
    displayName: 'Absorção',
    unlock: { kind: 'level', level: 100 },
    cooldownMs: 63_000,
    skillCostType: 2,
    skillCost: 2400,
    attackAnimationMs: 1260,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 112,
    attackIds: [530401],
    damage: damage([[530401, 11_000, 200]]),
    roles: ['survival-utility', 'single-target'],
    minTargets: null,
    effect: { effect: 'self-heal', subject: 'actor', healMaxHpBasisPoints: 1500 },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5202,
    classId: 5,
    slot: 12,
    displayName: 'Golpe Relâmpago',
    unlock: { kind: 'level', level: 110 },
    cooldownMs: 25_000,
    skillCostType: 2,
    skillCost: 4440,
    attackAnimationMs: 1200,
    hitCount: 2,
    requiresTarget: true,
    browserRangePx: 112,
    castRangePx: 320,
    attackIds: [520201, 520202],
    damage: damage([[520202, 28_000, 600, 2]]),
    roles: ['mobility', 'debuff', 'single-target'],
    minTargets: null,
    effect: {
      effect: 'knockdown',
      durationMs: 1200,
      chargeToTarget: true,
      pveChanceBasisPoints: 10_000,
      pvpChanceBasisPoints: 1000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
];

export const MIR4_SKILLS: readonly Mir4SkillDef[] = [
  ...WARRIOR_SKILLS,
  ...SORCERER_SKILLS,
  ...TAOIST_SKILLS,
  ...ARBALIST_SKILLS,
  ...LANCER_SKILLS,
  ...EXTRACTED_MIR4_SKILLS.filter(
    (skill) =>
      skill.classId !== 1 &&
      skill.classId !== 2 &&
      skill.classId !== 3 &&
      skill.classId !== 4 &&
      skill.classId !== 5,
  ),
];

const SKILL_INDEX = new Map(MIR4_SKILLS.map((skill) => [skill.skillId, skill]));
const CLASS_SKILL_INDEX = new Map<number, Mir4SkillDef[]>();
for (const skill of MIR4_SKILLS) {
  const skills = CLASS_SKILL_INDEX.get(skill.classId) ?? [];
  skills.push(skill);
  CLASS_SKILL_INDEX.set(skill.classId, skills);
}
for (const skills of CLASS_SKILL_INDEX.values()) skills.sort((a, b) => a.slot - b.slot);

export function mir4SkillById(skillId: number): Mir4SkillDef | null {
  return SKILL_INDEX.get(skillId) ?? null;
}

export function mir4SkillsForClass(classId: 1 | 2 | 3 | 4 | 5): readonly Mir4SkillDef[] {
  return CLASS_SKILL_INDEX.get(classId) ?? [];
}
