// Generated from the source project: server/mir4-combat-data.js (CLASS_CATALOG +
// SUPPLEMENTAL_SKILL_ROWS_BY_CLASS), server/mir4-skill-execution-contract-v1.js
// (ROLE_BY_SKILL + EFFECT_PROFILES), and display names from
// server/data/mir4-unified-skill-vfx-matrix-v2.json. DO NOT HAND-EDIT VALUES.
// The 7 authorial skills carry provenance authorial-v1; their combat rule is
// the matching policy in authorial_policies.ts (source decision: the authorial
// layer is canon where the native catalog stayed fail-closed).

import type { Mir4ClassId } from './classes';

export type Mir4SkillProvenance = 'native-catalog' | 'authorial-v1';

export interface Mir4SkillDamageComponent {
  attackId: number;
  /** 1 = physical, 2 = magic. */
  damageType: number;
  damageAttribute: number;
  coefficient: number;
  levelUpCoefficient: number;
  impactCount: number;
}

export interface Mir4SkillDamage {
  components: readonly Mir4SkillDamageComponent[];
  aggregateCoefficient: number;
  aggregateLevelUpCoefficient: number;
  allocationMode: 'per-impact' | 'row-total-impact-vector' | string;
}

export interface Mir4SkillEffect {
  effect: string;
  durationMs?: number;
  magnitude?: number;
  areaRadiusPx?: number;
  maxSecondaryTargets?: number;
  secondaryDamageBasisPoints?: number;
  pveChanceBasisPoints?: number;
  pvpChanceBasisPoints?: number;
  chanceModel?: string;
  sourceEffectIds?: readonly number[];
  /** Verbatim long tail the source effect profiles carry (subject, utility, ...). */
  [extra: string]: unknown;
}

export interface Mir4SkillDef {
  skillId: number;
  classId: Mir4ClassId;
  /** Deck slots 1..4; slot 5 is the level-unlocked supplemental skill. */
  slot: number;
  /** PT-BR source product name; the English i18n source is authored when the profile surfaces it. */
  displayName: string;
  unlock: { kind: 'initial-deck' } | { kind: 'level'; level: number };
  cooldownMs: number;
  skillCostType: number;
  skillCost: number;
  attackAnimationMs: number;
  hitCount: number;
  requiresTarget: boolean;
  browserRangePx: number;
  attackIds: readonly number[];
  /** null: the source ships no damage block for this row (supplemental rows). */
  damage: Mir4SkillDamage | null;
  /** Auto-battle rotation roles; the priority order is a Phase 3 system module. */
  roles: readonly string[];
  minTargets: number | null;
  effect: Mir4SkillEffect | null;
  provenance: Mir4SkillProvenance;
  /** Source runtime admission status, kept for traceability. */
  sourceRuntimeStatus: string | null;
}

/** Shared skill GCD (mir4-combat-data SKILL_GLOBAL_COOLDOWN_MS). */
export const MIR4_SKILL_GLOBAL_COOLDOWN_MS = 1000;

/**
 * Historical source skill-level caps (SKILL_LEVEL_CAPS_BY_CLASS), retained as
 * extraction provenance and for source-parity fixtures. Aeldrune gameplay no
 * longer consumes this table: its product rule is rank 1..15 in
 * sim/mir4/skill_progression.ts.
 */
export const MIR4_SKILL_LEVEL_CAPS: Readonly<Record<number, Readonly<Record<number, 2>>>> = {
  1: { 1102: 2, 1104: 2, 1304: 2, 1401: 2 },
  2: { 2101: 2, 2111: 2, 2501: 2, 2301: 2 },
  3: { 3101: 2 },
  4: { 4101: 2, 4106: 2, 4102: 2, 4103: 2 },
  5: { 5101: 2, 5301: 2 },
};

export const MIR4_SKILLS: readonly Mir4SkillDef[] = [
  {
    skillId: 1102,
    classId: 1,
    slot: 1,
    displayName: 'Golpe de Vácuo',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 25000,
    skillCostType: 2,
    skillCost: 1800,
    attackAnimationMs: 1500,
    hitCount: 3,
    requiresTarget: true,
    browserRangePx: 117,
    attackIds: [110201, 110202, 110203, 110204],
    damage: {
      components: [
        {
          attackId: 110202,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 8000,
          levelUpCoefficient: 160,
          impactCount: 1,
        },
        {
          attackId: 110203,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 8000,
          levelUpCoefficient: 160,
          impactCount: 1,
        },
        {
          attackId: 110204,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 9000,
          levelUpCoefficient: 180,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 25000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'per-impact',
    },
    roles: ['debuff', 'single-target'],
    minTargets: null,
    effect: {
      effect: 'stun',
      durationMs: 900,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 1104,
    classId: 1,
    slot: 2,
    displayName: 'Golpe Lacerante',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 16000,
    skillCostType: 2,
    skillCost: 2400,
    attackAnimationMs: 1539,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 117,
    attackIds: [110401, 110402],
    damage: {
      components: [
        {
          attackId: 110402,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 21000,
          levelUpCoefficient: 400,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 21000,
      aggregateLevelUpCoefficient: 400,
      allocationMode: 'per-impact',
    },
    roles: ['single-target'],
    minTargets: null,
    effect: {
      effect: 'knockdown',
      durationMs: 1200,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 1304,
    classId: 1,
    slot: 3,
    displayName: 'Placagem',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 23000,
    skillCostType: 2,
    skillCost: 4200,
    attackAnimationMs: 1200,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 117,
    attackIds: [130401, 130402],
    damage: {
      components: [
        {
          attackId: 130402,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 22000,
          levelUpCoefficient: 400,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 22000,
      aggregateLevelUpCoefficient: 400,
      allocationMode: 'per-impact',
    },
    roles: ['survival-utility', 'debuff'],
    minTargets: null,
    effect: {
      effect: 'defense-break',
      durationMs: 4500,
      magnitude: 0.12,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 1401,
    classId: 1,
    slot: 4,
    displayName: 'Esmagamento Terrestre',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 18000,
    skillCostType: 2,
    skillCost: 3000,
    attackAnimationMs: 1933,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 139,
    attackIds: [140101, 140102],
    damage: {
      components: [
        {
          attackId: 140102,
          damageType: 1,
          damageAttribute: 1,
          coefficient: 25000,
          levelUpCoefficient: 500,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 25000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'per-impact',
    },
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'knockdown',
      durationMs: 800,
      areaRadiusPx: 112,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 7000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 1501,
    classId: 1,
    slot: 5,
    displayName: 'Golpe de Vendaval',
    unlock: { kind: 'level', level: 5 },
    cooldownMs: 44000,
    skillCostType: 2,
    skillCost: 3400,
    attackAnimationMs: 2050,
    hitCount: 9,
    requiresTarget: true,
    browserRangePx: 104,
    attackIds: [150101, 150102, 150103, 150104, 150105],
    damage: null,
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'slow',
      durationMs: 3200,
      magnitude: 0.35,
      areaRadiusPx: 124,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 6500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'regional-authorial-v1',
  },
  {
    skillId: 2101,
    classId: 2,
    slot: 1,
    displayName: 'Raio Prismático',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 12000,
    skillCostType: 2,
    skillCost: 1600,
    attackAnimationMs: 1267,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 96,
    attackIds: [210101, 210102],
    damage: {
      components: [
        {
          attackId: 210102,
          damageType: 2,
          damageAttribute: 1,
          coefficient: 18700,
          levelUpCoefficient: 400,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 18700,
      aggregateLevelUpCoefficient: 400,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff', 'single-target'],
    minTargets: 3,
    effect: {
      effect: 'freeze',
      durationMs: 1400,
      areaRadiusPx: 104,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 2111,
    classId: 2,
    slot: 2,
    displayName: 'Lança de Brasa',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 15000,
    skillCostType: 2,
    skillCost: 2200,
    attackAnimationMs: 1330,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 96,
    attackIds: [211101, 211102],
    damage: {
      components: [
        {
          attackId: 211102,
          damageType: 2,
          damageAttribute: 2,
          coefficient: 17800,
          levelUpCoefficient: 400,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 17800,
      aggregateLevelUpCoefficient: 400,
      allocationMode: 'per-impact',
    },
    roles: ['debuff', 'single-target'],
    minTargets: null,
    effect: {
      effect: 'burn',
      durationMs: 4500,
      magnitude: 0.08,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 2501,
    classId: 2,
    slot: 3,
    displayName: 'Núcleo Evocado',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 18000,
    skillCostType: 2,
    skillCost: 3600,
    attackAnimationMs: 1267,
    hitCount: 6,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [250101, 250102],
    damage: null,
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'freeze',
      durationMs: 1800,
      areaRadiusPx: 128,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 6000,
    },
    provenance: 'authorial-v1',
    sourceRuntimeStatus: 'blocked-source-totem-timing-target-stat-ownership',
  },
  {
    skillId: 2301,
    classId: 2,
    slot: 4,
    displayName: 'Selo de Smite',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 27000,
    skillCostType: 2,
    skillCost: 4800,
    attackAnimationMs: 1570,
    hitCount: 5,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [230101],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: {
      effect: 'blind',
      durationMs: 4000,
      magnitude: 0.5,
    },
    provenance: 'authorial-v1',
    sourceRuntimeStatus: 'blocked-source-totem-target-buff-semantics',
  },
  {
    skillId: 2503,
    classId: 2,
    slot: 5,
    displayName: 'Escudo Mágico',
    unlock: { kind: 'level', level: 5 },
    cooldownMs: 52000,
    skillCostType: 2,
    skillCost: 2500,
    attackAnimationMs: 1267,
    hitCount: 3,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [250301, 250302, 250303],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: {
      effect: 'magic-shield',
      subject: 'actor',
      utility: 'shield',
      durationMs: 10000,
      magnitude: 0.22,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'regional-authorial-v1',
  },
  {
    skillId: 3506,
    classId: 3,
    slot: 1,
    displayName: 'Selo de Totem I',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 21000,
    skillCostType: 2,
    skillCost: 2600,
    attackAnimationMs: 2533,
    hitCount: 5,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [350601, 350602],
    damage: null,
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'root',
      durationMs: 1600,
      areaRadiusPx: 112,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6000,
    },
    provenance: 'authorial-v1',
    sourceRuntimeStatus: 'blocked-source-totem-timing',
  },
  {
    skillId: 3101,
    classId: 3,
    slot: 2,
    displayName: 'Sequência de Selo',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 16000,
    skillCostType: 2,
    skillCost: 1600,
    attackAnimationMs: 1833,
    hitCount: 7,
    requiresTarget: true,
    browserRangePx: 149,
    attackIds: [310101, 310102, 310103, 310104],
    damage: {
      components: [
        {
          attackId: 310101,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 5000,
          levelUpCoefficient: 100,
          impactCount: 1,
        },
        {
          attackId: 310102,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 5000,
          levelUpCoefficient: 100,
          impactCount: 2,
        },
        {
          attackId: 310103,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 5000,
          levelUpCoefficient: 100,
          impactCount: 2,
        },
        {
          attackId: 310104,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 5000,
          levelUpCoefficient: 100,
          impactCount: 2,
        },
      ],
      aggregateCoefficient: 20000,
      aggregateLevelUpCoefficient: 400,
      allocationMode: 'row-total-impact-vector',
    },
    roles: ['aoe', 'debuff', 'single-target'],
    minTargets: 3,
    effect: {
      effect: 'defense-break',
      durationMs: 4000,
      magnitude: 0.1,
      areaRadiusPx: 104,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 3301,
    classId: 3,
    slot: 3,
    displayName: 'Selo de Totem II',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 24000,
    skillCostType: 2,
    skillCost: 2400,
    attackAnimationMs: 1533,
    hitCount: 9,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [330101, 330102],
    damage: null,
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'slow',
      durationMs: 4200,
      magnitude: 0.35,
      areaRadiusPx: 116,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6000,
    },
    provenance: 'authorial-v1',
    sourceRuntimeStatus: 'blocked-source-totem-timing',
  },
  {
    skillId: 3104,
    classId: 3,
    slot: 4,
    displayName: 'Totem 1010',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 20000,
    skillCostType: 2,
    skillCost: 3840,
    attackAnimationMs: 1267,
    hitCount: 4,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [310401, 310402],
    damage: null,
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'stun',
      durationMs: 1400,
      areaRadiusPx: 124,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 6000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'blocked-native-gaps-and-durable-multi-target-totem-transaction',
  },
  {
    skillId: 3503,
    classId: 3,
    slot: 5,
    displayName: 'Cura',
    unlock: { kind: 'level', level: 5 },
    cooldownMs: 20000,
    skillCostType: 2,
    skillCost: 5200,
    attackAnimationMs: 1400,
    hitCount: 0,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [350301, 350302, 350303],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: {
      effect: 'heal-pulse',
      subject: 'actor',
      utility: 'heal',
      healMaxHpBasisPoints: 1800,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'regional-authorial-v1',
  },
  {
    skillId: 4101,
    classId: 4,
    slot: 1,
    displayName: 'Rajada 4101',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 12000,
    skillCostType: 2,
    skillCost: 1600,
    attackAnimationMs: 1500,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 256,
    attackIds: [410101, 410102, 410103, 410104, 410105, 410106],
    damage: {
      components: [
        {
          attackId: 410101,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 3300,
          levelUpCoefficient: 66,
          impactCount: 1,
        },
        {
          attackId: 410102,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 3300,
          levelUpCoefficient: 66,
          impactCount: 1,
        },
        {
          attackId: 410103,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 3300,
          levelUpCoefficient: 77,
          impactCount: 1,
        },
        {
          attackId: 410104,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 3300,
          levelUpCoefficient: 77,
          impactCount: 1,
        },
        {
          attackId: 410105,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4400,
          levelUpCoefficient: 77,
          impactCount: 1,
        },
        {
          attackId: 410106,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4400,
          levelUpCoefficient: 77,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 22000,
      aggregateLevelUpCoefficient: 440,
      allocationMode: 'per-impact',
    },
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'blind',
      durationMs: 3500,
      magnitude: 0.45,
      areaRadiusPx: 112,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 4106,
    classId: 4,
    slot: 2,
    displayName: 'Investida 4106',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 20000,
    skillCostType: 2,
    skillCost: 2600,
    attackAnimationMs: 1000,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 299,
    attackIds: [410601, 410602],
    damage: {
      components: [
        {
          attackId: 410602,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 17000,
          levelUpCoefficient: 400,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 17000,
      aggregateLevelUpCoefficient: 400,
      allocationMode: 'per-impact',
    },
    roles: ['survival-utility', 'single-target'],
    minTargets: null,
    effect: {
      effect: 'stun',
      durationMs: 2000,
      pveChanceBasisPoints: 10000,
      pvpChanceBasisPoints: 1000,
      chanceModel: 'base-plus-stun-success-minus-stun-resistance',
      sourceEffectIds: [40010, 10522, 10122],
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 4102,
    classId: 4,
    slot: 3,
    displayName: 'Sequência 4102',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 22000,
    skillCostType: 2,
    skillCost: 2500,
    attackAnimationMs: 1467,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 149,
    attackIds: [410201, 410202, 410203, 410204, 410205],
    damage: {
      components: [
        {
          attackId: 410201,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4000,
          levelUpCoefficient: 100,
          impactCount: 1,
        },
        {
          attackId: 410202,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 5000,
          levelUpCoefficient: 100,
          impactCount: 1,
        },
        {
          attackId: 410203,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 5000,
          levelUpCoefficient: 100,
          impactCount: 1,
        },
        {
          attackId: 410204,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 5000,
          levelUpCoefficient: 100,
          impactCount: 1,
        },
        {
          attackId: 410205,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 5000,
          levelUpCoefficient: 100,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 24000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'per-impact',
    },
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'slow',
      durationMs: 3500,
      magnitude: 0.3,
      areaRadiusPx: 106,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 4103,
    classId: 4,
    slot: 4,
    displayName: 'Eco Gêmeo',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 26000,
    skillCostType: 2,
    skillCost: 2100,
    attackAnimationMs: 1100,
    hitCount: 5,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [410301, 410302, 410303],
    damage: null,
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'blind',
      durationMs: 5000,
      magnitude: 0.6,
      areaRadiusPx: 120,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 5500,
    },
    provenance: 'authorial-v1',
    sourceRuntimeStatus: 'blocked-source-totem-damage-composition',
  },
  {
    skillId: 4107,
    classId: 4,
    slot: 5,
    displayName: 'Seta do Clarão',
    unlock: { kind: 'level', level: 5 },
    cooldownMs: 35000,
    skillCostType: 2,
    skillCost: 4000,
    attackAnimationMs: 1000,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 144,
    attackIds: [410701, 410702],
    damage: null,
    roles: ['aoe', 'debuff'],
    minTargets: 3,
    effect: {
      effect: 'blind',
      durationMs: 3200,
      magnitude: 0.45,
      areaRadiusPx: 108,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'regional-authorial-v1',
  },
  {
    skillId: 5201,
    classId: 5,
    slot: 1,
    displayName: 'Golpe 5201',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 24000,
    skillCostType: 2,
    skillCost: 1500,
    attackAnimationMs: 1833,
    hitCount: 6,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [520101, 520102, 520103],
    damage: null,
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'stun',
      durationMs: 1100,
      areaRadiusPx: 112,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 6500,
    },
    provenance: 'authorial-v1',
    sourceRuntimeStatus: 'blocked-source-damage-type-3',
  },
  {
    skillId: 5101,
    classId: 5,
    slot: 2,
    displayName: 'Estocada 5101',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 16000,
    skillCostType: 2,
    skillCost: 2000,
    attackAnimationMs: 1967,
    hitCount: 3,
    requiresTarget: true,
    browserRangePx: 139,
    attackIds: [510101, 510102],
    damage: {
      components: [
        {
          attackId: 510101,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 13000,
          levelUpCoefficient: 260,
          impactCount: 1,
        },
        {
          attackId: 510102,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 6000,
          levelUpCoefficient: 140,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 19000,
      aggregateLevelUpCoefficient: 400,
      allocationMode: 'per-impact',
    },
    roles: ['single-target'],
    minTargets: null,
    effect: {
      effect: 'knockdown',
      durationMs: 1000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 5104,
    classId: 5,
    slot: 3,
    displayName: 'Varredura 5104',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 18000,
    skillCostType: 2,
    skillCost: 1800,
    attackAnimationMs: 1233,
    hitCount: 2,
    requiresTarget: true,
    browserRangePx: 320,
    attackIds: [510401, 510402],
    damage: {
      components: [
        {
          attackId: 510402,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 16000,
          levelUpCoefficient: 300,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 16000,
      aggregateLevelUpCoefficient: 300,
      allocationMode: 'per-impact',
    },
    roles: ['execution'],
    minTargets: null,
    effect: {
      effect: 'defense-break',
      durationMs: 4500,
      magnitude: 0.14,
    },
    provenance: 'authorial-v1',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 5301,
    classId: 5,
    slot: 4,
    displayName: 'Cadeia 5301',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 24000,
    skillCostType: 2,
    skillCost: 3300,
    attackAnimationMs: 1900,
    hitCount: 3,
    requiresTarget: true,
    browserRangePx: 117,
    attackIds: [530101, 530102, 530103],
    damage: {
      components: [
        {
          attackId: 530101,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 9000,
          levelUpCoefficient: 180,
          impactCount: 1,
        },
        {
          attackId: 530102,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 8000,
          levelUpCoefficient: 160,
          impactCount: 1,
        },
        {
          attackId: 530103,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 8000,
          levelUpCoefficient: 160,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 25000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'per-impact',
    },
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'stun',
      durationMs: 900,
      areaRadiusPx: 116,
      maxSecondaryTargets: 3,
      secondaryDamageBasisPoints: 7000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'supported',
  },
  {
    skillId: 5401,
    classId: 5,
    slot: 5,
    displayName: 'Tempestade Arrebatadora',
    unlock: { kind: 'level', level: 5 },
    cooldownMs: 44000,
    skillCostType: 2,
    skillCost: 3400,
    attackAnimationMs: 1067,
    hitCount: 6,
    requiresTarget: true,
    browserRangePx: 112,
    attackIds: [540101, 540102, 540103, 540104, 540105, 540106],
    damage: null,
    roles: ['aoe'],
    minTargets: 3,
    effect: {
      effect: 'knockdown',
      durationMs: 1000,
      areaRadiusPx: 132,
      maxSecondaryTargets: 4,
      secondaryDamageBasisPoints: 6500,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'regional-authorial-v1',
  },
];

const SKILL_INDEX = new Map<number, Mir4SkillDef>();
const CLASS_SKILL_INDEX = new Map<number, Mir4SkillDef[]>();
for (const skill of MIR4_SKILLS) {
  SKILL_INDEX.set(skill.skillId, skill);
  const list = CLASS_SKILL_INDEX.get(skill.classId) ?? [];
  list.push(skill);
  CLASS_SKILL_INDEX.set(skill.classId, list);
}

export function mir4SkillById(skillId: number): Mir4SkillDef | null {
  return SKILL_INDEX.get(skillId) ?? null;
}

/** The class kit in slot order (slots 1..5). */
export function mir4SkillsForClass(classId: Mir4ClassId): readonly Mir4SkillDef[] {
  return CLASS_SKILL_INDEX.get(classId) ?? [];
}
