// Aeldrune's gameplay catalogue. The generated extraction in skills.ts stays
// immutable; this layer composes that evidence with complete class kits from
// the official MIR4 client tables without rewriting the imported snapshot.

import { MIR4_NATIVE_SORCERER_SKILL_ACTIONS } from './native_skill_actions_sorcerer';
import {
  MIR4_SKILLS as EXTRACTED_MIR4_SKILLS,
  type Mir4SkillDef as ExtractedMir4SkillDef,
  type Mir4SkillEffect as ExtractedMir4SkillEffect,
} from './skills';

export interface Mir4SkillEffect extends ExtractedMir4SkillEffect {
  /** Entity that receives this effect. Hostile effects default to target. */
  subject?: 'actor' | 'target' | 'party';
  /** Radius used by party heals and party-wide support effects. */
  partyRadiusPx?: number;
  /** Deterministic cap for allies admitted by a party pulse. */
  maxPartyTargets?: number;
  /** Base native Spell ATK coefficient for one healing pulse, in basis points. */
  healSpellAttackBasisPoints?: number;
  /** Per-rank increase to the native healing coefficient, in basis points. */
  healSpellAttackLevelUpBasisPoints?: number;
  /** Flat healing added after the Spell ATK contribution to each pulse. */
  healFlat?: number;
  /** Number of one-second native healing pulses. */
  healPulseCount?: number;
  /** Milliseconds between native healing pulses. */
  healPulseIntervalMs?: number;
  /** Move the actor to the target before resolving the skill. */
  chargeToTarget?: boolean;
  /** Pull every enemy hit toward the actor after contact. */
  pullToActor?: boolean;
  /** Push every enemy hit away from the actor after contact. */
  pushFromActorYards?: number;
  /** Center used by circular secondary-target selection. Legacy rows default to target. */
  areaOrigin?: 'actor' | 'target' | 'forward';
  /** Spatial footprint used to admit secondary targets. Legacy rows default to circle. */
  areaShape?: 'circle' | 'frontal-strip';
  /** Distance from the actor to a forward-centered circle. */
  areaForwardOffsetPx?: number;
  /** Forward reach of a strip-shaped attack. */
  areaLengthPx?: number;
  /** Full lateral width of a strip-shaped attack. */
  areaWidthPx?: number;
  /** Step-up magnitude used from rank 10 onward by an already-supported effect kind. */
  rank10Magnitude?: number;
}

export interface Mir4SkillDef extends Omit<ExtractedMir4SkillDef, 'effect'> {
  effect: Mir4SkillEffect | null;
  /** Extra effects let one official skill damage enemies and buff its caster. */
  additionalEffects?: readonly Mir4SkillEffect[];
  /** Skill-specific admission range, used by gap closers. */
  castRangePx?: number;
  /** Damage-contact offsets recovered from the official SKILL_ATTACK rows. */
  impactOffsetsMs?: readonly number[];
}

function extractedSkill(skillId: number): Mir4SkillDef {
  const skill = EXTRACTED_MIR4_SKILLS.find((candidate) => candidate.skillId === skillId);
  if (!skill) throw new Error(`Missing extracted MIR4 skill ${skillId}`);
  return skill;
}

function extractedEffect(skillId: number): Mir4SkillEffect {
  const effect = extractedSkill(skillId).effect;
  if (!effect) throw new Error(`Missing extracted MIR4 skill effect ${skillId}`);
  return effect;
}

function damage(
  components: readonly [number, number, number, number?][],
  damageType = 1,
  damageAttribute = 0,
  allocationMode: NonNullable<Mir4SkillDef['damage']>['allocationMode'] = 'per-impact',
): Mir4SkillDef['damage'] {
  return {
    components: components.map(([attackId, coefficient, levelUpCoefficient, impactCount]) => ({
      attackId,
      damageType,
      damageAttribute,
      coefficient,
      levelUpCoefficient,
      impactCount: impactCount ?? 1,
    })),
    aggregateCoefficient: components.reduce((total, component) => total + component[1], 0),
    aggregateLevelUpCoefficient: components.reduce((total, component) => total + component[2], 0),
    allocationMode,
  };
}

const SORCERER_ACTION_BY_SKILL_ID = new Map(
  MIR4_NATIVE_SORCERER_SKILL_ACTIONS.map((action) => [action.skillId, action]),
);

interface NativeSorcererSkillOptions {
  readonly slot: number;
  readonly displayName: string;
  readonly unlock: Mir4SkillDef['unlock'];
  readonly roles: Mir4SkillDef['roles'];
  readonly allocationMode?: NonNullable<Mir4SkillDef['damage']>['allocationMode'];
  readonly impactOffsetsMs?: readonly number[];
  /**
   * Some cooked Sorcerer actions carry Targeting=true while their admitted
   * attack geometry is an actor-centred area. Keep that compatibility
   * interpretation explicit per reviewed skill instead of treating the raw
   * UI flag as a mandatory entity target.
   */
  readonly requiresTarget?: boolean;
  /** Compatibility-only behavior retained until that skill's own review. */
  readonly minTargets?: Mir4SkillDef['minTargets'];
  readonly effect?: Mir4SkillDef['effect'];
  readonly additionalEffects?: Mir4SkillDef['additionalEffects'];
}

/**
 * Project the shared Sorcerer runtime header and direct contacts from the
 * recovered SKILL/SKILL_ATTACK action instead of maintaining a second copy.
 * Buffs, projectiles, totems and rank passives remain fail-closed elsewhere
 * until their consumers are individually homologated.
 */
function nativeSorcererSkill(skillId: number, options: NativeSorcererSkillOptions): Mir4SkillDef {
  const action = SORCERER_ACTION_BY_SKILL_ID.get(skillId);
  if (!action) throw new Error(`Missing native Sorcerer action ${skillId}`);
  const damageRows = action.rows.filter((row) => row.damage.type !== 0);
  const firstRow = action.rows[0];
  if (!firstRow) throw new Error(`Missing native Sorcerer action row ${skillId}`);
  const directDamage =
    damageRows.length === 0
      ? null
      : {
          components: damageRows.map((row) => ({
            attackId: row.attackId,
            damageType: row.damage.type,
            damageAttribute: row.damage.attribute,
            coefficient: row.damage.coefficient,
            levelUpCoefficient: row.damage.levelUpCoefficient,
            impactCount: row.impactOffsetsMs.length,
          })),
          aggregateCoefficient: damageRows.reduce(
            (total, row) => total + row.damage.coefficient,
            0,
          ),
          aggregateLevelUpCoefficient: damageRows.reduce(
            (total, row) => total + row.damage.levelUpCoefficient,
            0,
          ),
          allocationMode: options.allocationMode ?? ('per-impact' as const),
        };
  return {
    skillId,
    classId: 2,
    slot: options.slot,
    displayName: options.displayName,
    unlock: options.unlock,
    cooldownMs: action.cooldownMs,
    skillCostType: action.skillCostType,
    skillCost: action.skillCost,
    attackAnimationMs: action.attackAnimationMs,
    hitCount: action.hitCount,
    impactOffsetsMs: options.impactOffsetsMs ?? damageRows.flatMap((row) => row.impactOffsetsMs),
    requiresTarget: options.requiresTarget ?? action.targeting,
    browserRangePx:
      (options.requiresTarget ?? action.targeting)
        ? (firstRow.targetDistance.nativeMax * 16) / 100
        : 0,
    attackIds: action.rows.map((row) => row.attackId),
    damage: directDamage,
    roles: options.roles,
    minTargets: options.minTargets ?? null,
    effect: options.effect ?? null,
    ...(options.additionalEffects ? { additionalEffects: options.additionalEffects } : {}),
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  };
}

const WARRIOR_SKILLS: readonly Mir4SkillDef[] = [
  {
    ...extractedSkill(1102),
    slot: 1,
    displayName: 'Corte do Vazio',
    unlock: { kind: 'initial-deck' },
    // Native rows 110202..110204 request the generic Hit/Hit01 reaction for
    // 200 ms. They are not Stun rows (Stun is CrowdControlType 2), so the
    // imported 900 ms hard-control approximation must not enter gameplay.
    roles: ['aoe'],
    effect: null,
    impactOffsetsMs: [520, 699, 900],
    sourceRuntimeStatus: 'authorial-runtime-unhomologated',
  },
  {
    skillId: 1302,
    classId: 1,
    slot: 6,
    displayName: 'Rugido de Leão',
    unlock: { kind: 'level', level: 8 },
    cooldownMs: 39_000,
    skillCostType: 2,
    skillCost: 2640,
    attackAnimationMs: 1300,
    hitCount: 1,
    impactOffsetsMs: [500, 600],
    requiresTarget: true,
    browserRangePx: 117,
    attackIds: [130201, 130202, 130203],
    damage: damage([
      [130202, 11_000, 270],
      [130203, 2_000, 30],
    ]),
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 1301,
    classId: 1,
    slot: 7,
    displayName: 'Riposta',
    unlock: { kind: 'level', level: 16 },
    cooldownMs: 25_000,
    skillCostType: 2,
    skillCost: 3840,
    attackAnimationMs: 2150,
    hitCount: 1,
    impactOffsetsMs: [1240],
    requiresTarget: true,
    browserRangePx: 117,
    attackIds: [130101, 130102],
    damage: damage([[130102, 25_200, 500]]),
    roles: ['aoe', 'survival-utility'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 1101,
    classId: 1,
    slot: 10,
    displayName: 'Fúria',
    unlock: { kind: 'level', level: 40 },
    cooldownMs: 48_000,
    skillCostType: 2,
    skillCost: 5000,
    attackAnimationMs: 1367,
    hitCount: 1,
    impactOffsetsMs: [20, 650],
    requiresTarget: true,
    browserRangePx: 117,
    attackIds: [110100, 110101],
    damage: damage([
      [110100, 8000, 200],
      [110101, 8000, 200],
    ]),
    roles: ['aoe', 'survival-utility'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 1103,
    classId: 1,
    slot: 11,
    displayName: 'Investida Bárbara',
    unlock: { kind: 'level', level: 48 },
    cooldownMs: 33_000,
    skillCostType: 2,
    skillCost: 1700,
    attackAnimationMs: 1667,
    hitCount: 4,
    impactOffsetsMs: [550, 1100],
    requiresTarget: true,
    browserRangePx: 117,
    castRangePx: 320,
    attackIds: [110105, 110106, 110107],
    damage: damage([
      [110106, 10_000, 220],
      [110107, 11_000, 230],
    ]),
    roles: ['execution', 'mobility'],
    minTargets: null,
    effect: {
      effect: 'knockdown',
      durationMs: 3000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(1104),
    slot: 2,
    displayName: 'Corte Divisor',
    unlock: { kind: 'initial-deck' },
    impactOffsetsMs: [490],
    roles: ['aoe', 'mobility', 'debuff'],
    effect: {
      ...extractedEffect(1104),
      durationMs: 3_000,
      areaOrigin: 'actor',
      areaShape: 'frontal-strip',
      areaLengthPx: 112,
      areaWidthPx: 88,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 10_000,
    },
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(1501),
    slot: 5,
    displayName: 'Corte Vendaval',
    unlock: { kind: 'level', level: 5 },
    impactOffsetsMs: [20, 225, 375, 540, 640, 840, 900, 1050, 1275],
    damage: damage(
      [
        [150101, 9000, 180, 3],
        [150102, 8000, 160, 2],
        [150103, 8000, 160, 2],
        [150104, 6000, 150],
        [150105, 7000, 150],
      ],
      1,
      0,
      'row-total-impact-vector',
    ),
    minTargets: null,
    effect: null,
  },
  {
    skillId: 1201,
    classId: 1,
    slot: 8,
    displayName: 'Grilhão de Ferro',
    unlock: { kind: 'level', level: 24 },
    cooldownMs: 40_000,
    skillCostType: 2,
    skillCost: 1920,
    attackAnimationMs: 2833,
    hitCount: 3,
    impactOffsetsMs: [500, 850, 1500],
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [120101, 120102, 120103],
    damage: damage([
      [120101, 7000, 130],
      [120102, 7000, 130],
      [120103, 8000, 140],
    ]),
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 1601,
    classId: 1,
    slot: 9,
    displayName: 'Golpe Crescente',
    unlock: { kind: 'level', level: 32 },
    cooldownMs: 19_000,
    skillCostType: 2,
    skillCost: 1900,
    attackAnimationMs: 1533,
    hitCount: 1,
    impactOffsetsMs: [750],
    requiresTarget: true,
    browserRangePx: 160,
    attackIds: [160101, 160102, 160103],
    damage: damage([[160103, 18_000, 400]]),
    roles: ['aoe'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(1304),
    slot: 3,
    displayName: 'Choque Corporal',
    unlock: { kind: 'initial-deck' },
    impactOffsetsMs: [520],
    roles: ['aoe', 'mobility', 'debuff'],
    effect: {
      effect: 'knockdown',
      durationMs: 3_000,
      areaOrigin: 'actor',
      areaShape: 'frontal-strip',
      areaLengthPx: 128,
      areaWidthPx: 80,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 10_000,
      chargeToTarget: true,
    },
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(1401),
    slot: 4,
    displayName: 'Esmagamento Terrestre',
    unlock: { kind: 'initial-deck' },
    impactOffsetsMs: [610],
    roles: ['aoe', 'mobility', 'debuff'],
    minTargets: null,
    effect: {
      effect: 'knockdown',
      durationMs: 2_490,
    },
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 1502,
    classId: 1,
    slot: 12,
    displayName: 'Postura Inquebrável',
    unlock: { kind: 'level', level: 56 },
    cooldownMs: 52_000,
    skillCostType: 2,
    skillCost: 6400,
    attackAnimationMs: 1167,
    hitCount: 1,
    impactOffsetsMs: [240],
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [150201, 150202],
    damage: damage([[150202, 8000, 200]]),
    roles: ['aoe', 'survival-utility'],
    minTargets: null,
    effect: {
      effect: 'area-impact',
      areaRadiusPx: 112,
      maxSecondaryTargets: 7,
      secondaryDamageBasisPoints: 10_000,
    },
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
];

const SORCERER_SKILLS: readonly Mir4SkillDef[] = [
  nativeSorcererSkill(2101, {
    slot: 1,
    displayName: 'Esfera Flamejante',
    unlock: { kind: 'initial-deck' },
    roles: ['aoe', 'debuff', 'single-target'],
  }),
  nativeSorcererSkill(2111, {
    slot: 2,
    displayName: 'Esfera Gelada',
    unlock: { kind: 'initial-deck' },
    roles: ['aoe', 'debuff', 'single-target'],
  }),
  nativeSorcererSkill(2501, {
    slot: 3,
    displayName: 'Vórtice das Trevas',
    unlock: { kind: 'initial-deck' },
    roles: ['aoe', 'debuff'],
  }),
  nativeSorcererSkill(2301, {
    slot: 4,
    displayName: 'Tempestade de Relâmpagos',
    unlock: { kind: 'initial-deck' },
    roles: ['aoe', 'debuff'],
  }),
  {
    ...nativeSorcererSkill(2503, {
      slot: 5,
      displayName: 'Escudo Mágico',
      unlock: { kind: 'level', level: 5 },
      roles: ['aoe', 'survival-utility'],
    }),
    effect: {
      effect: 'magic-shield',
      subject: 'actor',
      utility: 'shield',
    },
  },
  nativeSorcererSkill(2203, {
    slot: 6,
    displayName: 'Nevão',
    unlock: { kind: 'level', level: 8 },
    roles: ['aoe'],
    impactOffsetsMs: [1600],
  }),
  nativeSorcererSkill(2303, {
    slot: 7,
    displayName: 'Cadeia de Relâmpagos',
    unlock: { kind: 'level', level: 16 },
    roles: ['aoe', 'single-target'],
    allocationMode: 'per-impact',
  }),
  nativeSorcererSkill(2201, {
    slot: 8,
    displayName: 'Coluna de Chamas',
    unlock: { kind: 'level', level: 24 },
    roles: ['aoe', 'debuff'],
    allocationMode: 'row-total-impact-vector',
    requiresTarget: false,
  }),
  nativeSorcererSkill(2502, {
    slot: 9,
    displayName: 'Devoração da Alma',
    unlock: { kind: 'level', level: 32 },
    roles: ['aoe'],
  }),
  nativeSorcererSkill(2103, {
    slot: 10,
    displayName: 'Imolar',
    unlock: { kind: 'level', level: 40 },
    roles: ['aoe', 'debuff'],
    allocationMode: 'row-total-impact-vector',
  }),
  nativeSorcererSkill(2204, {
    slot: 11,
    displayName: 'Abraço da Fênix',
    unlock: { kind: 'level', level: 48 },
    roles: ['survival-utility'],
  }),
  nativeSorcererSkill(2202, {
    slot: 12,
    displayName: 'Bloqueio de Gelo',
    unlock: { kind: 'level', level: 56 },
    roles: ['aoe', 'survival-utility'],
    requiresTarget: false,
  }),
];

const TAOIST_SKILLS: readonly Mir4SkillDef[] = [
  {
    skillId: 3506,
    classId: 3,
    slot: 1,
    displayName: 'Onda Lunar',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 21_000,
    skillCostType: 2,
    skillCost: 2600,
    attackAnimationMs: 2533,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 128,
    attackIds: [350601, 350602],
    impactOffsetsMs: [732],
    damage: damage([[350602, 6000, 100, 1]], 2, 5),
    roles: ['aoe', 'single-target'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3101,
    classId: 3,
    slot: 2,
    displayName: 'Espada de Raio Solar',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 16_000,
    skillCostType: 2,
    skillCost: 1600,
    attackAnimationMs: 1833,
    hitCount: 7,
    requiresTarget: true,
    browserRangePx: 112,
    attackIds: [310101, 310102, 310103, 310104],
    impactOffsetsMs: [380, 550, 750, 950, 1150, 1350, 1550],
    damage: damage(
      [
        [310101, 5000, 100],
        [310102, 5000, 100, 2],
        [310103, 5000, 100, 2],
        [310104, 5000, 100, 2],
      ],
      1,
      0,
      'row-total-impact-vector',
    ),
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3301,
    classId: 3,
    slot: 3,
    displayName: 'Esfera Lunar',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 24_000,
    skillCostType: 2,
    skillCost: 2400,
    attackAnimationMs: 1533,
    hitCount: 9,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [330101, 330102],
    impactOffsetsMs: [900],
    damage: damage([[330102, 3500, 60]], 2, 5),
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3104,
    classId: 3,
    slot: 4,
    displayName: 'Chuva de Lâminas',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 20_000,
    skillCostType: 2,
    skillCost: 3840,
    attackAnimationMs: 1267,
    hitCount: 4,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [310401, 310402],
    impactOffsetsMs: [1000],
    damage: {
      components: [
        {
          attackId: 310402,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 6000,
          levelUpCoefficient: 130,
          impactCount: 1,
        },
        {
          attackId: 310402,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 3000,
          levelUpCoefficient: 60,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 9000,
      aggregateLevelUpCoefficient: 190,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(3503),
    slot: 5,
    displayName: 'Cura',
    unlock: { kind: 'level', level: 5 },
    effect: {
      effect: 'heal-pulse',
      subject: 'party',
      utility: 'heal',
      healSpellAttackBasisPoints: 3600,
      healSpellAttackLevelUpBasisPoints: 200,
      healFlat: 100,
      healPulseCount: 5,
      healPulseIntervalMs: 1000,
      partyRadiusPx: 480,
      maxPartyTargets: 5,
    },
  },
  {
    skillId: 3103,
    classId: 3,
    slot: 6,
    displayName: 'Lâminas Perfurantes',
    unlock: { kind: 'level', level: 8 },
    cooldownMs: 20_000,
    skillCostType: 2,
    skillCost: 1500,
    attackAnimationMs: 1767,
    hitCount: 6,
    impactOffsetsMs: [720, 850, 980, 1120, 1250],
    requiresTarget: true,
    browserRangePx: 176,
    attackIds: [310301, 310302, 310303],
    damage: damage(
      [
        [310302, 10_000, 200, 3],
        [310303, 10_000, 200, 2],
      ],
      1,
      0,
      'row-total-impact-vector',
    ),
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3501,
    classId: 3,
    slot: 7,
    displayName: 'Círculo do Guardião',
    unlock: { kind: 'level', level: 16 },
    cooldownMs: 46_000,
    skillCostType: 2,
    skillCost: 2640,
    attackAnimationMs: 1000,
    hitCount: 1,
    impactOffsetsMs: [400],
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [350101, 350102, 350103],
    damage: damage([[350102, 6000, 100]], 2),
    roles: ['aoe', 'survival-utility'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3201,
    classId: 3,
    slot: 8,
    displayName: 'Tai Chi',
    unlock: { kind: 'level', level: 24 },
    cooldownMs: 35_000,
    skillCostType: 2,
    skillCost: 3000,
    attackAnimationMs: 2067,
    hitCount: 6,
    impactOffsetsMs: [20, 490, 690, 850, 1000, 1340],
    requiresTarget: true,
    browserRangePx: 0,
    attackIds: [320101, 320102, 320103, 320104, 320105, 320106, 320107],
    damage: {
      components: [
        ...[320101, 320102, 320103, 320104].flatMap((attackId) => [
          {
            attackId,
            damageType: 1 as const,
            damageAttribute: 0,
            coefficient: 4000,
            levelUpCoefficient: 80,
            impactCount: 1,
          },
          {
            attackId,
            damageType: 2 as const,
            damageAttribute: 0,
            coefficient: 1000,
            levelUpCoefficient: 20,
            impactCount: 1,
          },
        ]),
        ...[320105, 320106].flatMap((attackId) => [
          {
            attackId,
            damageType: 1 as const,
            damageAttribute: 0,
            coefficient: 4000,
            levelUpCoefficient: 90,
            impactCount: 1,
          },
          {
            attackId,
            damageType: 2 as const,
            damageAttribute: 0,
            coefficient: 2000,
            levelUpCoefficient: 40,
            impactCount: 1,
          },
        ]),
      ],
      aggregateCoefficient: 32_000,
      aggregateLevelUpCoefficient: 660,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3505,
    classId: 3,
    slot: 9,
    displayName: 'Amuleto Explosivo',
    unlock: { kind: 'level', level: 32 },
    cooldownMs: 28_000,
    skillCostType: 2,
    skillCost: 4000,
    attackAnimationMs: 1533,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [350501, 350502],
    impactOffsetsMs: [1080],
    damage: damage([[350502, 24_000, 500]], 2, 6),
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3203,
    classId: 3,
    slot: 10,
    displayName: 'Golpe Esvoaçante',
    unlock: { kind: 'level', level: 40 },
    cooldownMs: 31_000,
    skillCostType: 2,
    skillCost: 2800,
    attackAnimationMs: 1700,
    hitCount: 9,
    requiresTarget: true,
    browserRangePx: 112,
    attackIds: [320301, 320302, 320303],
    impactOffsetsMs: [350, 500, 650, 800, 950, 1100, 1250, 1450, 1650],
    damage: {
      components: [
        {
          attackId: 320301,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 9000,
          levelUpCoefficient: 200,
          impactCount: 3,
        },
        {
          attackId: 320301,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 3000,
          levelUpCoefficient: 60,
          impactCount: 3,
        },
        ...[320302, 320303].flatMap((attackId) => [
          {
            attackId,
            damageType: 1 as const,
            damageAttribute: 0,
            coefficient: 10_000,
            levelUpCoefficient: 200,
            impactCount: 3,
          },
          {
            attackId,
            damageType: 2 as const,
            damageAttribute: 0,
            coefficient: 4_000,
            levelUpCoefficient: 70,
            impactCount: 3,
          },
        ]),
      ],
      aggregateCoefficient: 40_000,
      aggregateLevelUpCoefficient: 800,
      allocationMode: 'row-total-impact-vector',
    },
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3404,
    classId: 3,
    slot: 11,
    displayName: 'Círculo de Expulsão',
    unlock: { kind: 'level', level: 48 },
    cooldownMs: 46_000,
    skillCostType: 2,
    skillCost: 3000,
    attackAnimationMs: 1000,
    hitCount: 0,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [340401],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 3504,
    classId: 3,
    slot: 12,
    displayName: 'Cura Maior',
    unlock: { kind: 'level', level: 56 },
    cooldownMs: 46_000,
    skillCostType: 2,
    skillCost: 5880,
    attackAnimationMs: 1640,
    hitCount: 0,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [350401, 350402, 350403, 350404],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
];

const ARBALIST_SKILLS: readonly Mir4SkillDef[] = [
  {
    ...extractedSkill(4101),
    slot: 1,
    displayName: 'Tiro Rápido',
    unlock: { kind: 'initial-deck' },
    roles: ['aoe', 'single-target'],
    impactOffsetsMs: [113, 213, 313, 413, 519, 619, 719, 819, 913, 1013, 1116, 1216],
    damage: {
      components: extractedSkill(4101).damage!.components.map((component) => ({
        ...component,
        impactCount: 2,
      })),
      aggregateCoefficient: 22_000,
      aggregateLevelUpCoefficient: 440,
      allocationMode: 'row-total-final-contact',
    },
    minTargets: null,
    effect: null,
  },
  {
    ...extractedSkill(4106),
    slot: 2,
    displayName: 'Vendaval de Golpe de Dor',
    unlock: { kind: 'initial-deck' },
    browserRangePx: 192,
    attackIds: [410601, 410602, 410603],
    impactOffsetsMs: [450],
    damage: {
      components: [
        {
          attackId: 410602,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 17_000,
          levelUpCoefficient: 400,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 17_000,
      aggregateLevelUpCoefficient: 400,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'mobility', 'control'],
    minTargets: null,
    effect: null,
  },
  {
    ...extractedSkill(4102),
    slot: 3,
    displayName: 'Seta da Ilusão',
    unlock: { kind: 'initial-deck' },
    browserRangePx: 112,
    attackIds: [410201, 410202, 410203, 410204, 410205],
    impactOffsetsMs: [20, 400, 600, 800, 1000],
    damage: {
      components: [
        {
          attackId: 410201,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4_000,
          levelUpCoefficient: 100,
          impactCount: 1,
        },
        ...[410202, 410203, 410204, 410205].map((attackId) => ({
          attackId,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 5_000,
          levelUpCoefficient: 100,
          impactCount: 1,
        })),
      ],
      aggregateCoefficient: 24_000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'control'],
    minTargets: null,
    effect: null,
  },
  {
    skillId: 4103,
    classId: 4,
    slot: 4,
    displayName: 'Projétil Explosivo',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 26_000,
    skillCostType: 2,
    skillCost: 2100,
    attackAnimationMs: 1100,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [410301, 410302, 410303],
    impactOffsetsMs: [],
    damage: null,
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4107,
    classId: 4,
    slot: 5,
    displayName: 'Seta do Clarão',
    unlock: { kind: 'level', level: 5 },
    cooldownMs: 35_000,
    skillCostType: 2,
    skillCost: 4000,
    attackAnimationMs: 1000,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [410701, 410702],
    impactOffsetsMs: [790],
    damage: damage([[410702, 19_000, 400]], 1, 3),
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4108,
    classId: 4,
    slot: 6,
    displayName: 'Arco Celestial',
    unlock: { kind: 'level', level: 8 },
    cooldownMs: 20_000,
    skillCostType: 2,
    skillCost: 2800,
    attackAnimationMs: 1133,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [410801, 410802],
    impactOffsetsMs: [900],
    damage: damage([[410802, 6600, 132]]),
    roles: ['aoe'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4111,
    classId: 4,
    slot: 7,
    displayName: 'Olho da Mente',
    unlock: { kind: 'level', level: 16 },
    cooldownMs: 30_000,
    skillCostType: 2,
    skillCost: 2000,
    attackAnimationMs: 1000,
    hitCount: 5,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [411101],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4105,
    classId: 4,
    slot: 8,
    displayName: 'Prisão de Gelo',
    unlock: { kind: 'level', level: 24 },
    cooldownMs: 33_000,
    skillCostType: 2,
    skillCost: 2500,
    attackAnimationMs: 1000,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [410501, 410502],
    impactOffsetsMs: [900],
    damage: damage([[410502, 4_000, 100]]),
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4109,
    classId: 4,
    slot: 9,
    displayName: 'Escudo de Aniquilação',
    unlock: { kind: 'level', level: 32 },
    cooldownMs: 28_000,
    skillCostType: 2,
    skillCost: 2160,
    attackAnimationMs: 1000,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 224,
    attackIds: [410901, 410902, 410903],
    impactOffsetsMs: [480, 520],
    damage: damage([
      [410902, 11_000, 250],
      [410903, 11_000, 250],
    ]),
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4104,
    classId: 4,
    slot: 10,
    displayName: 'Escudo da Névoa Venenosa',
    unlock: { kind: 'level', level: 40 },
    cooldownMs: 40_000,
    skillCostType: 2,
    skillCost: 4800,
    attackAnimationMs: 1267,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 224,
    attackIds: [410401, 410402, 410403],
    impactOffsetsMs: [750],
    damage: damage([[410403, 5_500, 110]]),
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4110,
    classId: 4,
    slot: 11,
    displayName: 'Seta da Procura',
    unlock: { kind: 'level', level: 48 },
    cooldownMs: 38_000,
    skillCostType: 2,
    skillCost: 4000,
    attackAnimationMs: 1900,
    impactOffsetsMs: [1250],
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 320,
    attackIds: [411000, 411001, 411002],
    damage: damage([[411002, 42_000, 840]]),
    roles: ['execution', 'single-target'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 4112,
    classId: 4,
    slot: 12,
    displayName: 'Ocultação',
    unlock: { kind: 'level', level: 56 },
    cooldownMs: 60_000,
    skillCostType: 2,
    skillCost: 5500,
    attackAnimationMs: 600,
    hitCount: 5,
    requiresTarget: false,
    browserRangePx: 0,
    attackIds: [411201, 411202, 411203],
    damage: null,
    roles: ['survival-utility'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
];

const LANCER_SKILLS: readonly Mir4SkillDef[] = [
  {
    skillId: 5201,
    classId: 5,
    slot: 1,
    displayName: 'Ataque Devastador',
    unlock: { kind: 'initial-deck' },
    cooldownMs: 24_000,
    skillCostType: 2,
    skillCost: 1500,
    attackAnimationMs: 1833,
    hitCount: 6,
    impactOffsetsMs: [480, 690, 880, 1000, 1150, 1300],
    requiresTarget: true,
    browserRangePx: 112,
    attackIds: [520101, 520102, 520103],
    damage: {
      components: [
        {
          attackId: 520101,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4_000,
          levelUpCoefficient: 60,
          impactCount: 3,
        },
        {
          attackId: 520101,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 6_000,
          levelUpCoefficient: 100,
          impactCount: 3,
        },
        {
          attackId: 520102,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4_000,
          levelUpCoefficient: 60,
          impactCount: 2,
        },
        {
          attackId: 520102,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 5_000,
          levelUpCoefficient: 100,
          impactCount: 2,
        },
        {
          attackId: 520103,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4_000,
          levelUpCoefficient: 80,
          impactCount: 1,
        },
        {
          attackId: 520103,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 5_000,
          levelUpCoefficient: 100,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 28_000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'row-total-impact-vector',
    },
    roles: ['aoe'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(5101),
    slot: 2,
    displayName: 'Lâmina Crescente',
    unlock: { kind: 'initial-deck' },
    browserRangePx: 104,
    impactOffsetsMs: [400, 1_120],
    roles: ['aoe', 'mobility', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(5104),
    slot: 3,
    displayName: 'Pontapé Nirvana',
    unlock: { kind: 'initial-deck' },
    impactOffsetsMs: [600],
    roles: ['aoe', 'mobility', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    ...extractedSkill(5301),
    slot: 4,
    displayName: 'Golpe Duplo',
    unlock: { kind: 'initial-deck' },
    impactOffsetsMs: [400, 1040, 1200],
    roles: ['aoe', 'mobility'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5401,
    classId: 5,
    slot: 5,
    displayName: 'Tempestade Arrebatadora',
    unlock: { kind: 'level', level: 5 },
    cooldownMs: 44_000,
    skillCostType: 2,
    skillCost: 3400,
    attackAnimationMs: 1067,
    hitCount: 6,
    requiresTarget: true,
    browserRangePx: 72,
    attackIds: [540101, 540102, 540103, 540104, 540105, 540106],
    impactOffsetsMs: [20, 240, 400, 510, 660, 840],
    damage: {
      components: [
        {
          attackId: 540101,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 1_000,
          levelUpCoefficient: 20,
          impactCount: 1,
        },
        {
          attackId: 540101,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 3_000,
          levelUpCoefficient: 60,
          impactCount: 1,
        },
        ...[
          [540102, 1_000, 30, 3_000, 60],
          [540103, 1_000, 30, 3_000, 70],
          [540104, 2_000, 40, 3_000, 70],
          [540105, 2_000, 40, 4_000, 70],
          [540106, 2_000, 40, 4_000, 70],
        ].flatMap(([attackId, physical, physicalLevel, magic, magicLevel]) => [
          {
            attackId,
            damageType: 1,
            damageAttribute: 0,
            coefficient: physical,
            levelUpCoefficient: physicalLevel,
            impactCount: 1,
          },
          {
            attackId,
            damageType: 2,
            damageAttribute: 0,
            coefficient: magic,
            levelUpCoefficient: magicLevel,
            impactCount: 1,
          },
        ]),
      ],
      aggregateCoefficient: 29_000,
      aggregateLevelUpCoefficient: 600,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5102,
    classId: 5,
    slot: 6,
    displayName: 'Cauda do Dragão',
    unlock: { kind: 'level', level: 8 },
    cooldownMs: 29_000,
    skillCostType: 2,
    skillCost: 4000,
    attackAnimationMs: 1667,
    hitCount: 3,
    requiresTarget: true,
    browserRangePx: 88,
    attackIds: [510201, 510202, 510203, 510204],
    impactOffsetsMs: [400, 790, 890],
    damage: {
      components: [
        {
          attackId: 510202,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 16_000,
          levelUpCoefficient: 270,
          impactCount: 1,
        },
        {
          attackId: 510203,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 16_000,
          levelUpCoefficient: 370,
          impactCount: 1,
        },
        {
          attackId: 510204,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4_000,
          levelUpCoefficient: 60,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 36_000,
      aggregateLevelUpCoefficient: 700,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff', 'mobility'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5103,
    classId: 5,
    slot: 7,
    displayName: 'Dragão Ascendente',
    unlock: { kind: 'level', level: 16 },
    cooldownMs: 25_000,
    skillCostType: 2,
    skillCost: 2500,
    attackAnimationMs: 2000,
    hitCount: 6,
    requiresTarget: true,
    browserRangePx: 112,
    impactOffsetsMs: [580, 960, 1240],
    attackIds: [510301, 510302, 510303, 510304],
    damage: {
      components: [
        {
          attackId: 510302,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4_000,
          levelUpCoefficient: 60,
          impactCount: 1,
        },
        {
          attackId: 510302,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 5_000,
          levelUpCoefficient: 100,
          impactCount: 1,
        },
        {
          attackId: 510303,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4_000,
          levelUpCoefficient: 60,
          impactCount: 1,
        },
        {
          attackId: 510303,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 5_000,
          levelUpCoefficient: 100,
          impactCount: 1,
        },
        {
          attackId: 510304,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4_000,
          levelUpCoefficient: 80,
          impactCount: 1,
        },
        {
          attackId: 510304,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 6_000,
          levelUpCoefficient: 100,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 28_000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'per-impact',
    },
    roles: ['aoe', 'debuff'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5303,
    classId: 5,
    slot: 8,
    displayName: 'Ataque Esmagador',
    unlock: { kind: 'level', level: 24 },
    cooldownMs: 38_000,
    skillCostType: 2,
    skillCost: 4200,
    attackAnimationMs: 1760,
    hitCount: 4,
    requiresTarget: true,
    browserRangePx: 144,
    attackIds: [530301, 530302, 530303],
    damage: {
      components: [
        {
          attackId: 530302,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 18_000,
          levelUpCoefficient: 350,
          impactCount: 3,
        },
        {
          attackId: 530303,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 6_000,
          levelUpCoefficient: 150,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 24_000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'row-total-impact-vector',
    },
    roles: ['aoe', 'debuff'],
    impactOffsetsMs: [400, 550, 700, 890],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5403,
    classId: 5,
    slot: 9,
    displayName: 'Muralha de Vento',
    unlock: { kind: 'level', level: 32 },
    cooldownMs: 45_000,
    skillCostType: 2,
    skillCost: 3800,
    attackAnimationMs: 800,
    hitCount: 5,
    requiresTarget: true,
    browserRangePx: 96,
    attackIds: [540301, 540302, 540303, 540304, 540305],
    damage: {
      components: [
        {
          attackId: 540301,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 3_000,
          levelUpCoefficient: 70,
          impactCount: 1,
        },
        {
          attackId: 540301,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 2_000,
          levelUpCoefficient: 40,
          impactCount: 1,
        },
        {
          attackId: 540303,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 3_000,
          levelUpCoefficient: 70,
          impactCount: 2,
        },
        {
          attackId: 540303,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 2_000,
          levelUpCoefficient: 40,
          impactCount: 2,
        },
        {
          attackId: 540304,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4_000,
          levelUpCoefficient: 80,
          impactCount: 1,
        },
        {
          attackId: 540304,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 2_000,
          levelUpCoefficient: 60,
          impactCount: 1,
        },
        {
          attackId: 540305,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 4_000,
          levelUpCoefficient: 80,
          impactCount: 1,
        },
        {
          attackId: 540305,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 2_000,
          levelUpCoefficient: 60,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 22_000,
      aggregateLevelUpCoefficient: 500,
      allocationMode: 'row-total-impact-vector',
    },
    roles: ['aoe', 'survival-utility'],
    impactOffsetsMs: [20, 300, 400, 510, 620],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5205,
    classId: 5,
    slot: 10,
    displayName: 'Lança Penetrante',
    unlock: { kind: 'level', level: 40 },
    cooldownMs: 37_000,
    skillCostType: 2,
    skillCost: 4800,
    attackAnimationMs: 1440,
    hitCount: 1,
    requiresTarget: true,
    browserRangePx: 272,
    impactOffsetsMs: [380, 400],
    attackIds: [520501, 520502, 520503],
    damage: {
      components: [
        {
          attackId: 520502,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 8000,
          levelUpCoefficient: 200,
          impactCount: 1,
        },
        {
          attackId: 520502,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 13_000,
          levelUpCoefficient: 200,
          impactCount: 1,
        },
        {
          attackId: 520503,
          damageType: 1,
          damageAttribute: 0,
          coefficient: 8000,
          levelUpCoefficient: 200,
          impactCount: 1,
        },
        {
          attackId: 520503,
          damageType: 2,
          damageAttribute: 0,
          coefficient: 13_000,
          levelUpCoefficient: 200,
          impactCount: 1,
        },
      ],
      aggregateCoefficient: 42_000,
      aggregateLevelUpCoefficient: 800,
      allocationMode: 'per-impact',
    },
    roles: ['debuff', 'single-target'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5304,
    classId: 5,
    slot: 11,
    displayName: 'Absorção',
    unlock: { kind: 'level', level: 48 },
    cooldownMs: 63_000,
    skillCostType: 2,
    skillCost: 2400,
    attackAnimationMs: 1260,
    hitCount: 0,
    requiresTarget: true,
    browserRangePx: 112,
    attackIds: [530401],
    impactOffsetsMs: [950],
    damage: damage([[530401, 11_000, 200]]),
    roles: ['survival-utility', 'single-target'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
  {
    skillId: 5202,
    classId: 5,
    slot: 12,
    displayName: 'Golpe Relâmpago',
    unlock: { kind: 'level', level: 56 },
    cooldownMs: 25_000,
    skillCostType: 2,
    skillCost: 4440,
    attackAnimationMs: 1200,
    hitCount: 2,
    impactOffsetsMs: [600],
    requiresTarget: true,
    browserRangePx: 192,
    attackIds: [520201, 520202],
    damage: damage([[520202, 28_000, 600]]),
    roles: ['mobility', 'debuff', 'single-target'],
    minTargets: null,
    effect: null,
    provenance: 'native-catalog',
    sourceRuntimeStatus: 'official-client-catalog',
  },
];

export const MIR4_SKILLS: readonly Mir4SkillDef[] = [
  ...WARRIOR_SKILLS,
  ...SORCERER_SKILLS,
  ...TAOIST_SKILLS,
  ...ARBALIST_SKILLS,
  ...LANCER_SKILLS,
  ...EXTRACTED_MIR4_SKILLS.filter(
    (skill) =>
      skill.classId !== 1 &&
      skill.classId !== 2 &&
      skill.classId !== 3 &&
      skill.classId !== 4 &&
      skill.classId !== 5,
  ),
];

const SKILL_INDEX = new Map(MIR4_SKILLS.map((skill) => [skill.skillId, skill]));
const CLASS_SKILL_INDEX = new Map<number, Mir4SkillDef[]>();
for (const skill of MIR4_SKILLS) {
  const skills = CLASS_SKILL_INDEX.get(skill.classId) ?? [];
  skills.push(skill);
  CLASS_SKILL_INDEX.set(skill.classId, skills);
}
for (const skills of CLASS_SKILL_INDEX.values()) skills.sort((a, b) => a.slot - b.slot);

export function mir4SkillById(skillId: number): Mir4SkillDef | null {
  return SKILL_INDEX.get(skillId) ?? null;
}

export function mir4SkillsForClass(classId: 1 | 2 | 3 | 4 | 5): readonly Mir4SkillDef[] {
  return CLASS_SKILL_INDEX.get(classId) ?? [];
}
