// Generated from the source project server/mir4-spirit-summon-v1.js.
// DO NOT HAND-EDIT VALUES. Stats are the authoritative equipmentEffect /
// GRADE_STATS blocks verbatim; visuals stay reference-only placeholders.
// Names are PT-BR source copy; the English i18n source lands with the HUD.

export interface Mir4SpiritDef {
  id: string;
  name: string;
  grade: number;
  gradeKey: string;
  stats: Record<string, number>;
}

export const MIR4_SPIRITS_CATALOG: readonly Mir4SpiritDef[] = [
  {
    id: 'spirit-common-01',
    name: 'Faisca da Campina',
    grade: 1,
    gradeKey: 'common',
    stats: {
      physicalAttack: 2,
      magicAttack: 2,
      physicalDefense: 2,
      magicDefense: 2,
      accuracy: 1,
      critical: 0,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-common-02',
    name: 'Brisa do Arroio',
    grade: 1,
    gradeKey: 'common',
    stats: {
      physicalAttack: 2,
      magicAttack: 2,
      physicalDefense: 2,
      magicDefense: 2,
      accuracy: 1,
      critical: 0,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-common-03',
    name: 'Folha Vigia',
    grade: 1,
    gradeKey: 'common',
    stats: {
      physicalAttack: 2,
      magicAttack: 2,
      physicalDefense: 2,
      magicDefense: 2,
      accuracy: 1,
      critical: 0,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-common-04',
    name: 'Eco de Pedra',
    grade: 1,
    gradeKey: 'common',
    stats: {
      physicalAttack: 2,
      magicAttack: 2,
      physicalDefense: 2,
      magicDefense: 2,
      accuracy: 1,
      critical: 0,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-uncommon-01',
    name: 'Lume da Alvorada',
    grade: 2,
    gradeKey: 'uncommon',
    stats: {
      physicalAttack: 5,
      magicAttack: 5,
      physicalDefense: 5,
      magicDefense: 5,
      accuracy: 3,
      critical: 0,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-uncommon-02',
    name: 'Ninfa da Bruma',
    grade: 2,
    gradeKey: 'uncommon',
    stats: {
      physicalAttack: 5,
      magicAttack: 5,
      physicalDefense: 5,
      magicDefense: 5,
      accuracy: 3,
      critical: 0,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-uncommon-03',
    name: 'Guardiao de Musgo',
    grade: 2,
    gradeKey: 'uncommon',
    stats: {
      physicalAttack: 5,
      magicAttack: 5,
      physicalDefense: 5,
      magicDefense: 5,
      accuracy: 3,
      critical: 0,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-uncommon-04',
    name: 'Salamandra do Vale',
    grade: 2,
    gradeKey: 'uncommon',
    stats: {
      physicalAttack: 5,
      magicAttack: 5,
      physicalDefense: 5,
      magicDefense: 5,
      accuracy: 3,
      critical: 0,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-rare-01',
    name: 'Raposa de Ambar',
    grade: 3,
    gradeKey: 'rare',
    stats: {
      physicalAttack: 10,
      magicAttack: 10,
      physicalDefense: 10,
      magicDefense: 10,
      accuracy: 6,
      critical: 1,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-rare-02',
    name: 'Coruja do Poente',
    grade: 3,
    gradeKey: 'rare',
    stats: {
      physicalAttack: 10,
      magicAttack: 10,
      physicalDefense: 10,
      magicDefense: 10,
      accuracy: 6,
      critical: 1,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-rare-03',
    name: 'Draco de Raiz',
    grade: 3,
    gradeKey: 'rare',
    stats: {
      physicalAttack: 10,
      magicAttack: 10,
      physicalDefense: 10,
      magicDefense: 10,
      accuracy: 6,
      critical: 1,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-rare-04',
    name: 'Oraculo das Colinas',
    grade: 3,
    gradeKey: 'rare',
    stats: {
      physicalAttack: 10,
      magicAttack: 10,
      physicalDefense: 10,
      magicDefense: 10,
      accuracy: 6,
      critical: 1,
      penetrationBps: 0,
    },
  },
  {
    id: 'spirit-epic-01',
    name: 'Avatar do Eclipse',
    grade: 4,
    gradeKey: 'epic',
    stats: {
      physicalAttack: 20,
      magicAttack: 20,
      physicalDefense: 20,
      magicDefense: 20,
      accuracy: 12,
      critical: 2,
      penetrationBps: 50,
    },
  },
  {
    id: 'spirit-epic-02',
    name: 'Ifrit Rubro',
    grade: 4,
    gradeKey: 'epic',
    stats: {
      physicalAttack: 20,
      magicAttack: 20,
      physicalDefense: 20,
      magicDefense: 20,
      accuracy: 12,
      critical: 2,
      penetrationBps: 50,
    },
  },
  {
    id: 'spirit-epic-03',
    name: 'Cervo Astral',
    grade: 4,
    gradeKey: 'epic',
    stats: {
      physicalAttack: 20,
      magicAttack: 20,
      physicalDefense: 20,
      magicDefense: 20,
      accuracy: 12,
      critical: 2,
      penetrationBps: 50,
    },
  },
  {
    id: 'spirit-epic-04',
    name: 'Sentinela de Jade',
    grade: 4,
    gradeKey: 'epic',
    stats: {
      physicalAttack: 20,
      magicAttack: 20,
      physicalDefense: 20,
      magicDefense: 20,
      accuracy: 12,
      critical: 2,
      penetrationBps: 50,
    },
  },
  {
    id: 'spirit-epic-05',
    name: 'Lobo Solar',
    grade: 4,
    gradeKey: 'epic',
    stats: {
      physicalAttack: 20,
      magicAttack: 20,
      physicalDefense: 20,
      magicDefense: 20,
      accuracy: 12,
      critical: 2,
      penetrationBps: 50,
    },
  },
  {
    id: 'spirit-epic-06',
    name: 'Quimera Etérea',
    grade: 4,
    gradeKey: 'epic',
    stats: {
      physicalAttack: 20,
      magicAttack: 20,
      physicalDefense: 20,
      magicDefense: 20,
      accuracy: 12,
      critical: 2,
      penetrationBps: 50,
    },
  },
  {
    id: 'spirit-legendary-01',
    name: 'Titã Terrestre',
    grade: 5,
    gradeKey: 'legendary',
    stats: {
      physicalAttack: 40,
      magicAttack: 40,
      physicalDefense: 40,
      magicDefense: 40,
      accuracy: 24,
      critical: 4,
      penetrationBps: 100,
    },
  },
  {
    id: 'spirit-legendary-02',
    name: 'Fenix da Alvorada',
    grade: 5,
    gradeKey: 'legendary',
    stats: {
      physicalAttack: 40,
      magicAttack: 40,
      physicalDefense: 40,
      magicDefense: 40,
      accuracy: 24,
      critical: 4,
      penetrationBps: 100,
    },
  },
  {
    id: 'spirit-legendary-03',
    name: 'Arconte Imperial',
    grade: 5,
    gradeKey: 'legendary',
    stats: {
      physicalAttack: 40,
      magicAttack: 40,
      physicalDefense: 40,
      magicDefense: 40,
      accuracy: 24,
      critical: 4,
      penetrationBps: 100,
    },
  },
  {
    id: 'spirit-legendary-04',
    name: 'Leviata de Cristal',
    grade: 5,
    gradeKey: 'legendary',
    stats: {
      physicalAttack: 40,
      magicAttack: 40,
      physicalDefense: 40,
      magicDefense: 40,
      accuracy: 24,
      critical: 4,
      penetrationBps: 100,
    },
  },
  {
    id: 'spirit-legendary-05',
    name: 'Unicornio do Vazio',
    grade: 5,
    gradeKey: 'legendary',
    stats: {
      physicalAttack: 40,
      magicAttack: 40,
      physicalDefense: 40,
      magicDefense: 40,
      accuracy: 24,
      critical: 4,
      penetrationBps: 100,
    },
  },
  {
    id: 'spirit-legendary-06',
    name: 'Manticora Aurea',
    grade: 5,
    gradeKey: 'legendary',
    stats: {
      physicalAttack: 40,
      magicAttack: 40,
      physicalDefense: 40,
      magicDefense: 40,
      accuracy: 24,
      critical: 4,
      penetrationBps: 100,
    },
  },
  {
    id: 'spirit-mythical-01',
    name: 'Alma Primordial',
    grade: 6,
    gradeKey: 'mythical',
    stats: {
      physicalAttack: 80,
      magicAttack: 80,
      physicalDefense: 80,
      magicDefense: 80,
      accuracy: 48,
      critical: 8,
      penetrationBps: 250,
    },
  },
  {
    id: 'spirit-mythical-02',
    name: 'Fenix Eterna',
    grade: 6,
    gradeKey: 'mythical',
    stats: {
      physicalAttack: 80,
      magicAttack: 80,
      physicalDefense: 80,
      magicDefense: 80,
      accuracy: 48,
      critical: 8,
      penetrationBps: 250,
    },
  },
  {
    id: 'spirit-mythical-03',
    name: 'Kirin Celestial',
    grade: 6,
    gradeKey: 'mythical',
    stats: {
      physicalAttack: 80,
      magicAttack: 80,
      physicalDefense: 80,
      magicDefense: 80,
      accuracy: 48,
      critical: 8,
      penetrationBps: 250,
    },
  },
  {
    id: 'spirit-mythical-04',
    name: 'Beemote do Firmamento',
    grade: 6,
    gradeKey: 'mythical',
    stats: {
      physicalAttack: 80,
      magicAttack: 80,
      physicalDefense: 80,
      magicDefense: 80,
      accuracy: 48,
      critical: 8,
      penetrationBps: 250,
    },
  },
  {
    id: 'spirit-mythical-05',
    name: 'Serafim Abissal',
    grade: 6,
    gradeKey: 'mythical',
    stats: {
      physicalAttack: 80,
      magicAttack: 80,
      physicalDefense: 80,
      magicDefense: 80,
      accuracy: 48,
      critical: 8,
      penetrationBps: 250,
    },
  },
  {
    id: 'spirit-mythical-06',
    name: 'Hidra do Tempo',
    grade: 6,
    gradeKey: 'mythical',
    stats: {
      physicalAttack: 80,
      magicAttack: 80,
      physicalDefense: 80,
      magicDefense: 80,
      accuracy: 48,
      critical: 8,
      penetrationBps: 250,
    },
  },
];

const BY_ID = new Map(MIR4_SPIRITS_CATALOG.map((m) => [m.id, m]));
export function mir4SpiritById(id: string): Mir4SpiritDef | null {
  return BY_ID.get(id) ?? null;
}
