// Generated from the source project server/data/
// mir4-mmo-world-runtime-v1.json (via mir4-mmo-world-content-v1.js). DO NOT
// HAND-EDIT VALUES. The 20-map progression arc: sequence, act, level band,
// environment (with its fork-biome mapping), city flags, gear ranks, and the
// forward portal chain. Zone geometry stays TMX-semantic (never ported):
// each map becomes a procedural zone band authored against this table.

import type { BiomeId } from '../../types';

export interface Mir4ArcMap {
  sequence: number;
  mapId: string;
  name: string;
  act: number;
  levelMin: number;
  levelMax: number;
  environment: string;
  biome: BiomeId;
  isCity: boolean;
  targetGearRank: number;
  zoneCount: number;
  npcCount: number;
  portalTo: readonly string[];
}

export const MIR4_WORLD_ARC: readonly Mir4ArcMap[] = [
  {
    sequence: 1,
    mapId: 'm01-vila-do-vau',
    name: 'Vila do Vau',
    act: 1,
    levelMin: 1,
    levelMax: 10,
    environment: 'grass-land-forest-river',
    biome: 'vale',
    isCity: false,
    targetGearRank: 2,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m02-trilha-dos-juncos'],
  },
  {
    sequence: 2,
    mapId: 'm02-trilha-dos-juncos',
    name: 'Posto das Duas Pontes',
    act: 1,
    levelMin: 11,
    levelMax: 20,
    environment: 'grass-land-wetland',
    biome: 'marsh',
    isCity: false,
    targetGearRank: 2,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m03-bosque-do-vale'],
  },
  {
    sequence: 3,
    mapId: 'm03-bosque-do-vale',
    name: 'Abrigo das Silvas',
    act: 1,
    levelMin: 21,
    levelMax: 30,
    environment: 'ancient-forest',
    biome: 'vale',
    isCity: false,
    targetGearRank: 3,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m04-ruinas-da-encosta'],
  },
  {
    sequence: 4,
    mapId: 'm04-ruinas-da-encosta',
    name: 'Vau Dourado',
    act: 1,
    levelMin: 31,
    levelMax: 40,
    environment: 'forest-ancient-ruins-highland',
    biome: 'peaks',
    isCity: true,
    targetGearRank: 4,
    zoneCount: 6,
    npcCount: 16,
    portalTo: ['m05-clareira-da-fenda'],
  },
  {
    sequence: 5,
    mapId: 'm05-clareira-da-fenda',
    name: 'Posto da Fenda',
    act: 2,
    levelMin: 41,
    levelMax: 50,
    environment: 'ruins-open-crypt',
    biome: 'cave',
    isCity: false,
    targetGearRank: 4,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m06-criptas-de-pedra-vela'],
  },
  {
    sequence: 6,
    mapId: 'm06-criptas-de-pedra-vela',
    name: 'Capela Fortificada',
    act: 2,
    levelMin: 51,
    levelMax: 60,
    environment: 'crypt-cemetery',
    biome: 'haunt',
    isCity: false,
    targetGearRank: 5,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m07-galerias-do-ossario'],
  },
  {
    sequence: 7,
    mapId: 'm07-galerias-do-ossario',
    name: 'Bastião do Sino',
    act: 2,
    levelMin: 61,
    levelMax: 70,
    environment: 'ossuary-underground',
    biome: 'cave',
    isCity: false,
    targetGearRank: 5,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m08-fortaleza-de-brumapedra'],
  },
  {
    sequence: 8,
    mapId: 'm08-fortaleza-de-brumapedra',
    name: 'Brumaforte',
    act: 2,
    levelMin: 71,
    levelMax: 80,
    environment: 'highlands-fortress',
    biome: 'peaks',
    isCity: true,
    targetGearRank: 6,
    zoneCount: 6,
    npcCount: 14,
    portalTo: ['m09-pantano-das-lanternas'],
  },
  {
    sequence: 9,
    mapId: 'm09-pantano-das-lanternas',
    name: 'Palafita das Luzes',
    act: 3,
    levelMin: 81,
    levelMax: 90,
    environment: 'swamp-fen-lights',
    biome: 'fen',
    isCity: false,
    targetGearRank: 6,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m10-charcos-do-rei-bog'],
  },
  {
    sequence: 10,
    mapId: 'm10-charcos-do-rei-bog',
    name: 'Posto das Tábuas',
    act: 3,
    levelMin: 91,
    levelMax: 100,
    environment: 'deep-swamp',
    biome: 'fen',
    isCity: false,
    targetGearRank: 7,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m11-mangue-das-sanguessugas'],
  },
  {
    sequence: 11,
    mapId: 'm11-mangue-das-sanguessugas',
    name: 'Refúgio do Sal',
    act: 3,
    levelMin: 101,
    levelMax: 110,
    environment: 'mangrove-channels',
    biome: 'marsh',
    isCity: false,
    targetGearRank: 7,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m12-porto-dos-juncos'],
  },
  {
    sequence: 12,
    mapId: 'm12-porto-dos-juncos',
    name: 'Porto Lúmen',
    act: 3,
    levelMin: 111,
    levelMax: 120,
    environment: 'coast-mangrove-port',
    biome: 'beach',
    isCity: true,
    targetGearRank: 8,
    zoneCount: 6,
    npcCount: 14,
    portalTo: ['m13-dunas-de-vidro'],
  },
  {
    sequence: 13,
    mapId: 'm13-dunas-de-vidro',
    name: 'Oásis do Véu',
    act: 4,
    levelMin: 121,
    levelMax: 130,
    environment: 'desert-oasis-glass',
    biome: 'desert',
    isCity: false,
    targetGearRank: 8,
    zoneCount: 6,
    npcCount: 10,
    portalTo: ['m14-necropole-de-akhet'],
  },
  {
    sequence: 14,
    mapId: 'm14-necropole-de-akhet',
    name: 'Acampamento da Lua',
    act: 4,
    levelMin: 131,
    levelMax: 140,
    environment: 'desert-necropolis',
    biome: 'desert',
    isCity: false,
    targetGearRank: 9,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m15-caldeira-de-cinerita'],
  },
  {
    sequence: 15,
    mapId: 'm15-caldeira-de-cinerita',
    name: 'Posto Obsidiano',
    act: 4,
    levelMin: 141,
    levelMax: 150,
    environment: 'desert-volcano',
    biome: 'volcano',
    isCity: false,
    targetGearRank: 9,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m16-forja-do-sol-partido'],
  },
  {
    sequence: 16,
    mapId: 'm16-forja-do-sol-partido',
    name: 'Forja Rubra',
    act: 4,
    levelMin: 151,
    levelMax: 160,
    environment: 'volcano-citadel',
    biome: 'volcano',
    isCity: true,
    targetGearRank: 10,
    zoneCount: 6,
    npcCount: 16,
    portalTo: ['m17-tundra-dos-uivos'],
  },
  {
    sequence: 17,
    mapId: 'm17-tundra-dos-uivos',
    name: 'Abrigo Branca-Lenha',
    act: 5,
    levelMin: 161,
    levelMax: 170,
    environment: 'snow-cold-forest',
    biome: 'frost',
    isCity: false,
    targetGearRank: 10,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m18-passo-do-jarl'],
  },
  {
    sequence: 18,
    mapId: 'm18-passo-do-jarl',
    name: 'Torre da Aurora',
    act: 5,
    levelMin: 171,
    levelMax: 180,
    environment: 'snow-tiered-mountain',
    biome: 'frost',
    isCity: false,
    targetGearRank: 11,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m19-veu-da-noite'],
  },
  {
    sequence: 19,
    mapId: 'm19-veu-da-noite',
    name: 'Farol Velado',
    act: 5,
    levelMin: 181,
    levelMax: 190,
    environment: 'night-rift-plateau',
    biome: 'night',
    isCity: false,
    targetGearRank: 11,
    zoneCount: 6,
    npcCount: 9,
    portalTo: ['m20-bastilha-do-eclipse'],
  },
  {
    sequence: 20,
    mapId: 'm20-bastilha-do-eclipse',
    name: 'Cidade Aurora',
    act: 5,
    levelMin: 191,
    levelMax: 200,
    environment: 'ice-night-city',
    biome: 'night',
    isCity: true,
    targetGearRank: 12,
    zoneCount: 6,
    npcCount: 17,
    portalTo: [],
  },
];

export const MIR4_WORLD_ARC_BY_MAP = new Map(MIR4_WORLD_ARC.map((m) => [m.mapId, m]));
