// Bakes The Last Keep interior floor plan into one static WebP plate per STORY
// (public/map_bg/lastkeep_<story>.webp) plus the generated manifest the
// freshness guard pins (src/ui/lastkeep_map_manifest.generated.ts). The plates
// are pure functions of the authored LASTKEEP layout (rooms + doors), rendered
// through the same lastKeepPlanSvg source the runtime painter falls back to,
// so the shipped image and the fallback are the same drawing by construction.
//
// Run via `npm run assets:lastkeepmap` after ANY change to the keep's layout
// or the plan palette (the freshness guard tests/lastkeep_map_baked.test.ts
// reds until you do). Mirrors the esbuild-bundle pattern in
// scripts/build_map_backgrounds.mjs (never import raw .ts from an .mjs).
import fs from 'node:fs';
import path from 'node:path';
import * as esbuild from 'esbuild';
import sharp from 'sharp';

const root = process.cwd();

const entrySource = `
  export {
    LASTKEEP_STORY_IDS,
    lastKeepPlanFingerprint,
    lastKeepPlanSvg,
    lastKeepPlateSize,
  } from './src/ui/lastkeep_map_view.ts';
`;

const built = await esbuild.build({
  stdin: {
    contents: entrySource,
    resolveDir: root,
    sourcefile: 'lastkeep-map-entry.ts',
    loader: 'ts',
  },
  bundle: true,
  platform: 'node',
  format: 'esm',
  write: false,
  logLevel: 'silent',
});
const dataUrl = `data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`;
const { LASTKEEP_STORY_IDS, lastKeepPlanFingerprint, lastKeepPlanSvg, lastKeepPlateSize } =
  await import(dataUrl);

const outDir = path.join(root, 'public', 'map_bg');
fs.mkdirSync(outDir, { recursive: true });

const { w, h } = lastKeepPlateSize();
for (const storyId of LASTKEEP_STORY_IDS) {
  const started = Date.now();
  const svg = lastKeepPlanSvg(storyId);
  const file = path.join(outDir, `lastkeep_${storyId}.webp`);
  await sharp(Buffer.from(svg)).webp({ quality: 90 }).toFile(file);
  const kb = Math.round(fs.statSync(file).size / 1024);
  console.log(`baked lastkeep_${storyId}: ${w}x${h} ${kb}KB in ${Date.now() - started}ms`);
}

const manifestPath = path.join(root, 'src', 'ui', 'lastkeep_map_manifest.generated.ts');
const manifest = `// GENERATED by scripts/build_lastkeep_map.mjs; do not edit by hand.
// Re-bake with \`npm run assets:lastkeepmap\` after any Last Keep layout or
// plan-palette change (tests/lastkeep_map_baked.test.ts guards freshness).
// Plates live in public/map_bg/lastkeep_<story>.webp.

export const BAKED_LASTKEEP_MAP = {
  fingerprint: '${lastKeepPlanFingerprint()}',
  plateWidth: ${w},
  plateHeight: ${h},
  stories: ${JSON.stringify([...LASTKEEP_STORY_IDS])},
} as const;
`;
fs.writeFileSync(manifestPath, manifest);
console.log(`wrote ${manifestPath} (${LASTKEEP_STORY_IDS.length} stories)`);
