// Bakes Dawnhold Castle's interior floor plan into one static WebP plate per
// STORY (public/map_bg/dawnhold_<story>.webp) plus the generated manifest the
// freshness guard pins (src/ui/dawnhold_map_manifest.generated.ts). The plates
// are pure functions of the authored DAWNHOLD layout (rooms + doors), rendered
// through the same dawnholdPlanSvg source the runtime painter falls back to,
// so the shipped image and the fallback are the same drawing by construction.
//
// Run via `npm run assets:dawnholdmap` after ANY change to the palace's layout
// or the plan palette (the freshness guard tests/dawnhold_map_baked.test.ts
// reds until you do). Mirrors scripts/build_lastkeep_map.mjs (never import raw
// .ts from an .mjs).
import fs from 'node:fs';
import path from 'node:path';
import * as esbuild from 'esbuild';
import sharp from 'sharp';

const root = process.cwd();

const entrySource = `
  export {
    DAWNHOLD_STORY_IDS,
    dawnholdPlanFingerprint,
    dawnholdPlanSvg,
    dawnholdPlateSize,
  } from './src/ui/lastkeep_map_view.ts';
`;

const built = await esbuild.build({
  stdin: {
    contents: entrySource,
    resolveDir: root,
    sourcefile: 'dawnhold-map-entry.ts',
    loader: 'ts',
  },
  bundle: true,
  platform: 'node',
  format: 'esm',
  write: false,
  logLevel: 'silent',
});
const dataUrl = `data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`;
const { DAWNHOLD_STORY_IDS, dawnholdPlanFingerprint, dawnholdPlanSvg, dawnholdPlateSize } =
  await import(dataUrl);

const outDir = path.join(root, 'public', 'map_bg');
fs.mkdirSync(outDir, { recursive: true });

const { w, h } = dawnholdPlateSize();
for (const storyId of DAWNHOLD_STORY_IDS) {
  const started = Date.now();
  const svg = dawnholdPlanSvg(storyId);
  const file = path.join(outDir, `dawnhold_${storyId}.webp`);
  await sharp(Buffer.from(svg)).webp({ quality: 90 }).toFile(file);
  const kb = Math.round(fs.statSync(file).size / 1024);
  console.log(`baked dawnhold_${storyId}: ${w}x${h} ${kb}KB in ${Date.now() - started}ms`);
}

const manifestPath = path.join(root, 'src', 'ui', 'dawnhold_map_manifest.generated.ts');
const manifest = `// GENERATED by scripts/build_dawnhold_map.mjs; do not edit by hand.
// Re-bake with \`npm run assets:dawnholdmap\` after any Dawnhold layout or
// plan-palette change (tests/dawnhold_map_baked.test.ts guards freshness).
// Plates live in public/map_bg/dawnhold_<story>.webp.

export const BAKED_DAWNHOLD_MAP = {
  fingerprint: '${dawnholdPlanFingerprint()}',
  plateWidth: ${w},
  plateHeight: ${h},
  stories: ${JSON.stringify([...DAWNHOLD_STORY_IDS])},
} as const;
`;
fs.writeFileSync(manifestPath, manifest);
console.log(`wrote ${manifestPath} (${DAWNHOLD_STORY_IDS.length} stories)`);
