// Server-authoritative command visibility for profile-specific gameplay.
// The wire vocabulary remains append-only; this gate decides which existing
// tokens may execute in each profile. Generic combat, inventory, social,
// economy and recovery commands stay shared. MIR4 owns its migrated systems
// through the single `mir4` envelope, so a modified client cannot reach the
// hidden classic providers directly.

import { COMMAND_NAMES, type CommandName } from '../world_api';
import { type GameProfile, MIR4_GAME_PROFILE } from './game_profile';

export const MIR4_CLASSIC_ONLY_COMMANDS = [
  // Classic quests and town progression.
  'accept',
  'turnin',
  'abandon',
  'qlinkaccept',
  'set_town_focus',
  'prestige',
  'dev_complete_quest',
  'dev_complete_all_quests',

  // Classic equipment and profession providers. MIR4 equivalents travel in
  // the profile envelope and still reuse native WoC inventory presentation.
  'equip',
  'unequip_item',
  'harvestCorpse',
  'harvest_node',
  'craft_item',
  'place_mobile_station',
  'train_recipe',
  'slot_tool_effect',
  'recharge_tool_effect',
  'disenchant_item',
  'apply_enchant',
  'salvage_item',
  'unbind_item',
  'open_commission_order',
  'cancel_commission_order',
  'accept_commission_order',
  'deliver_commission_order',
  'rift_upgrade_item',
  'rift_enchant_item',
  'rift_socket_gem',

  // Classic class build and companion systems.
  'applyTalents',
  'respec',
  'setSpec',
  'selectTalentRow',
  'saveLoadout',
  'switchLoadout',
  'deleteLoadout',
  'pet_abandon',
  'pet_rename',
  'pet_revive',
  'pet_attack',
  'pet_water_jet',
  'pet_taunt',
  'pet_auto_taunt',
  'pet_auto_water_jet',
  'pet_special',
  'pet_auto_special',
  'pet_feed',
  'pet_heal',
  'pet_mode',

  // Native riding is an implementation detail of MIR4 Mounts. Only the MIR4
  // ownership/equip verbs may mint and operate their bound reins shell.
  'mount_toggle',
  'mount_train_begin',
  'mount_train_answer',
  'mount_train_abort',
  'mount_race_start',
  'mount_race_cancel',
  'learn_riding',

  // Classic competitive, activity-finder, dungeon, delve and Deeds content.
  'arena_queue',
  'arena_leave',
  'arena_augment',
  'card_queue_join',
  'card_queue_leave',
  'play_card',
  'card_forfeit',
  'vcup_queue',
  'vcup_leave',
  'vcup_role',
  'vcup_ready',
  'vcup_bet',
  'vcup_practice',
  'bg_queue',
  'bg_leave',
  'bg_respond',
  'bg_flag',
  'dev_bg_start',
  'df_roles',
  'df_queue',
  'df_queue_leave',
  'df_proposal',
  'df_list_create',
  'df_list_close',
  'df_apply',
  'df_apply_cancel',
  'df_app_respond',
  'enter_crypt',
  'enter_dungeon',
  'leave_crypt',
  'leave_dungeon',
  'set_dungeon_difficulty',
  'heroic_buy',
  'enter_delve',
  'leave_delve',
  'delve_interact',
  'companion_upgrade',
  'delve_buy',
  'lockpick_engage',
  'lockpick_action',
  'lockpick_abort',
  'collect_delve_chest_loot',
  'delve_rite_choose',
  'deed_set_title',
  'deed_set_border',
] as const satisfies readonly CommandName[];

// Explicit allowlist so a future append-only wire token fails closed in MIR4
// until it is deliberately classified. The companion test proves this and the
// classic-only list form one exact, non-overlapping partition of COMMAND_NAMES.
export const MIR4_SHARED_COMMANDS = [
  'castSlot',
  'castAt',
  'cast',
  'cancel_aura',
  'target',
  'tab',
  'targetNearest',
  'tabFriendly',
  'targetNearestFriendly',
  'attack',
  'stopattack',
  'interact',
  'loot',
  'lootRoll',
  'pickup',
  'inv_move',
  'use',
  'discard',
  'lock_item',
  'buy',
  'sell',
  'buyback',
  'sell_all_junk',
  'change_skin',
  'unequip_mech_chroma',
  'claim_event_skin',
  'change_weapon_skin',
  'release',
  'challengeResponse',
  'chat',
  'emote',
  'pinvite',
  'paccept',
  'pdecline',
  'pleave',
  'pkick',
  'ppromote',
  'praid',
  'punraid',
  'pmoveRaid',
  'setLootMaster',
  'masterAssign',
  'setMarker',
  'clearMarker',
  'readyrespond',
  'trade_req',
  'trade_accept',
  'trade_offer',
  'trade_confirm',
  'trade_cancel',
  'duel_req',
  'duel_accept',
  'duel_decline',
  'friend_add',
  'friend_accept',
  'friend_decline',
  'friend_remove',
  'block_add',
  'block_remove',
  'social_refresh',
  'guild_create',
  'guild_invite',
  'guild_accept',
  'guild_decline',
  'guild_leave',
  'guild_kick',
  'guild_promote',
  'guild_demote',
  'guild_transfer',
  'guild_disband',
  'market_search',
  'market_sell_price_check',
  'market_list',
  'market_list_instance',
  'market_buy',
  'market_cancel',
  'market_collect',
  'dev_level',
  'dev_teleport',
  'dev_give',
  'telemetry',
  'equip_bag',
  'unequip_bag',
  'mail_send',
  'mail_take',
  'mail_delete',
  'mail_read',
  'guild_event_create',
  'guild_event_remove',
  'autoloot',
  'resurrect_corpse',
  'resurrect_healer',
  'bank_deposit',
  'bank_withdraw',
  'bank_buy_slots',
  'releaseEmpowered',
  'ignore_add',
  'ignore_remove',
  'stow_weapon',
  'unstuck',
  'resurrect_respond',
  'save_hotbar_layout',
  'guild_set_motd',
  'stopAutoAttackOnTargetSwitch',
  'dev_profiler_invulnerable',
  'guild_bank_deposit_gold',
  'guild_bank_withdraw_gold',
  'guild_bank_deposit',
  'guild_bank_withdraw',
  'guild_bank_buy_slots',
  'guild_bank_log',
  'set_helm',
  'inv_sort',
  'tabPrev',
  'mir4',
] as const satisfies readonly CommandName[];

const MIR4_SHARED_COMMAND_SET: ReadonlySet<CommandName> = new Set(MIR4_SHARED_COMMANDS);
const COMMAND_NAME_SET: ReadonlySet<string> = new Set(COMMAND_NAMES);

export function gameProfileAllowsCommand(profile: GameProfile, command: CommandName): boolean {
  if (profile === MIR4_GAME_PROFILE) return MIR4_SHARED_COMMAND_SET.has(command);
  return command !== 'mir4';
}

/** Unknown wire tokens must still reach the protocol-anomaly arm in the host. */
export function gameProfileAllowsWireCommand(profile: GameProfile, command: unknown): boolean {
  if (typeof command !== 'string' || !COMMAND_NAME_SET.has(command)) return true;
  return gameProfileAllowsCommand(profile, command as CommandName);
}
